<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.fundaciobit.pluginsib.signatureweb</groupId>
    <artifactId>pluginsib-signatureweb</artifactId>
    <version>4.1.0-SNAPSHOT</version>
  </parent>

  <artifactId>pluginsib-signatureweb-afirma_triphase_server_lib</artifactId>
  <packaging>jar</packaging>
  <name>FundacioBit - PluginsIB - SignatureWeb - @firma Triphase Server Lib</name>

  <properties>
    <action_rename_copy>rename</action_rename_copy>
  </properties>

  <dependencies>

    <dependency>
      <groupId>es.gob.afirma</groupId>
      <artifactId>afirma-server-triphase-signer</artifactId>
      <version>${afirma.version}</version>
      <type>war</type>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>es.gob.afirma</groupId>
      <artifactId>afirma-core</artifactId>
      <version>${afirma.version}</version>
    </dependency>

    <dependency>
      <groupId>es.gob.afirma</groupId>
      <artifactId>afirma-server-triphase-signer-core</artifactId>
      <version>${afirma.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.santuario</groupId>
          <artifactId>xmlsec</artifactId>
        </exclusion>
        <exclusion>
          <groupId>javax.xml.bind</groupId>
          <artifactId>jaxb-api</artifactId>
        </exclusion>
        <!--  Necessitam llibreria especial de afirma-crypto-pdf per tema de taula de firmes 
              anomenada afirma-crypto-pdf-for-pluginsib per això feim exclusion d'aquesta -->
        <exclusion>
            <artifactId>afirma-crypto-pdf</artifactId>
            <groupId>es.gob.afirma</groupId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
        <artifactId>afirma-crypto-pdf-for-pluginsib</artifactId>
        <groupId>es.gob.afirma</groupId>
        <version>1.7.2</version>
    </dependency>

    <dependency>
      <groupId>es.gob.afirma</groupId>
      <artifactId>afirma-server-triphase-signer-document</artifactId>
      <version>${afirma.version}</version>
    </dependency>

    <dependency>
      <groupId>es.gob.afirma</groupId>
      <artifactId>afirma-signature-retriever</artifactId>
      <version>${afirma.version}</version>
      <type>war</type>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>es.gob.afirma</groupId>
      <artifactId>afirma-signature-storage</artifactId>
      <version>${afirma.version}</version>
      <type>war</type>
      <scope>provided</scope>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>unpack</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>unpack</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>es.gob.afirma</groupId>
                  <artifactId>afirma-server-triphase-signer</artifactId>
                  <version>${afirma.version}</version>
                  <type>war</type>
                  <overWrite>true</overWrite>
                  <outputDirectory>${project.build.directory}/classes_war</outputDirectory>
                  <includes>**/*.class</includes> 
                  <excludes>**/*test.class</excludes>
                </artifactItem>
                <artifactItem>
                  <groupId>es.gob.afirma</groupId>
                  <artifactId>afirma-signature-retriever</artifactId>
                  <version>${afirma.version}</version>
                  <type>war</type>
                  <overWrite>true</overWrite>
                  <outputDirectory>${project.build.directory}/classes_war</outputDirectory>
                  <includes>**/*.class</includes> 
                  <excludes>**/*test.class</excludes>
                </artifactItem>
                <artifactItem>
                  <groupId>es.gob.afirma</groupId>
                  <artifactId>afirma-signature-storage</artifactId>
                  <version>${afirma.version}</version>
                  <type>war</type>
                  <overWrite>true</overWrite>
                  <outputDirectory>${project.build.directory}/classes_war</outputDirectory>
                  <includes>**/*.class</includes> 
                  <excludes>**/*test.class</excludes>
                </artifactItem>
              </artifactItems>
              <overWriteReleases>true</overWriteReleases>
              <overWriteSnapshots>true</overWriteSnapshots>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>com.coderplus.maven.plugins</groupId>
        <artifactId>copy-rename-maven-plugin</artifactId>
        <version>1.0</version>
        <executions>
          <execution>
            <id>rename-file</id>
            <phase>process-classes</phase>
            <!-- POST COMPILE compile -->
            <goals>
              <goal>rename</goal>
            </goals>
            <configuration>
              <sourceFile>${project.build.directory}/classes_war/WEB-INF/classes/es</sourceFile>
              <destinationFile>${project.build.directory}/classes/es</destinationFile>
            </configuration>
          </execution>
        </executions>
      </plugin>

    </plugins>

  </build>

</project>
