/*
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.authentication.v1.api;

import org.fundaciobit.vintegris.nebula.api.client.authentication.v1.services.ApiException;
import org.fundaciobit.vintegris.nebula.api.client.authentication.v1.model.AuthViewModel;
import org.fundaciobit.vintegris.nebula.api.client.authentication.v1.model.NebulaResponseResponseCodeTokenWithAuthenticatorsViewModel;
import org.fundaciobit.vintegris.nebula.api.client.authentication.v1.model.NebulaResponseResponseCodeTokenWithChallengeVierModel;
import org.fundaciobit.vintegris.nebula.api.client.authentication.v1.model.NebulaResponseResponseCodeTokenWithLevelViewModel;
import org.fundaciobit.vintegris.nebula.api.client.authentication.v1.model.NebulaResponseStringVoid;
import org.fundaciobit.vintegris.nebula.api.client.authentication.v1.model.SessionAndChallengeViewModel;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticationApi
 */
class AuthenticationApiTest {

    private final AuthenticationApi api = new AuthenticationApi();

    /**
     * First factor authentication
     *
     * First factor authentication
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void authFirstTest() throws ApiException {
        //
        //AuthViewModel authViewModel = null;
        //
        //NebulaResponseResponseCodeTokenWithLevelViewModel response = api.authFirst(authViewModel);

        // TODO: test validations
    }
    /**
     * Second factor authentication
     *
     * Second factor authentication
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void authSecondTest() throws ApiException {
        //
        //String authorization = null;
        //
        //SessionAndChallengeViewModel sessionAndChallengeViewModel = null;
        //
        //NebulaResponseResponseCodeTokenWithLevelViewModel response = api.authSecond(authorization, sessionAndChallengeViewModel);

        // TODO: test validations
    }
    /**
     * Get authenticators
     *
     * Get authenticators
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getAuthenticatorsTest() throws ApiException {
        //
        //String authorization = null;
        //
        //NebulaResponseResponseCodeTokenWithAuthenticatorsViewModel response = api.getAuthenticators(authorization);

        // TODO: test validations
    }
    /**
     * Get challenge
     *
     * Get challenge
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getChallengeTest() throws ApiException {
        //
        //String authenticator = null;
        //
        //String authorization = null;
        //
        //NebulaResponseResponseCodeTokenWithChallengeVierModel response = api.getChallenge(authenticator, authorization);

        // TODO: test validations
    }
}
