/*
 * Certificates API
 * API for managing digital certificates in nebulaSUITE
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ActivateCertificateRequest
 */
@JsonPropertyOrder({
  ActivateCertificateRequest.JSON_PROPERTY_PIN
})
@JsonTypeName("activateCertificate_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ActivateCertificateRequest {
  public static final String JSON_PROPERTY_PIN = "pin";
  @javax.annotation.Nonnull
  private String pin;

  public ActivateCertificateRequest() {
  }

  public ActivateCertificateRequest pin(@javax.annotation.Nonnull String pin) {
    
    this.pin = pin;
    return this;
  }

  /**
   * Certificate&#39;s protection pin
   * @return pin
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPin() {
    return pin;
  }


  @JsonProperty(JSON_PROPERTY_PIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPin(@javax.annotation.Nonnull String pin) {
    this.pin = pin;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivateCertificateRequest activateCertificateRequest = (ActivateCertificateRequest) o;
    return Objects.equals(this.pin, activateCertificateRequest.pin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pin);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivateCertificateRequest {\n");
    sb.append("    pin: ").append(toIndentedString(pin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

