/*
 * Certificates API
 * API for managing digital certificates in nebulaSUITE
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ActivateCertificate200Response
 */
@JsonPropertyOrder({
  ActivateCertificate200Response.JSON_PROPERTY_SERIAL_NUMBER,
  ActivateCertificate200Response.JSON_PROPERTY_ID_CERT
})
@JsonTypeName("activateCertificate_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ActivateCertificate200Response {
  public static final String JSON_PROPERTY_SERIAL_NUMBER = "serialNumber";
  @javax.annotation.Nullable
  private String serialNumber;

  public static final String JSON_PROPERTY_ID_CERT = "idCert";
  @javax.annotation.Nullable
  private String idCert;

  public ActivateCertificate200Response() {
  }

  public ActivateCertificate200Response serialNumber(@javax.annotation.Nullable String serialNumber) {
    
    this.serialNumber = serialNumber;
    return this;
  }

  /**
   * Certificate fingerprint
   * @return serialNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERIAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSerialNumber() {
    return serialNumber;
  }


  @JsonProperty(JSON_PROPERTY_SERIAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSerialNumber(@javax.annotation.Nullable String serialNumber) {
    this.serialNumber = serialNumber;
  }

  public ActivateCertificate200Response idCert(@javax.annotation.Nullable String idCert) {
    
    this.idCert = idCert;
    return this;
  }

  /**
   * Internal identifier of the certificate in nebulaSUITE
   * @return idCert
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID_CERT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdCert() {
    return idCert;
  }


  @JsonProperty(JSON_PROPERTY_ID_CERT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdCert(@javax.annotation.Nullable String idCert) {
    this.idCert = idCert;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivateCertificate200Response activateCertificate200Response = (ActivateCertificate200Response) o;
    return Objects.equals(this.serialNumber, activateCertificate200Response.serialNumber) &&
        Objects.equals(this.idCert, activateCertificate200Response.idCert);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serialNumber, idCert);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivateCertificate200Response {\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    idCert: ").append(toIndentedString(idCert)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

