/*
 * Certificates API
 * API for managing digital certificates in nebulaSUITE
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Certificate
 */
@JsonPropertyOrder({
  Certificate.JSON_PROPERTY_CERTIFICATE_ID,
  Certificate.JSON_PROPERTY_SIGNING_ID,
  Certificate.JSON_PROPERTY_DATE_VALID_START,
  Certificate.JSON_PROPERTY_DATE_VALID_END,
  Certificate.JSON_PROPERTY_ISSUER,
  Certificate.JSON_PROPERTY_ALIAS,
  Certificate.JSON_PROPERTY_SERIAL_NUMBER,
  Certificate.JSON_PROPERTY_SUBJECT,
  Certificate.JSON_PROPERTY_CERTIFICATE,
  Certificate.JSON_PROPERTY_CERT_TYPE,
  Certificate.JSON_PROPERTY_IS_USABLE,
  Certificate.JSON_PROPERTY_STATUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class Certificate {
  public static final String JSON_PROPERTY_CERTIFICATE_ID = "certificateId";
  @javax.annotation.Nullable
  private String certificateId;

  public static final String JSON_PROPERTY_SIGNING_ID = "signingId";
  @javax.annotation.Nullable
  private String signingId;

  public static final String JSON_PROPERTY_DATE_VALID_START = "dateValidStart";
  @javax.annotation.Nullable
  private Integer dateValidStart;

  public static final String JSON_PROPERTY_DATE_VALID_END = "dateValidEnd";
  @javax.annotation.Nullable
  private Integer dateValidEnd;

  public static final String JSON_PROPERTY_ISSUER = "issuer";
  @javax.annotation.Nullable
  private String issuer;

  public static final String JSON_PROPERTY_ALIAS = "alias";
  @javax.annotation.Nullable
  private String alias;

  public static final String JSON_PROPERTY_SERIAL_NUMBER = "serialNumber";
  @javax.annotation.Nullable
  private String serialNumber;

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @javax.annotation.Nullable
  private String subject;

  public static final String JSON_PROPERTY_CERTIFICATE = "certificate";
  @javax.annotation.Nullable
  private String certificate;

  public static final String JSON_PROPERTY_CERT_TYPE = "certType";
  @javax.annotation.Nullable
  private String certType;

  public static final String JSON_PROPERTY_IS_USABLE = "isUsable";
  @javax.annotation.Nullable
  private String isUsable;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public Certificate() {
  }

  public Certificate certificateId(@javax.annotation.Nullable String certificateId) {
    
    this.certificateId = certificateId;
    return this;
  }

  /**
   * Certificate identifier
   * @return certificateId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERTIFICATE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCertificateId() {
    return certificateId;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificateId(@javax.annotation.Nullable String certificateId) {
    this.certificateId = certificateId;
  }

  public Certificate signingId(@javax.annotation.Nullable String signingId) {
    
    this.signingId = signingId;
    return this;
  }

  /**
   * Certificate identifier for signing operations To be used through the API&#39;s Signature operations
   * @return signingId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSigningId() {
    return signingId;
  }


  @JsonProperty(JSON_PROPERTY_SIGNING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSigningId(@javax.annotation.Nullable String signingId) {
    this.signingId = signingId;
  }

  public Certificate dateValidStart(@javax.annotation.Nullable Integer dateValidStart) {
    
    this.dateValidStart = dateValidStart;
    return this;
  }

  /**
   * Start date for the certificate&#39;s valid period
   * @return dateValidStart
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_VALID_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDateValidStart() {
    return dateValidStart;
  }


  @JsonProperty(JSON_PROPERTY_DATE_VALID_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateValidStart(@javax.annotation.Nullable Integer dateValidStart) {
    this.dateValidStart = dateValidStart;
  }

  public Certificate dateValidEnd(@javax.annotation.Nullable Integer dateValidEnd) {
    
    this.dateValidEnd = dateValidEnd;
    return this;
  }

  /**
   * End date for the certificate&#39;s valid period
   * @return dateValidEnd
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_VALID_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDateValidEnd() {
    return dateValidEnd;
  }


  @JsonProperty(JSON_PROPERTY_DATE_VALID_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateValidEnd(@javax.annotation.Nullable Integer dateValidEnd) {
    this.dateValidEnd = dateValidEnd;
  }

  public Certificate issuer(@javax.annotation.Nullable String issuer) {
    
    this.issuer = issuer;
    return this;
  }

  /**
   * Name of the certificate&#39;s issuer
   * @return issuer
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ISSUER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIssuer() {
    return issuer;
  }


  @JsonProperty(JSON_PROPERTY_ISSUER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuer(@javax.annotation.Nullable String issuer) {
    this.issuer = issuer;
  }

  public Certificate alias(@javax.annotation.Nullable String alias) {
    
    this.alias = alias;
    return this;
  }

  /**
   * Name of the certificate&#39;s alias
   * @return alias
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAlias() {
    return alias;
  }


  @JsonProperty(JSON_PROPERTY_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlias(@javax.annotation.Nullable String alias) {
    this.alias = alias;
  }

  public Certificate serialNumber(@javax.annotation.Nullable String serialNumber) {
    
    this.serialNumber = serialNumber;
    return this;
  }

  /**
   * Certificate&#39;s serial number
   * @return serialNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERIAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSerialNumber() {
    return serialNumber;
  }


  @JsonProperty(JSON_PROPERTY_SERIAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSerialNumber(@javax.annotation.Nullable String serialNumber) {
    this.serialNumber = serialNumber;
  }

  public Certificate subject(@javax.annotation.Nullable String subject) {
    
    this.subject = subject;
    return this;
  }

  /**
   * Certificate&#39;s subject
   * @return subject
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubject() {
    return subject;
  }


  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubject(@javax.annotation.Nullable String subject) {
    this.subject = subject;
  }

  public Certificate certificate(@javax.annotation.Nullable String certificate) {
    
    this.certificate = certificate;
    return this;
  }

  /**
   * Certificate&#39;s public key
   * @return certificate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCertificate() {
    return certificate;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificate(@javax.annotation.Nullable String certificate) {
    this.certificate = certificate;
  }

  public Certificate certType(@javax.annotation.Nullable String certType) {
    
    this.certType = certType;
    return this;
  }

  /**
   * Certificate type
   * @return certType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCertType() {
    return certType;
  }


  @JsonProperty(JSON_PROPERTY_CERT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertType(@javax.annotation.Nullable String certType) {
    this.certType = certType;
  }

  public Certificate isUsable(@javax.annotation.Nullable String isUsable) {
    
    this.isUsable = isUsable;
    return this;
  }

  /**
   * True if the certificate is usable
   * @return isUsable
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_USABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIsUsable() {
    return isUsable;
  }


  @JsonProperty(JSON_PROPERTY_IS_USABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsUsable(@javax.annotation.Nullable String isUsable) {
    this.isUsable = isUsable;
  }

  public Certificate status(@javax.annotation.Nullable String status) {
    
    this.status = status;
    return this;
  }

  /**
   * Certificate status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Certificate certificate = (Certificate) o;
    return Objects.equals(this.certificateId, certificate.certificateId) &&
        Objects.equals(this.signingId, certificate.signingId) &&
        Objects.equals(this.dateValidStart, certificate.dateValidStart) &&
        Objects.equals(this.dateValidEnd, certificate.dateValidEnd) &&
        Objects.equals(this.issuer, certificate.issuer) &&
        Objects.equals(this.alias, certificate.alias) &&
        Objects.equals(this.serialNumber, certificate.serialNumber) &&
        Objects.equals(this.subject, certificate.subject) &&
        Objects.equals(this.certificate, certificate.certificate) &&
        Objects.equals(this.certType, certificate.certType) &&
        Objects.equals(this.isUsable, certificate.isUsable) &&
        Objects.equals(this.status, certificate.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certificateId, signingId, dateValidStart, dateValidEnd, issuer, alias, serialNumber, subject, certificate, certType, isUsable, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Certificate {\n");
    sb.append("    certificateId: ").append(toIndentedString(certificateId)).append("\n");
    sb.append("    signingId: ").append(toIndentedString(signingId)).append("\n");
    sb.append("    dateValidStart: ").append(toIndentedString(dateValidStart)).append("\n");
    sb.append("    dateValidEnd: ").append(toIndentedString(dateValidEnd)).append("\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    certificate: ").append(toIndentedString(certificate)).append("\n");
    sb.append("    certType: ").append(toIndentedString(certType)).append("\n");
    sb.append("    isUsable: ").append(toIndentedString(isUsable)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

