/*
 * Certificates API
 * API for managing digital certificates in nebulaSUITE
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ChangeCertificatePinRequest
 */
@JsonPropertyOrder({
  ChangeCertificatePinRequest.JSON_PROPERTY_IDCERT,
  ChangeCertificatePinRequest.JSON_PROPERTY_OLD_PIN,
  ChangeCertificatePinRequest.JSON_PROPERTY_NEW_PIN
})
@JsonTypeName("changeCertificatePin_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ChangeCertificatePinRequest {
  public static final String JSON_PROPERTY_IDCERT = "idcert";
  @javax.annotation.Nonnull
  private String idcert;

  public static final String JSON_PROPERTY_OLD_PIN = "oldPin";
  @javax.annotation.Nonnull
  private String oldPin;

  public static final String JSON_PROPERTY_NEW_PIN = "newPin";
  @javax.annotation.Nonnull
  private String newPin;

  public ChangeCertificatePinRequest() {
  }

  public ChangeCertificatePinRequest idcert(@javax.annotation.Nonnull String idcert) {
    
    this.idcert = idcert;
    return this;
  }

  /**
   * The certificate
   * @return idcert
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IDCERT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIdcert() {
    return idcert;
  }


  @JsonProperty(JSON_PROPERTY_IDCERT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdcert(@javax.annotation.Nonnull String idcert) {
    this.idcert = idcert;
  }

  public ChangeCertificatePinRequest oldPin(@javax.annotation.Nonnull String oldPin) {
    
    this.oldPin = oldPin;
    return this;
  }

  /**
   * Old PIN
   * @return oldPin
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OLD_PIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOldPin() {
    return oldPin;
  }


  @JsonProperty(JSON_PROPERTY_OLD_PIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOldPin(@javax.annotation.Nonnull String oldPin) {
    this.oldPin = oldPin;
  }

  public ChangeCertificatePinRequest newPin(@javax.annotation.Nonnull String newPin) {
    
    this.newPin = newPin;
    return this;
  }

  /**
   * New PIN
   * @return newPin
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NEW_PIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNewPin() {
    return newPin;
  }


  @JsonProperty(JSON_PROPERTY_NEW_PIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNewPin(@javax.annotation.Nonnull String newPin) {
    this.newPin = newPin;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangeCertificatePinRequest changeCertificatePinRequest = (ChangeCertificatePinRequest) o;
    return Objects.equals(this.idcert, changeCertificatePinRequest.idcert) &&
        Objects.equals(this.oldPin, changeCertificatePinRequest.oldPin) &&
        Objects.equals(this.newPin, changeCertificatePinRequest.newPin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idcert, oldPin, newPin);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangeCertificatePinRequest {\n");
    sb.append("    idcert: ").append(toIndentedString(idcert)).append("\n");
    sb.append("    oldPin: ").append(toIndentedString(oldPin)).append("\n");
    sb.append("    newPin: ").append(toIndentedString(newPin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

