/*
 * Certificates API
 * API for managing digital certificates in nebulaSUITE
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CLoginRequestDTO
 */
@JsonPropertyOrder({
  CLoginRequestDTO.JSON_PROPERTY_PIN,
  CLoginRequestDTO.JSON_PROPERTY_SIGNING_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class CLoginRequestDTO {
  public static final String JSON_PROPERTY_PIN = "pin";
  @javax.annotation.Nullable
  private String pin;

  public static final String JSON_PROPERTY_SIGNING_ID = "signingId";
  @javax.annotation.Nullable
  private String signingId;

  public CLoginRequestDTO() {
  }

  public CLoginRequestDTO pin(@javax.annotation.Nullable String pin) {
    
    this.pin = pin;
    return this;
  }

  /**
   * Get pin
   * @return pin
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPin() {
    return pin;
  }


  @JsonProperty(JSON_PROPERTY_PIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPin(@javax.annotation.Nullable String pin) {
    this.pin = pin;
  }

  public CLoginRequestDTO signingId(@javax.annotation.Nullable String signingId) {
    
    this.signingId = signingId;
    return this;
  }

  /**
   * Get signingId
   * @return signingId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSigningId() {
    return signingId;
  }


  @JsonProperty(JSON_PROPERTY_SIGNING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSigningId(@javax.annotation.Nullable String signingId) {
    this.signingId = signingId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CLoginRequestDTO cloginRequestDTO = (CLoginRequestDTO) o;
    return Objects.equals(this.pin, cloginRequestDTO.pin) &&
        Objects.equals(this.signingId, cloginRequestDTO.signingId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pin, signingId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CLoginRequestDTO {\n");
    sb.append("    pin: ").append(toIndentedString(pin)).append("\n");
    sb.append("    signingId: ").append(toIndentedString(signingId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

