/*
 * Certificates API
 * API for managing digital certificates in nebulaSUITE
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CSessionDTOV2
 */
@JsonPropertyOrder({
  CSessionDTOV2.JSON_PROPERTY_MESSAGE,
  CSessionDTOV2.JSON_PROPERTY_RC_SIGN,
  CSessionDTOV2.JSON_PROPERTY_SESSION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class CSessionDTOV2 {
  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nullable
  private String message;

  public static final String JSON_PROPERTY_RC_SIGN = "rcSign";
  @javax.annotation.Nullable
  private String rcSign;

  public static final String JSON_PROPERTY_SESSION = "session";
  @javax.annotation.Nullable
  private String session;

  public CSessionDTOV2() {
  }

  public CSessionDTOV2 message(@javax.annotation.Nullable String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }

  public CSessionDTOV2 rcSign(@javax.annotation.Nullable String rcSign) {
    
    this.rcSign = rcSign;
    return this;
  }

  /**
   * Get rcSign
   * @return rcSign
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RC_SIGN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRcSign() {
    return rcSign;
  }


  @JsonProperty(JSON_PROPERTY_RC_SIGN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRcSign(@javax.annotation.Nullable String rcSign) {
    this.rcSign = rcSign;
  }

  public CSessionDTOV2 session(@javax.annotation.Nullable String session) {
    
    this.session = session;
    return this;
  }

  /**
   * Get session
   * @return session
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SESSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSession() {
    return session;
  }


  @JsonProperty(JSON_PROPERTY_SESSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSession(@javax.annotation.Nullable String session) {
    this.session = session;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CSessionDTOV2 csessionDTOV2 = (CSessionDTOV2) o;
    return Objects.equals(this.message, csessionDTOV2.message) &&
        Objects.equals(this.rcSign, csessionDTOV2.rcSign) &&
        Objects.equals(this.session, csessionDTOV2.session);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, rcSign, session);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CSessionDTOV2 {\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    rcSign: ").append(toIndentedString(rcSign)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

