/*
 * Certificates API
 * API for managing digital certificates in nebulaSUITE
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CSignDTO
 */
@JsonPropertyOrder({
  CSignDTO.JSON_PROPERTY_MESSAGE,
  CSignDTO.JSON_PROPERTY_RC_SIGN,
  CSignDTO.JSON_PROPERTY_SIGNED_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class CSignDTO {
  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nullable
  private String message;

  public static final String JSON_PROPERTY_RC_SIGN = "rcSign";
  @javax.annotation.Nullable
  private String rcSign;

  public static final String JSON_PROPERTY_SIGNED_DATA = "signedData";
  @javax.annotation.Nullable
  private String signedData;

  public CSignDTO() {
  }

  public CSignDTO message(@javax.annotation.Nullable String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }

  public CSignDTO rcSign(@javax.annotation.Nullable String rcSign) {
    
    this.rcSign = rcSign;
    return this;
  }

  /**
   * Get rcSign
   * @return rcSign
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RC_SIGN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRcSign() {
    return rcSign;
  }


  @JsonProperty(JSON_PROPERTY_RC_SIGN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRcSign(@javax.annotation.Nullable String rcSign) {
    this.rcSign = rcSign;
  }

  public CSignDTO signedData(@javax.annotation.Nullable String signedData) {
    
    this.signedData = signedData;
    return this;
  }

  /**
   * Get signedData
   * @return signedData
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNED_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignedData() {
    return signedData;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedData(@javax.annotation.Nullable String signedData) {
    this.signedData = signedData;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CSignDTO csignDTO = (CSignDTO) o;
    return Objects.equals(this.message, csignDTO.message) &&
        Objects.equals(this.rcSign, csignDTO.rcSign) &&
        Objects.equals(this.signedData, csignDTO.signedData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, rcSign, signedData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CSignDTO {\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    rcSign: ").append(toIndentedString(rcSign)).append("\n");
    sb.append("    signedData: ").append(toIndentedString(signedData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

