/*
 * Certificates API
 * API for managing digital certificates in nebulaSUITE
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CSignReqDTOV2
 */
@JsonPropertyOrder({
  CSignReqDTOV2.JSON_PROPERTY_MECHANISM,
  CSignReqDTOV2.JSON_PROPERTY_SESSION,
  CSignReqDTOV2.JSON_PROPERTY_SIGNDATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class CSignReqDTOV2 {
  public static final String JSON_PROPERTY_MECHANISM = "mechanism";
  @javax.annotation.Nullable
  private String mechanism;

  public static final String JSON_PROPERTY_SESSION = "session";
  @javax.annotation.Nullable
  private String session;

  public static final String JSON_PROPERTY_SIGNDATA = "signdata";
  @javax.annotation.Nullable
  private String signdata;

  public CSignReqDTOV2() {
  }

  public CSignReqDTOV2 mechanism(@javax.annotation.Nullable String mechanism) {
    
    this.mechanism = mechanism;
    return this;
  }

  /**
   * Get mechanism
   * @return mechanism
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MECHANISM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMechanism() {
    return mechanism;
  }


  @JsonProperty(JSON_PROPERTY_MECHANISM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMechanism(@javax.annotation.Nullable String mechanism) {
    this.mechanism = mechanism;
  }

  public CSignReqDTOV2 session(@javax.annotation.Nullable String session) {
    
    this.session = session;
    return this;
  }

  /**
   * Get session
   * @return session
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SESSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSession() {
    return session;
  }


  @JsonProperty(JSON_PROPERTY_SESSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSession(@javax.annotation.Nullable String session) {
    this.session = session;
  }

  public CSignReqDTOV2 signdata(@javax.annotation.Nullable String signdata) {
    
    this.signdata = signdata;
    return this;
  }

  /**
   * Get signdata
   * @return signdata
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNDATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSigndata() {
    return signdata;
  }


  @JsonProperty(JSON_PROPERTY_SIGNDATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSigndata(@javax.annotation.Nullable String signdata) {
    this.signdata = signdata;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CSignReqDTOV2 csignReqDTOV2 = (CSignReqDTOV2) o;
    return Objects.equals(this.mechanism, csignReqDTOV2.mechanism) &&
        Objects.equals(this.session, csignReqDTOV2.session) &&
        Objects.equals(this.signdata, csignReqDTOV2.signdata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mechanism, session, signdata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CSignReqDTOV2 {\n");
    sb.append("    mechanism: ").append(toIndentedString(mechanism)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("    signdata: ").append(toIndentedString(signdata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

