/*
 * Nebula Certificates API
 * API for issuing, activating, and managing digital certificates in Nebula Suite.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DeleteCertificateRequest
 */
@JsonPropertyOrder({
  DeleteCertificateRequest.JSON_PROPERTY_SERIAL_NUMBER,
  DeleteCertificateRequest.JSON_PROPERTY_ID_CERT
})
@JsonTypeName("deleteCertificate_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class DeleteCertificateRequest {
  public static final String JSON_PROPERTY_SERIAL_NUMBER = "serialNumber";
  @javax.annotation.Nonnull
  private String serialNumber;

  public static final String JSON_PROPERTY_ID_CERT = "idCert";
  @javax.annotation.Nonnull
  private String idCert;

  public DeleteCertificateRequest() {
  }

  public DeleteCertificateRequest serialNumber(@javax.annotation.Nonnull String serialNumber) {
    
    this.serialNumber = serialNumber;
    return this;
  }

  /**
   * Get serialNumber
   * @return serialNumber
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SERIAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSerialNumber() {
    return serialNumber;
  }


  @JsonProperty(JSON_PROPERTY_SERIAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSerialNumber(@javax.annotation.Nonnull String serialNumber) {
    this.serialNumber = serialNumber;
  }

  public DeleteCertificateRequest idCert(@javax.annotation.Nonnull String idCert) {
    
    this.idCert = idCert;
    return this;
  }

  /**
   * Get idCert
   * @return idCert
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID_CERT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIdCert() {
    return idCert;
  }


  @JsonProperty(JSON_PROPERTY_ID_CERT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdCert(@javax.annotation.Nonnull String idCert) {
    this.idCert = idCert;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteCertificateRequest deleteCertificateRequest = (DeleteCertificateRequest) o;
    return Objects.equals(this.serialNumber, deleteCertificateRequest.serialNumber) &&
        Objects.equals(this.idCert, deleteCertificateRequest.idCert);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serialNumber, idCert);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteCertificateRequest {\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    idCert: ").append(toIndentedString(idCert)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

