/*
 * Nebula Certificates API
 * API for issuing, activating, and managing digital certificates in Nebula Suite.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DelegateCertificateUserRequest
 */
@JsonPropertyOrder({
  DelegateCertificateUserRequest.JSON_PROPERTY_IDUSER,
  DelegateCertificateUserRequest.JSON_PROPERTY_IDCERT,
  DelegateCertificateUserRequest.JSON_PROPERTY_USEPIN,
  DelegateCertificateUserRequest.JSON_PROPERTY_PIN,
  DelegateCertificateUserRequest.JSON_PROPERTY_DATE_VALID_START,
  DelegateCertificateUserRequest.JSON_PROPERTY_DATE_VALID_END
})
@JsonTypeName("delegateCertificateUser_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class DelegateCertificateUserRequest {
  public static final String JSON_PROPERTY_IDUSER = "iduser";
  @javax.annotation.Nonnull
  private String iduser;

  public static final String JSON_PROPERTY_IDCERT = "idcert";
  @javax.annotation.Nonnull
  private String idcert;

  public static final String JSON_PROPERTY_USEPIN = "usepin";
  @javax.annotation.Nullable
  private Boolean usepin;

  public static final String JSON_PROPERTY_PIN = "pin";
  @javax.annotation.Nullable
  private String pin;

  public static final String JSON_PROPERTY_DATE_VALID_START = "dateValidStart";
  @javax.annotation.Nullable
  private String dateValidStart;

  public static final String JSON_PROPERTY_DATE_VALID_END = "dateValidEnd";
  @javax.annotation.Nullable
  private String dateValidEnd;

  public DelegateCertificateUserRequest() {
  }

  public DelegateCertificateUserRequest iduser(@javax.annotation.Nonnull String iduser) {
    
    this.iduser = iduser;
    return this;
  }

  /**
   * Get iduser
   * @return iduser
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IDUSER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIduser() {
    return iduser;
  }


  @JsonProperty(JSON_PROPERTY_IDUSER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIduser(@javax.annotation.Nonnull String iduser) {
    this.iduser = iduser;
  }

  public DelegateCertificateUserRequest idcert(@javax.annotation.Nonnull String idcert) {
    
    this.idcert = idcert;
    return this;
  }

  /**
   * Get idcert
   * @return idcert
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IDCERT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIdcert() {
    return idcert;
  }


  @JsonProperty(JSON_PROPERTY_IDCERT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdcert(@javax.annotation.Nonnull String idcert) {
    this.idcert = idcert;
  }

  public DelegateCertificateUserRequest usepin(@javax.annotation.Nullable Boolean usepin) {
    
    this.usepin = usepin;
    return this;
  }

  /**
   * Get usepin
   * @return usepin
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USEPIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUsepin() {
    return usepin;
  }


  @JsonProperty(JSON_PROPERTY_USEPIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsepin(@javax.annotation.Nullable Boolean usepin) {
    this.usepin = usepin;
  }

  public DelegateCertificateUserRequest pin(@javax.annotation.Nullable String pin) {
    
    this.pin = pin;
    return this;
  }

  /**
   * Get pin
   * @return pin
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPin() {
    return pin;
  }


  @JsonProperty(JSON_PROPERTY_PIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPin(@javax.annotation.Nullable String pin) {
    this.pin = pin;
  }

  public DelegateCertificateUserRequest dateValidStart(@javax.annotation.Nullable String dateValidStart) {
    
    this.dateValidStart = dateValidStart;
    return this;
  }

  /**
   * Get dateValidStart
   * @return dateValidStart
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_VALID_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDateValidStart() {
    return dateValidStart;
  }


  @JsonProperty(JSON_PROPERTY_DATE_VALID_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateValidStart(@javax.annotation.Nullable String dateValidStart) {
    this.dateValidStart = dateValidStart;
  }

  public DelegateCertificateUserRequest dateValidEnd(@javax.annotation.Nullable String dateValidEnd) {
    
    this.dateValidEnd = dateValidEnd;
    return this;
  }

  /**
   * Get dateValidEnd
   * @return dateValidEnd
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_VALID_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDateValidEnd() {
    return dateValidEnd;
  }


  @JsonProperty(JSON_PROPERTY_DATE_VALID_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateValidEnd(@javax.annotation.Nullable String dateValidEnd) {
    this.dateValidEnd = dateValidEnd;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DelegateCertificateUserRequest delegateCertificateUserRequest = (DelegateCertificateUserRequest) o;
    return Objects.equals(this.iduser, delegateCertificateUserRequest.iduser) &&
        Objects.equals(this.idcert, delegateCertificateUserRequest.idcert) &&
        Objects.equals(this.usepin, delegateCertificateUserRequest.usepin) &&
        Objects.equals(this.pin, delegateCertificateUserRequest.pin) &&
        Objects.equals(this.dateValidStart, delegateCertificateUserRequest.dateValidStart) &&
        Objects.equals(this.dateValidEnd, delegateCertificateUserRequest.dateValidEnd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(iduser, idcert, usepin, pin, dateValidStart, dateValidEnd);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DelegateCertificateUserRequest {\n");
    sb.append("    iduser: ").append(toIndentedString(iduser)).append("\n");
    sb.append("    idcert: ").append(toIndentedString(idcert)).append("\n");
    sb.append("    usepin: ").append(toIndentedString(usepin)).append("\n");
    sb.append("    pin: ").append(toIndentedString(pin)).append("\n");
    sb.append("    dateValidStart: ").append(toIndentedString(dateValidStart)).append("\n");
    sb.append("    dateValidEnd: ").append(toIndentedString(dateValidEnd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

