/*
 * Certificates API
 * API for managing digital certificates in nebulaSUITE
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model.FindCertificatesToSign200ResponsePagination;
import org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model.SigningCertificate;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FindCertificatesToSign200Response
 */
@JsonPropertyOrder({
  FindCertificatesToSign200Response.JSON_PROPERTY_PAGINATION,
  FindCertificatesToSign200Response.JSON_PROPERTY_LIST
})
@JsonTypeName("findCertificatesToSign_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class FindCertificatesToSign200Response {
  public static final String JSON_PROPERTY_PAGINATION = "pagination";
  @javax.annotation.Nullable
  private FindCertificatesToSign200ResponsePagination pagination;

  public static final String JSON_PROPERTY_LIST = "list";
  @javax.annotation.Nullable
  private List<SigningCertificate> _list = new ArrayList<>();

  public FindCertificatesToSign200Response() {
  }

  public FindCertificatesToSign200Response pagination(@javax.annotation.Nullable FindCertificatesToSign200ResponsePagination pagination) {
    
    this.pagination = pagination;
    return this;
  }

  /**
   * Get pagination
   * @return pagination
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAGINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FindCertificatesToSign200ResponsePagination getPagination() {
    return pagination;
  }


  @JsonProperty(JSON_PROPERTY_PAGINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPagination(@javax.annotation.Nullable FindCertificatesToSign200ResponsePagination pagination) {
    this.pagination = pagination;
  }

  public FindCertificatesToSign200Response _list(@javax.annotation.Nullable List<SigningCertificate> _list) {
    
    this._list = _list;
    return this;
  }

  public FindCertificatesToSign200Response addListItem(SigningCertificate _listItem) {
    if (this._list == null) {
      this._list = new ArrayList<>();
    }
    this._list.add(_listItem);
    return this;
  }

  /**
   * Get _list
   * @return _list
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SigningCertificate> getList() {
    return _list;
  }


  @JsonProperty(JSON_PROPERTY_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setList(@javax.annotation.Nullable List<SigningCertificate> _list) {
    this._list = _list;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FindCertificatesToSign200Response findCertificatesToSign200Response = (FindCertificatesToSign200Response) o;
    return Objects.equals(this.pagination, findCertificatesToSign200Response.pagination) &&
        Objects.equals(this._list, findCertificatesToSign200Response._list);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pagination, _list);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FindCertificatesToSign200Response {\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("    _list: ").append(toIndentedString(_list)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

