/*
 * Certificates API
 * API for managing digital certificates in nebulaSUITE
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FindCertificatesToSign200ResponsePagination
 */
@JsonPropertyOrder({
  FindCertificatesToSign200ResponsePagination.JSON_PROPERTY_TOTAL_ELEMENTS,
  FindCertificatesToSign200ResponsePagination.JSON_PROPERTY_TOTAL_PAGES,
  FindCertificatesToSign200ResponsePagination.JSON_PROPERTY_PAGE_SIZE,
  FindCertificatesToSign200ResponsePagination.JSON_PROPERTY_CURRENT_PAGE
})
@JsonTypeName("findCertificatesToSign_200_response_pagination")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class FindCertificatesToSign200ResponsePagination {
  public static final String JSON_PROPERTY_TOTAL_ELEMENTS = "totalElements";
  @javax.annotation.Nullable
  private Integer totalElements;

  public static final String JSON_PROPERTY_TOTAL_PAGES = "totalPages";
  @javax.annotation.Nullable
  private Integer totalPages;

  public static final String JSON_PROPERTY_PAGE_SIZE = "pageSize";
  @javax.annotation.Nullable
  private Integer pageSize;

  public static final String JSON_PROPERTY_CURRENT_PAGE = "currentPage";
  @javax.annotation.Nullable
  private Integer currentPage;

  public FindCertificatesToSign200ResponsePagination() {
  }

  public FindCertificatesToSign200ResponsePagination totalElements(@javax.annotation.Nullable Integer totalElements) {
    
    this.totalElements = totalElements;
    return this;
  }

  /**
   * Total elements
   * @return totalElements
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_ELEMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalElements() {
    return totalElements;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_ELEMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalElements(@javax.annotation.Nullable Integer totalElements) {
    this.totalElements = totalElements;
  }

  public FindCertificatesToSign200ResponsePagination totalPages(@javax.annotation.Nullable Integer totalPages) {
    
    this.totalPages = totalPages;
    return this;
  }

  /**
   * Total amount of pages
   * @return totalPages
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_PAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalPages() {
    return totalPages;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_PAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalPages(@javax.annotation.Nullable Integer totalPages) {
    this.totalPages = totalPages;
  }

  public FindCertificatesToSign200ResponsePagination pageSize(@javax.annotation.Nullable Integer pageSize) {
    
    this.pageSize = pageSize;
    return this;
  }

  /**
   * Size of the page
   * @return pageSize
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAGE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPageSize() {
    return pageSize;
  }


  @JsonProperty(JSON_PROPERTY_PAGE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageSize(@javax.annotation.Nullable Integer pageSize) {
    this.pageSize = pageSize;
  }

  public FindCertificatesToSign200ResponsePagination currentPage(@javax.annotation.Nullable Integer currentPage) {
    
    this.currentPage = currentPage;
    return this;
  }

  /**
   * Current page
   * @return currentPage
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENT_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCurrentPage() {
    return currentPage;
  }


  @JsonProperty(JSON_PROPERTY_CURRENT_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrentPage(@javax.annotation.Nullable Integer currentPage) {
    this.currentPage = currentPage;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FindCertificatesToSign200ResponsePagination findCertificatesToSign200ResponsePagination = (FindCertificatesToSign200ResponsePagination) o;
    return Objects.equals(this.totalElements, findCertificatesToSign200ResponsePagination.totalElements) &&
        Objects.equals(this.totalPages, findCertificatesToSign200ResponsePagination.totalPages) &&
        Objects.equals(this.pageSize, findCertificatesToSign200ResponsePagination.pageSize) &&
        Objects.equals(this.currentPage, findCertificatesToSign200ResponsePagination.currentPage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalElements, totalPages, pageSize, currentPage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FindCertificatesToSign200ResponsePagination {\n");
    sb.append("    totalElements: ").append(toIndentedString(totalElements)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    currentPage: ").append(toIndentedString(currentPage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

