/*
 * Certificates API
 * API for managing digital certificates in nebulaSUITE
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model.Policy;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetCertPolicies200Response
 */
@JsonPropertyOrder({
  GetCertPolicies200Response.JSON_PROPERTY_TOTAL_POLICIES,
  GetCertPolicies200Response.JSON_PROPERTY_POLICY_LIST
})
@JsonTypeName("getCertPolicies_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class GetCertPolicies200Response {
  public static final String JSON_PROPERTY_TOTAL_POLICIES = "totalPolicies";
  @javax.annotation.Nullable
  private Integer totalPolicies;

  public static final String JSON_PROPERTY_POLICY_LIST = "policyList";
  @javax.annotation.Nullable
  private List<Policy> policyList = new ArrayList<>();

  public GetCertPolicies200Response() {
  }

  public GetCertPolicies200Response totalPolicies(@javax.annotation.Nullable Integer totalPolicies) {
    
    this.totalPolicies = totalPolicies;
    return this;
  }

  /**
   * Total results for the search before applying offset and limit
   * @return totalPolicies
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_POLICIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalPolicies() {
    return totalPolicies;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_POLICIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalPolicies(@javax.annotation.Nullable Integer totalPolicies) {
    this.totalPolicies = totalPolicies;
  }

  public GetCertPolicies200Response policyList(@javax.annotation.Nullable List<Policy> policyList) {
    
    this.policyList = policyList;
    return this;
  }

  public GetCertPolicies200Response addPolicyListItem(Policy policyListItem) {
    if (this.policyList == null) {
      this.policyList = new ArrayList<>();
    }
    this.policyList.add(policyListItem);
    return this;
  }

  /**
   * Get policyList
   * @return policyList
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POLICY_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Policy> getPolicyList() {
    return policyList;
  }


  @JsonProperty(JSON_PROPERTY_POLICY_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPolicyList(@javax.annotation.Nullable List<Policy> policyList) {
    this.policyList = policyList;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCertPolicies200Response getCertPolicies200Response = (GetCertPolicies200Response) o;
    return Objects.equals(this.totalPolicies, getCertPolicies200Response.totalPolicies) &&
        Objects.equals(this.policyList, getCertPolicies200Response.policyList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalPolicies, policyList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCertPolicies200Response {\n");
    sb.append("    totalPolicies: ").append(toIndentedString(totalPolicies)).append("\n");
    sb.append("    policyList: ").append(toIndentedString(policyList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

