/*
 * Certificates API
 * API for managing digital certificates in nebulaSUITE
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetMyCertificates200ResponseCertificatesListInner
 */
@JsonPropertyOrder({
  GetMyCertificates200ResponseCertificatesListInner.JSON_PROPERTY_CERTIFICATE_ID,
  GetMyCertificates200ResponseCertificatesListInner.JSON_PROPERTY_SIGNING_ID,
  GetMyCertificates200ResponseCertificatesListInner.JSON_PROPERTY_ALIAS,
  GetMyCertificates200ResponseCertificatesListInner.JSON_PROPERTY_SUBJECT,
  GetMyCertificates200ResponseCertificatesListInner.JSON_PROPERTY_ISSUER,
  GetMyCertificates200ResponseCertificatesListInner.JSON_PROPERTY_SERIAL_NUMBER,
  GetMyCertificates200ResponseCertificatesListInner.JSON_PROPERTY_DATE_VALID_START,
  GetMyCertificates200ResponseCertificatesListInner.JSON_PROPERTY_DATE_VALID_END,
  GetMyCertificates200ResponseCertificatesListInner.JSON_PROPERTY_STATUS,
  GetMyCertificates200ResponseCertificatesListInner.JSON_PROPERTY_CERTIFICATE,
  GetMyCertificates200ResponseCertificatesListInner.JSON_PROPERTY_CERT_TYPE,
  GetMyCertificates200ResponseCertificatesListInner.JSON_PROPERTY_IS_USABLE
})
@JsonTypeName("getMyCertificates_200_response_certificatesList_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class GetMyCertificates200ResponseCertificatesListInner {
  public static final String JSON_PROPERTY_CERTIFICATE_ID = "certificateId";
  @javax.annotation.Nonnull
  private String certificateId;

  public static final String JSON_PROPERTY_SIGNING_ID = "signingId";
  @javax.annotation.Nullable
  private String signingId;

  public static final String JSON_PROPERTY_ALIAS = "alias";
  @javax.annotation.Nullable
  private String alias;

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @javax.annotation.Nonnull
  private String subject;

  public static final String JSON_PROPERTY_ISSUER = "issuer";
  @javax.annotation.Nonnull
  private String issuer;

  public static final String JSON_PROPERTY_SERIAL_NUMBER = "serialNumber";
  @javax.annotation.Nonnull
  private String serialNumber;

  public static final String JSON_PROPERTY_DATE_VALID_START = "dateValidStart";
  @javax.annotation.Nullable
  private OffsetDateTime dateValidStart;

  public static final String JSON_PROPERTY_DATE_VALID_END = "dateValidEnd";
  @javax.annotation.Nullable
  private OffsetDateTime dateValidEnd;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_CERTIFICATE = "certificate";
  @javax.annotation.Nullable
  private String certificate;

  public static final String JSON_PROPERTY_CERT_TYPE = "certType";
  @javax.annotation.Nullable
  private String certType;

  public static final String JSON_PROPERTY_IS_USABLE = "isUsable";
  @javax.annotation.Nullable
  private String isUsable;

  public GetMyCertificates200ResponseCertificatesListInner() {
  }

  public GetMyCertificates200ResponseCertificatesListInner certificateId(@javax.annotation.Nonnull String certificateId) {
    
    this.certificateId = certificateId;
    return this;
  }

  /**
   * Unique certificate identifier.
   * @return certificateId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CERTIFICATE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCertificateId() {
    return certificateId;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCertificateId(@javax.annotation.Nonnull String certificateId) {
    this.certificateId = certificateId;
  }

  public GetMyCertificates200ResponseCertificatesListInner signingId(@javax.annotation.Nullable String signingId) {
    
    this.signingId = signingId;
    return this;
  }

  /**
   * Signing identifier.
   * @return signingId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSigningId() {
    return signingId;
  }


  @JsonProperty(JSON_PROPERTY_SIGNING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSigningId(@javax.annotation.Nullable String signingId) {
    this.signingId = signingId;
  }

  public GetMyCertificates200ResponseCertificatesListInner alias(@javax.annotation.Nullable String alias) {
    
    this.alias = alias;
    return this;
  }

  /**
   * Certificate alias or friendly name.
   * @return alias
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAlias() {
    return alias;
  }


  @JsonProperty(JSON_PROPERTY_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlias(@javax.annotation.Nullable String alias) {
    this.alias = alias;
  }

  public GetMyCertificates200ResponseCertificatesListInner subject(@javax.annotation.Nonnull String subject) {
    
    this.subject = subject;
    return this;
  }

  /**
   * Subject name (CN, OU, O...).
   * @return subject
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSubject() {
    return subject;
  }


  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
  }

  public GetMyCertificates200ResponseCertificatesListInner issuer(@javax.annotation.Nonnull String issuer) {
    
    this.issuer = issuer;
    return this;
  }

  /**
   * Issuer of the certificate.
   * @return issuer
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ISSUER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIssuer() {
    return issuer;
  }


  @JsonProperty(JSON_PROPERTY_ISSUER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIssuer(@javax.annotation.Nonnull String issuer) {
    this.issuer = issuer;
  }

  public GetMyCertificates200ResponseCertificatesListInner serialNumber(@javax.annotation.Nonnull String serialNumber) {
    
    this.serialNumber = serialNumber;
    return this;
  }

  /**
   * Certificate serial number.
   * @return serialNumber
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SERIAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSerialNumber() {
    return serialNumber;
  }


  @JsonProperty(JSON_PROPERTY_SERIAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSerialNumber(@javax.annotation.Nonnull String serialNumber) {
    this.serialNumber = serialNumber;
  }

  public GetMyCertificates200ResponseCertificatesListInner dateValidStart(@javax.annotation.Nullable OffsetDateTime dateValidStart) {
    
    this.dateValidStart = dateValidStart;
    return this;
  }

  /**
   * Start date of certificate validity.
   * @return dateValidStart
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_VALID_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDateValidStart() {
    return dateValidStart;
  }


  @JsonProperty(JSON_PROPERTY_DATE_VALID_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateValidStart(@javax.annotation.Nullable OffsetDateTime dateValidStart) {
    this.dateValidStart = dateValidStart;
  }

  public GetMyCertificates200ResponseCertificatesListInner dateValidEnd(@javax.annotation.Nullable OffsetDateTime dateValidEnd) {
    
    this.dateValidEnd = dateValidEnd;
    return this;
  }

  /**
   * Expiration date of the certificate.
   * @return dateValidEnd
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_VALID_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDateValidEnd() {
    return dateValidEnd;
  }


  @JsonProperty(JSON_PROPERTY_DATE_VALID_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateValidEnd(@javax.annotation.Nullable OffsetDateTime dateValidEnd) {
    this.dateValidEnd = dateValidEnd;
  }

  public GetMyCertificates200ResponseCertificatesListInner status(@javax.annotation.Nullable String status) {
    
    this.status = status;
    return this;
  }

  /**
   * Current status (ISSUED, etc.).
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }

  public GetMyCertificates200ResponseCertificatesListInner certificate(@javax.annotation.Nullable String certificate) {
    
    this.certificate = certificate;
    return this;
  }

  /**
   * Base64 encoded X.509 certificate.
   * @return certificate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCertificate() {
    return certificate;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificate(@javax.annotation.Nullable String certificate) {
    this.certificate = certificate;
  }

  public GetMyCertificates200ResponseCertificatesListInner certType(@javax.annotation.Nullable String certType) {
    
    this.certType = certType;
    return this;
  }

  /**
   * Type of certificate (IMPORTED, INTERMEDIATE, QUALIFIED).
   * @return certType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCertType() {
    return certType;
  }


  @JsonProperty(JSON_PROPERTY_CERT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertType(@javax.annotation.Nullable String certType) {
    this.certType = certType;
  }

  public GetMyCertificates200ResponseCertificatesListInner isUsable(@javax.annotation.Nullable String isUsable) {
    
    this.isUsable = isUsable;
    return this;
  }

  /**
   * Indicates if the certificate is usable (1 for yes, 0 for no).
   * @return isUsable
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_USABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIsUsable() {
    return isUsable;
  }


  @JsonProperty(JSON_PROPERTY_IS_USABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsUsable(@javax.annotation.Nullable String isUsable) {
    this.isUsable = isUsable;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMyCertificates200ResponseCertificatesListInner getMyCertificates200ResponseCertificatesListInner = (GetMyCertificates200ResponseCertificatesListInner) o;
    return Objects.equals(this.certificateId, getMyCertificates200ResponseCertificatesListInner.certificateId) &&
        Objects.equals(this.signingId, getMyCertificates200ResponseCertificatesListInner.signingId) &&
        Objects.equals(this.alias, getMyCertificates200ResponseCertificatesListInner.alias) &&
        Objects.equals(this.subject, getMyCertificates200ResponseCertificatesListInner.subject) &&
        Objects.equals(this.issuer, getMyCertificates200ResponseCertificatesListInner.issuer) &&
        Objects.equals(this.serialNumber, getMyCertificates200ResponseCertificatesListInner.serialNumber) &&
        Objects.equals(this.dateValidStart, getMyCertificates200ResponseCertificatesListInner.dateValidStart) &&
        Objects.equals(this.dateValidEnd, getMyCertificates200ResponseCertificatesListInner.dateValidEnd) &&
        Objects.equals(this.status, getMyCertificates200ResponseCertificatesListInner.status) &&
        Objects.equals(this.certificate, getMyCertificates200ResponseCertificatesListInner.certificate) &&
        Objects.equals(this.certType, getMyCertificates200ResponseCertificatesListInner.certType) &&
        Objects.equals(this.isUsable, getMyCertificates200ResponseCertificatesListInner.isUsable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certificateId, signingId, alias, subject, issuer, serialNumber, dateValidStart, dateValidEnd, status, certificate, certType, isUsable);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMyCertificates200ResponseCertificatesListInner {\n");
    sb.append("    certificateId: ").append(toIndentedString(certificateId)).append("\n");
    sb.append("    signingId: ").append(toIndentedString(signingId)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    dateValidStart: ").append(toIndentedString(dateValidStart)).append("\n");
    sb.append("    dateValidEnd: ").append(toIndentedString(dateValidEnd)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    certificate: ").append(toIndentedString(certificate)).append("\n");
    sb.append("    certType: ").append(toIndentedString(certType)).append("\n");
    sb.append("    isUsable: ").append(toIndentedString(isUsable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

