/*
 * Certificates API
 * API for managing digital certificates in nebulaSUITE
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model.GetMyCertificates200ResponseCertificatesListInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetMyCertificates200Response
 */
@JsonPropertyOrder({
  GetMyCertificates200Response.JSON_PROPERTY_TOTAL_CERTIFICATES,
  GetMyCertificates200Response.JSON_PROPERTY_CERTIFICATES_LIST
})
@JsonTypeName("getMyCertificates_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class GetMyCertificates200Response {
  public static final String JSON_PROPERTY_TOTAL_CERTIFICATES = "totalCertificates";
  @javax.annotation.Nullable
  private Integer totalCertificates;

  public static final String JSON_PROPERTY_CERTIFICATES_LIST = "certificatesList";
  @javax.annotation.Nullable
  private List<GetMyCertificates200ResponseCertificatesListInner> certificatesList = new ArrayList<>();

  public GetMyCertificates200Response() {
  }

  public GetMyCertificates200Response totalCertificates(@javax.annotation.Nullable Integer totalCertificates) {
    
    this.totalCertificates = totalCertificates;
    return this;
  }

  /**
   * Total number of certificates found.
   * @return totalCertificates
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_CERTIFICATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalCertificates() {
    return totalCertificates;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_CERTIFICATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalCertificates(@javax.annotation.Nullable Integer totalCertificates) {
    this.totalCertificates = totalCertificates;
  }

  public GetMyCertificates200Response certificatesList(@javax.annotation.Nullable List<GetMyCertificates200ResponseCertificatesListInner> certificatesList) {
    
    this.certificatesList = certificatesList;
    return this;
  }

  public GetMyCertificates200Response addCertificatesListItem(GetMyCertificates200ResponseCertificatesListInner certificatesListItem) {
    if (this.certificatesList == null) {
      this.certificatesList = new ArrayList<>();
    }
    this.certificatesList.add(certificatesListItem);
    return this;
  }

  /**
   * Get certificatesList
   * @return certificatesList
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERTIFICATES_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<GetMyCertificates200ResponseCertificatesListInner> getCertificatesList() {
    return certificatesList;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATES_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificatesList(@javax.annotation.Nullable List<GetMyCertificates200ResponseCertificatesListInner> certificatesList) {
    this.certificatesList = certificatesList;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMyCertificates200Response getMyCertificates200Response = (GetMyCertificates200Response) o;
    return Objects.equals(this.totalCertificates, getMyCertificates200Response.totalCertificates) &&
        Objects.equals(this.certificatesList, getMyCertificates200Response.certificatesList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalCertificates, certificatesList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMyCertificates200Response {\n");
    sb.append("    totalCertificates: ").append(toIndentedString(totalCertificates)).append("\n");
    sb.append("    certificatesList: ").append(toIndentedString(certificatesList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

