/*
 * Nebula Certificates API
 * API for issuing, activating, and managing digital certificates in Nebula Suite.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ImportCertificateRequest
 */
@JsonPropertyOrder({
  ImportCertificateRequest.JSON_PROPERTY_PFX_IN_BASE64,
  ImportCertificateRequest.JSON_PROPERTY_PASSWORD,
  ImportCertificateRequest.JSON_PROPERTY_ALIAS
})
@JsonTypeName("importCertificate_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ImportCertificateRequest {
  public static final String JSON_PROPERTY_PFX_IN_BASE64 = "pfxInBase64";
  @javax.annotation.Nonnull
  private String pfxInBase64;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  @javax.annotation.Nullable
  private String password;

  public static final String JSON_PROPERTY_ALIAS = "alias";
  @javax.annotation.Nullable
  private String alias;

  public ImportCertificateRequest() {
  }

  public ImportCertificateRequest pfxInBase64(@javax.annotation.Nonnull String pfxInBase64) {
    
    this.pfxInBase64 = pfxInBase64;
    return this;
  }

  /**
   * Get pfxInBase64
   * @return pfxInBase64
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PFX_IN_BASE64)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPfxInBase64() {
    return pfxInBase64;
  }


  @JsonProperty(JSON_PROPERTY_PFX_IN_BASE64)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPfxInBase64(@javax.annotation.Nonnull String pfxInBase64) {
    this.pfxInBase64 = pfxInBase64;
  }

  public ImportCertificateRequest password(@javax.annotation.Nullable String password) {
    
    this.password = password;
    return this;
  }

  /**
   * Get password
   * @return password
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassword(@javax.annotation.Nullable String password) {
    this.password = password;
  }

  public ImportCertificateRequest alias(@javax.annotation.Nullable String alias) {
    
    this.alias = alias;
    return this;
  }

  /**
   * Get alias
   * @return alias
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAlias() {
    return alias;
  }


  @JsonProperty(JSON_PROPERTY_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlias(@javax.annotation.Nullable String alias) {
    this.alias = alias;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImportCertificateRequest importCertificateRequest = (ImportCertificateRequest) o;
    return Objects.equals(this.pfxInBase64, importCertificateRequest.pfxInBase64) &&
        Objects.equals(this.password, importCertificateRequest.password) &&
        Objects.equals(this.alias, importCertificateRequest.alias);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pfxInBase64, password, alias);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImportCertificateRequest {\n");
    sb.append("    pfxInBase64: ").append(toIndentedString(pfxInBase64)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

