/*
 * Certificates API
 * API for managing digital certificates in nebulaSUITE
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ImportCertificateDTO
 */
@JsonPropertyOrder({
  ImportCertificateDTO.JSON_PROPERTY_PFX_IN_BASE64,
  ImportCertificateDTO.JSON_PROPERTY_PFX_PASSWORD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ImportCertificateDTO {
  public static final String JSON_PROPERTY_PFX_IN_BASE64 = "pfxInBase64";
  @javax.annotation.Nullable
  private String pfxInBase64;

  public static final String JSON_PROPERTY_PFX_PASSWORD = "pfxPassword";
  @javax.annotation.Nullable
  private String pfxPassword;

  public ImportCertificateDTO() {
  }

  public ImportCertificateDTO pfxInBase64(@javax.annotation.Nullable String pfxInBase64) {
    
    this.pfxInBase64 = pfxInBase64;
    return this;
  }

  /**
   * Get pfxInBase64
   * @return pfxInBase64
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PFX_IN_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPfxInBase64() {
    return pfxInBase64;
  }


  @JsonProperty(JSON_PROPERTY_PFX_IN_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPfxInBase64(@javax.annotation.Nullable String pfxInBase64) {
    this.pfxInBase64 = pfxInBase64;
  }

  public ImportCertificateDTO pfxPassword(@javax.annotation.Nullable String pfxPassword) {
    
    this.pfxPassword = pfxPassword;
    return this;
  }

  /**
   * Get pfxPassword
   * @return pfxPassword
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PFX_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPfxPassword() {
    return pfxPassword;
  }


  @JsonProperty(JSON_PROPERTY_PFX_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPfxPassword(@javax.annotation.Nullable String pfxPassword) {
    this.pfxPassword = pfxPassword;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImportCertificateDTO importCertificateDTO = (ImportCertificateDTO) o;
    return Objects.equals(this.pfxInBase64, importCertificateDTO.pfxInBase64) &&
        Objects.equals(this.pfxPassword, importCertificateDTO.pfxPassword);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pfxInBase64, pfxPassword);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImportCertificateDTO {\n");
    sb.append("    pfxInBase64: ").append(toIndentedString(pfxInBase64)).append("\n");
    sb.append("    pfxPassword: ").append(toIndentedString(pfxPassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

