/*
 * Nebula Certificates API
 * API for issuing, activating, and managing digital certificates in Nebula Suite.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RequestCertificateReportRequest
 */
@JsonPropertyOrder({
  RequestCertificateReportRequest.JSON_PROPERTY_EMAILS_LIST
})
@JsonTypeName("requestCertificateReport_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RequestCertificateReportRequest {
  public static final String JSON_PROPERTY_EMAILS_LIST = "emailsList";
  @javax.annotation.Nonnull
  private List<String> emailsList = new ArrayList<>();

  public RequestCertificateReportRequest() {
  }

  public RequestCertificateReportRequest emailsList(@javax.annotation.Nonnull List<String> emailsList) {
    
    this.emailsList = emailsList;
    return this;
  }

  public RequestCertificateReportRequest addEmailsListItem(String emailsListItem) {
    if (this.emailsList == null) {
      this.emailsList = new ArrayList<>();
    }
    this.emailsList.add(emailsListItem);
    return this;
  }

  /**
   * Get emailsList
   * @return emailsList
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EMAILS_LIST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getEmailsList() {
    return emailsList;
  }


  @JsonProperty(JSON_PROPERTY_EMAILS_LIST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmailsList(@javax.annotation.Nonnull List<String> emailsList) {
    this.emailsList = emailsList;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestCertificateReportRequest requestCertificateReportRequest = (RequestCertificateReportRequest) o;
    return Objects.equals(this.emailsList, requestCertificateReportRequest.emailsList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emailsList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestCertificateReportRequest {\n");
    sb.append("    emailsList: ").append(toIndentedString(emailsList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

