/*
 * Nebula Certificates API
 * API for issuing, activating, and managing digital certificates in Nebula Suite.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RequestKeystoreCertificateRequest
 */
@JsonPropertyOrder({
  RequestKeystoreCertificateRequest.JSON_PROPERTY_CSR,
  RequestKeystoreCertificateRequest.JSON_PROPERTY_POLICY_ID
})
@JsonTypeName("requestKeystoreCertificate_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RequestKeystoreCertificateRequest {
  public static final String JSON_PROPERTY_CSR = "csr";
  @javax.annotation.Nonnull
  private String csr;

  public static final String JSON_PROPERTY_POLICY_ID = "policyId";
  @javax.annotation.Nonnull
  private String policyId;

  public RequestKeystoreCertificateRequest() {
  }

  public RequestKeystoreCertificateRequest csr(@javax.annotation.Nonnull String csr) {
    
    this.csr = csr;
    return this;
  }

  /**
   * Certificate Signing Request in PEM format.
   * @return csr
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CSR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCsr() {
    return csr;
  }


  @JsonProperty(JSON_PROPERTY_CSR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCsr(@javax.annotation.Nonnull String csr) {
    this.csr = csr;
  }

  public RequestKeystoreCertificateRequest policyId(@javax.annotation.Nonnull String policyId) {
    
    this.policyId = policyId;
    return this;
  }

  /**
   * Identifier of the certificate policy.
   * @return policyId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_POLICY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPolicyId() {
    return policyId;
  }


  @JsonProperty(JSON_PROPERTY_POLICY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPolicyId(@javax.annotation.Nonnull String policyId) {
    this.policyId = policyId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestKeystoreCertificateRequest requestKeystoreCertificateRequest = (RequestKeystoreCertificateRequest) o;
    return Objects.equals(this.csr, requestKeystoreCertificateRequest.csr) &&
        Objects.equals(this.policyId, requestKeystoreCertificateRequest.policyId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(csr, policyId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestKeystoreCertificateRequest {\n");
    sb.append("    csr: ").append(toIndentedString(csr)).append("\n");
    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

