/*
 * Trusted Applications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AuthorizeResponseViewModel
 */
@JsonPropertyOrder({
  AuthorizeResponseViewModel.JSON_PROPERTY_AUTHORIZATION,
  AuthorizeResponseViewModel.JSON_PROPERTY_EXPIRATION,
  AuthorizeResponseViewModel.JSON_PROPERTY_GRANTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class AuthorizeResponseViewModel {
  public static final String JSON_PROPERTY_AUTHORIZATION = "authorization";
  @javax.annotation.Nonnull
  private String authorization;

  public static final String JSON_PROPERTY_EXPIRATION = "expiration";
  @javax.annotation.Nonnull
  private Long expiration;

  /**
   * Permissions held with the generated token
   */
  public enum GrantsEnum {
    AUTH_FIRST(String.valueOf("DISABLE_AUTH_FIRST")),
    
    AUTH_SECOND(String.valueOf("DISABLE_AUTH_SECOND")),
    
    PIN_POLICY(String.valueOf("DISABLE_PIN_POLICY"));

    private String value;

    GrantsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static GrantsEnum fromValue(String value) {
      for (GrantsEnum b : GrantsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_GRANTS = "grants";
  @javax.annotation.Nonnull
  private List<GrantsEnum> grants = new ArrayList<>();

  public AuthorizeResponseViewModel() {
  }

  public AuthorizeResponseViewModel authorization(@javax.annotation.Nonnull String authorization) {
    
    this.authorization = authorization;
    return this;
  }

  /**
   * Token generated for future operations in nebulaSUITE
   * @return authorization
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AUTHORIZATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAuthorization() {
    return authorization;
  }


  @JsonProperty(JSON_PROPERTY_AUTHORIZATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthorization(@javax.annotation.Nonnull String authorization) {
    this.authorization = authorization;
  }

  public AuthorizeResponseViewModel expiration(@javax.annotation.Nonnull Long expiration) {
    
    this.expiration = expiration;
    return this;
  }

  /**
   * Token expiration time in minutes
   * @return expiration
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXPIRATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getExpiration() {
    return expiration;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpiration(@javax.annotation.Nonnull Long expiration) {
    this.expiration = expiration;
  }

  public AuthorizeResponseViewModel grants(@javax.annotation.Nonnull List<GrantsEnum> grants) {
    
    this.grants = grants;
    return this;
  }

  public AuthorizeResponseViewModel addGrantsItem(GrantsEnum grantsItem) {
    if (this.grants == null) {
      this.grants = new ArrayList<>();
    }
    this.grants.add(grantsItem);
    return this;
  }

  /**
   * Permissions held with the generated token
   * @return grants
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GRANTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<GrantsEnum> getGrants() {
    return grants;
  }


  @JsonProperty(JSON_PROPERTY_GRANTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGrants(@javax.annotation.Nonnull List<GrantsEnum> grants) {
    this.grants = grants;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizeResponseViewModel authorizeResponseViewModel = (AuthorizeResponseViewModel) o;
    return Objects.equals(this.authorization, authorizeResponseViewModel.authorization) &&
        Objects.equals(this.expiration, authorizeResponseViewModel.expiration) &&
        Objects.equals(this.grants, authorizeResponseViewModel.grants);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authorization, expiration, grants);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizeResponseViewModel {\n");
    sb.append("    authorization: ").append(toIndentedString(authorization)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    grants: ").append(toIndentedString(grants)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

