/*
 * Trusted Applications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DetailedTrustedAppViewModel
 */
@JsonPropertyOrder({
  DetailedTrustedAppViewModel.JSON_PROPERTY_APP_ID,
  DetailedTrustedAppViewModel.JSON_PROPERTY_TENANT_ID,
  DetailedTrustedAppViewModel.JSON_PROPERTY_NAME,
  DetailedTrustedAppViewModel.JSON_PROPERTY_STATUS,
  DetailedTrustedAppViewModel.JSON_PROPERTY_PERMISSIONS,
  DetailedTrustedAppViewModel.JSON_PROPERTY_DESCRIPTION,
  DetailedTrustedAppViewModel.JSON_PROPERTY_GROUPS,
  DetailedTrustedAppViewModel.JSON_PROPERTY_JWT_SIGNATURE_ALGORITHM,
  DetailedTrustedAppViewModel.JSON_PROPERTY_EXPIRATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class DetailedTrustedAppViewModel {
  public static final String JSON_PROPERTY_APP_ID = "appId";
  @javax.annotation.Nonnull
  private String appId;

  public static final String JSON_PROPERTY_TENANT_ID = "tenantId";
  @javax.annotation.Nonnull
  private String tenantId;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  /**
   * Current status of the trusted app
   */
  public enum StatusEnum {
    ENABLED(String.valueOf("ENABLED")),
    
    DISABLED(String.valueOf("DISABLED"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_PERMISSIONS = "permissions";
  @javax.annotation.Nonnull
  private List<String> permissions = new ArrayList<>();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nonnull
  private String description;

  public static final String JSON_PROPERTY_GROUPS = "groups";
  @javax.annotation.Nonnull
  private List<String> groups = new ArrayList<>();

  /**
   * Algorithm defined to generate the token to perform the authorisation
   */
  public enum JwtSignatureAlgorithmEnum {
    SHA256(String.valueOf("HMAC_SHA256")),
    
    SHA384(String.valueOf("HMAC_SHA384")),
    
    SHA512(String.valueOf("HMAC_SHA512"));

    private String value;

    JwtSignatureAlgorithmEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static JwtSignatureAlgorithmEnum fromValue(String value) {
      for (JwtSignatureAlgorithmEnum b : JwtSignatureAlgorithmEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_JWT_SIGNATURE_ALGORITHM = "jwtSignatureAlgorithm";
  @javax.annotation.Nonnull
  private JwtSignatureAlgorithmEnum jwtSignatureAlgorithm;

  public static final String JSON_PROPERTY_EXPIRATION = "expiration";
  @javax.annotation.Nonnull
  private Integer expiration;

  public DetailedTrustedAppViewModel() {
  }

  public DetailedTrustedAppViewModel appId(@javax.annotation.Nonnull String appId) {
    
    this.appId = appId;
    return this;
  }

  /**
   * UUID of the trusted app
   * @return appId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_APP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAppId() {
    return appId;
  }


  @JsonProperty(JSON_PROPERTY_APP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAppId(@javax.annotation.Nonnull String appId) {
    this.appId = appId;
  }

  public DetailedTrustedAppViewModel tenantId(@javax.annotation.Nonnull String tenantId) {
    
    this.tenantId = tenantId;
    return this;
  }

  /**
   * Tenant ID
   * @return tenantId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TENANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTenantId() {
    return tenantId;
  }


  @JsonProperty(JSON_PROPERTY_TENANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTenantId(@javax.annotation.Nonnull String tenantId) {
    this.tenantId = tenantId;
  }

  public DetailedTrustedAppViewModel name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Name defined in the trusted app
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public DetailedTrustedAppViewModel status(@javax.annotation.Nonnull StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * Current status of the trusted app
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }

  public DetailedTrustedAppViewModel permissions(@javax.annotation.Nonnull List<String> permissions) {
    
    this.permissions = permissions;
    return this;
  }

  public DetailedTrustedAppViewModel addPermissionsItem(String permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new ArrayList<>();
    }
    this.permissions.add(permissionsItem);
    return this;
  }

  /**
   * List of permissions assigned to the trusted app
   * @return permissions
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getPermissions() {
    return permissions;
  }


  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPermissions(@javax.annotation.Nonnull List<String> permissions) {
    this.permissions = permissions;
  }

  public DetailedTrustedAppViewModel description(@javax.annotation.Nonnull String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Description defined in the trusted app
   * @return description
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }

  public DetailedTrustedAppViewModel groups(@javax.annotation.Nonnull List<String> groups) {
    
    this.groups = groups;
    return this;
  }

  public DetailedTrustedAppViewModel addGroupsItem(String groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

  /**
   * List of groups defined in the trusted app
   * @return groups
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getGroups() {
    return groups;
  }


  @JsonProperty(JSON_PROPERTY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGroups(@javax.annotation.Nonnull List<String> groups) {
    this.groups = groups;
  }

  public DetailedTrustedAppViewModel jwtSignatureAlgorithm(@javax.annotation.Nonnull JwtSignatureAlgorithmEnum jwtSignatureAlgorithm) {
    
    this.jwtSignatureAlgorithm = jwtSignatureAlgorithm;
    return this;
  }

  /**
   * Algorithm defined to generate the token to perform the authorisation
   * @return jwtSignatureAlgorithm
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_JWT_SIGNATURE_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public JwtSignatureAlgorithmEnum getJwtSignatureAlgorithm() {
    return jwtSignatureAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_JWT_SIGNATURE_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setJwtSignatureAlgorithm(@javax.annotation.Nonnull JwtSignatureAlgorithmEnum jwtSignatureAlgorithm) {
    this.jwtSignatureAlgorithm = jwtSignatureAlgorithm;
  }

  public DetailedTrustedAppViewModel expiration(@javax.annotation.Nonnull Integer expiration) {
    
    this.expiration = expiration;
    return this;
  }

  /**
   * Expiration time (in seconds) defined for the token generated when the trusted app is authorised
   * @return expiration
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXPIRATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getExpiration() {
    return expiration;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpiration(@javax.annotation.Nonnull Integer expiration) {
    this.expiration = expiration;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailedTrustedAppViewModel detailedTrustedAppViewModel = (DetailedTrustedAppViewModel) o;
    return Objects.equals(this.appId, detailedTrustedAppViewModel.appId) &&
        Objects.equals(this.tenantId, detailedTrustedAppViewModel.tenantId) &&
        Objects.equals(this.name, detailedTrustedAppViewModel.name) &&
        Objects.equals(this.status, detailedTrustedAppViewModel.status) &&
        Objects.equals(this.permissions, detailedTrustedAppViewModel.permissions) &&
        Objects.equals(this.description, detailedTrustedAppViewModel.description) &&
        Objects.equals(this.groups, detailedTrustedAppViewModel.groups) &&
        Objects.equals(this.jwtSignatureAlgorithm, detailedTrustedAppViewModel.jwtSignatureAlgorithm) &&
        Objects.equals(this.expiration, detailedTrustedAppViewModel.expiration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appId, tenantId, name, status, permissions, description, groups, jwtSignatureAlgorithm, expiration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailedTrustedAppViewModel {\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    jwtSignatureAlgorithm: ").append(toIndentedString(jwtSignatureAlgorithm)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

