/*
 * Trusted Applications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GroupViewModel
 */
@JsonPropertyOrder({
  GroupViewModel.JSON_PROPERTY_GID,
  GroupViewModel.JSON_PROPERTY_GUID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class GroupViewModel {
  public static final String JSON_PROPERTY_GID = "gid";
  @javax.annotation.Nonnull
  private String gid;

  public static final String JSON_PROPERTY_GUID = "guid";
  @javax.annotation.Nonnull
  private String guid;

  public GroupViewModel() {
  }

  public GroupViewModel gid(@javax.annotation.Nonnull String gid) {
    
    this.gid = gid;
    return this;
  }

  /**
   * Name of the group. In case the group does not exist in nebulaUSERS, it shall have the value of GUID
   * @return gid
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getGid() {
    return gid;
  }


  @JsonProperty(JSON_PROPERTY_GID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGid(@javax.annotation.Nonnull String gid) {
    this.gid = gid;
  }

  public GroupViewModel guid(@javax.annotation.Nonnull String guid) {
    
    this.guid = guid;
    return this;
  }

  /**
   * UUID of the group
   * @return guid
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GUID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getGuid() {
    return guid;
  }


  @JsonProperty(JSON_PROPERTY_GUID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGuid(@javax.annotation.Nonnull String guid) {
    this.guid = guid;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupViewModel groupViewModel = (GroupViewModel) o;
    return Objects.equals(this.gid, groupViewModel.gid) &&
        Objects.equals(this.guid, groupViewModel.guid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gid, guid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupViewModel {\n");
    sb.append("    gid: ").append(toIndentedString(gid)).append("\n");
    sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

