/*
 * Trusted Applications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Pagination information for listing operations
 */
@JsonPropertyOrder({
  NebulaPagination.JSON_PROPERTY_TOTAL_ELEMENTS,
  NebulaPagination.JSON_PROPERTY_TOTAL_PAGES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class NebulaPagination {
  public static final String JSON_PROPERTY_TOTAL_ELEMENTS = "totalElements";
  @javax.annotation.Nonnull
  private Integer totalElements;

  public static final String JSON_PROPERTY_TOTAL_PAGES = "totalPages";
  @javax.annotation.Nonnull
  private Integer totalPages;

  public NebulaPagination() {
  }

  public NebulaPagination totalElements(@javax.annotation.Nonnull Integer totalElements) {
    
    this.totalElements = totalElements;
    return this;
  }

  /**
   * Total number of items of the operation carried out
   * @return totalElements
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOTAL_ELEMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTotalElements() {
    return totalElements;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_ELEMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalElements(@javax.annotation.Nonnull Integer totalElements) {
    this.totalElements = totalElements;
  }

  public NebulaPagination totalPages(@javax.annotation.Nonnull Integer totalPages) {
    
    this.totalPages = totalPages;
    return this;
  }

  /**
   * Total number of available pages of the operation carried out
   * @return totalPages
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOTAL_PAGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTotalPages() {
    return totalPages;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_PAGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalPages(@javax.annotation.Nonnull Integer totalPages) {
    this.totalPages = totalPages;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NebulaPagination nebulaPagination = (NebulaPagination) o;
    return Objects.equals(this.totalElements, nebulaPagination.totalElements) &&
        Objects.equals(this.totalPages, nebulaPagination.totalPages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalElements, totalPages);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NebulaPagination {\n");
    sb.append("    totalElements: ").append(toIndentedString(totalElements)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

