/*
 * Trusted Applications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TrustedAppSecParamsViewModel
 */
@JsonPropertyOrder({
  TrustedAppSecParamsViewModel.JSON_PROPERTY_TOKEN_EXPIRATION,
  TrustedAppSecParamsViewModel.JSON_PROPERTY_SIGNATURE_ALGORITHM,
  TrustedAppSecParamsViewModel.JSON_PROPERTY_STATUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class TrustedAppSecParamsViewModel {
  public static final String JSON_PROPERTY_TOKEN_EXPIRATION = "tokenExpiration";
  @javax.annotation.Nonnull
  private Integer tokenExpiration;

  /**
   * Algorithm used by the trusted app to generate the token to perform the authorisation
   */
  public enum SignatureAlgorithmEnum {
    SHA256(String.valueOf("HMAC_SHA256")),
    
    SHA384(String.valueOf("HMAC_SHA384")),
    
    SHA512(String.valueOf("HMAC_SHA512")),
    
    SHA2562(String.valueOf("HMAC_SHA256")),
    
    SHA3842(String.valueOf("HMAC_SHA384")),
    
    SHA5122(String.valueOf("HMAC_SHA512"));

    private String value;

    SignatureAlgorithmEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SignatureAlgorithmEnum fromValue(String value) {
      for (SignatureAlgorithmEnum b : SignatureAlgorithmEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SIGNATURE_ALGORITHM = "signatureAlgorithm";
  @javax.annotation.Nonnull
  private SignatureAlgorithmEnum signatureAlgorithm;

  /**
   * Trusted app status
   */
  public enum StatusEnum {
    ENABLED(String.valueOf("ENABLED")),
    
    DISABLED(String.valueOf("DISABLED")),
    
    ENABLED2(String.valueOf("ENABLED")),
    
    DISABLED2(String.valueOf("DISABLED"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private StatusEnum status;

  public TrustedAppSecParamsViewModel() {
  }

  public TrustedAppSecParamsViewModel tokenExpiration(@javax.annotation.Nonnull Integer tokenExpiration) {
    
    this.tokenExpiration = tokenExpiration;
    return this;
  }

  /**
   * Expiration time (in minutes) of the token to be generated by the system when the trusted app is authorised
   * minimum: 1
   * maximum: 1440
   * @return tokenExpiration
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOKEN_EXPIRATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTokenExpiration() {
    return tokenExpiration;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN_EXPIRATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTokenExpiration(@javax.annotation.Nonnull Integer tokenExpiration) {
    this.tokenExpiration = tokenExpiration;
  }

  public TrustedAppSecParamsViewModel signatureAlgorithm(@javax.annotation.Nonnull SignatureAlgorithmEnum signatureAlgorithm) {
    
    this.signatureAlgorithm = signatureAlgorithm;
    return this;
  }

  /**
   * Algorithm used by the trusted app to generate the token to perform the authorisation
   * @return signatureAlgorithm
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNATURE_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SignatureAlgorithmEnum getSignatureAlgorithm() {
    return signatureAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignatureAlgorithm(@javax.annotation.Nonnull SignatureAlgorithmEnum signatureAlgorithm) {
    this.signatureAlgorithm = signatureAlgorithm;
  }

  public TrustedAppSecParamsViewModel status(@javax.annotation.Nonnull StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * Trusted app status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrustedAppSecParamsViewModel trustedAppSecParamsViewModel = (TrustedAppSecParamsViewModel) o;
    return Objects.equals(this.tokenExpiration, trustedAppSecParamsViewModel.tokenExpiration) &&
        Objects.equals(this.signatureAlgorithm, trustedAppSecParamsViewModel.signatureAlgorithm) &&
        Objects.equals(this.status, trustedAppSecParamsViewModel.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tokenExpiration, signatureAlgorithm, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrustedAppSecParamsViewModel {\n");
    sb.append("    tokenExpiration: ").append(toIndentedString(tokenExpiration)).append("\n");
    sb.append("    signatureAlgorithm: ").append(toIndentedString(signatureAlgorithm)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

