/*
 * Digital signature API
 * API for digital signatures in Nebula Suite
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.api;

import org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.services.ApiException;
import org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model.CadesSignatureResponse;
import org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model.ErrorResponseOldAuthEnum;
import org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model.ErrorResponseSignature400Codes;
import org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model.ErrorResponseSignature404Codes;
import org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model.ErrorResponseSignature500Codes;
import java.io.File;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CadEsSignatureApi
 */
class CadEsSignatureApiTest {

    private final CadEsSignatureApi api = new CadEsSignatureApi();

    /**
     * Sign a document with CAdES
     *
     * Signs a document with the CAdES signature standard
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void cadesSignTest() throws ApiException {
        //
        //String data = null;
        //
        //File _file = null;
        //
        //CadesSignatureResponse response = api.cadesSign(data, _file);

        // TODO: test validations
    }
}
