/*
 * Digital signature API
 * API for digital signatures in Nebula Suite
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.api;

import org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.services.ApiException;
import org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model.ErrorResponseOldAuthEnum;
import org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model.ErrorResponseSignature400Codes;
import org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model.ErrorResponseSignature404Codes;
import org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model.ErrorResponseSignature500Codes;
import java.io.File;
import org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model.PadesSignatureOperationResponse;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PadEsSignatureApi
 */
class PadEsSignatureApiTest {

    private final PadEsSignatureApi api = new PadEsSignatureApi();

    /**
     * Sign a PDF file
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void signDocumentV1Test() throws ApiException {
        //
        //File _file = null;
        //
        //String data = null;
        //
        //List<File> images = null;
        //
        //PadesSignatureOperationResponse response = api.signDocumentV1(_file, data, images);

        // TODO: test validations
    }
}
