/*
 * Digital signature API
 * API for digital signatures in Nebula Suite
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CadesSignLocation
 */
@JsonPropertyOrder({
  CadesSignLocation.JSON_PROPERTY_COUNTRY,
  CadesSignLocation.JSON_PROPERTY_LOCALITY,
  CadesSignLocation.JSON_PROPERTY_POSTAL_ADDRESS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class CadesSignLocation {
  public static final String JSON_PROPERTY_COUNTRY = "country";
  @javax.annotation.Nullable
  private String country;

  public static final String JSON_PROPERTY_LOCALITY = "locality";
  @javax.annotation.Nullable
  private String locality;

  public static final String JSON_PROPERTY_POSTAL_ADDRESS = "postalAddress";
  @javax.annotation.Nullable
  private List<String> postalAddress = new ArrayList<>();

  public CadesSignLocation() {
  }

  public CadesSignLocation country(@javax.annotation.Nullable String country) {
    
    this.country = country;
    return this;
  }

  /**
   * Country where the signature is made
   * @return country
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }

  public CadesSignLocation locality(@javax.annotation.Nullable String locality) {
    
    this.locality = locality;
    return this;
  }

  /**
   * Locality where the signature is made
   * @return locality
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocality() {
    return locality;
  }


  @JsonProperty(JSON_PROPERTY_LOCALITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocality(@javax.annotation.Nullable String locality) {
    this.locality = locality;
  }

  public CadesSignLocation postalAddress(@javax.annotation.Nullable List<String> postalAddress) {
    
    this.postalAddress = postalAddress;
    return this;
  }

  public CadesSignLocation addPostalAddressItem(String postalAddressItem) {
    if (this.postalAddress == null) {
      this.postalAddress = new ArrayList<>();
    }
    this.postalAddress.add(postalAddressItem);
    return this;
  }

  /**
   * List of postal addresses where the signature is made
   * @return postalAddress
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSTAL_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getPostalAddress() {
    return postalAddress;
  }


  @JsonProperty(JSON_PROPERTY_POSTAL_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPostalAddress(@javax.annotation.Nullable List<String> postalAddress) {
    this.postalAddress = postalAddress;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CadesSignLocation cadesSignLocation = (CadesSignLocation) o;
    return Objects.equals(this.country, cadesSignLocation.country) &&
        Objects.equals(this.locality, cadesSignLocation.locality) &&
        Objects.equals(this.postalAddress, cadesSignLocation.postalAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, locality, postalAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CadesSignLocation {\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    locality: ").append(toIndentedString(locality)).append("\n");
    sb.append("    postalAddress: ").append(toIndentedString(postalAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

