/*
 * Digital signature API
 * API for digital signatures in Nebula Suite
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model.CadesSignLocation;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CadesSignatureRequest
 */
@JsonPropertyOrder({
  CadesSignatureRequest.JSON_PROPERTY_SIGN_LEVEL,
  CadesSignatureRequest.JSON_PROPERTY_SIGN_PACKAGE,
  CadesSignatureRequest.JSON_PROPERTY_DIGEST_ALGORITHM,
  CadesSignatureRequest.JSON_PROPERTY_CERT_ID,
  CadesSignatureRequest.JSON_PROPERTY_CERT_PIN,
  CadesSignatureRequest.JSON_PROPERTY_POLICY_ID,
  CadesSignatureRequest.JSON_PROPERTY_POLICY_HASH,
  CadesSignatureRequest.JSON_PROPERTY_POLICY_DIGEST_ALGORITHM,
  CadesSignatureRequest.JSON_PROPERTY_POLICY_QUALIFIER,
  CadesSignatureRequest.JSON_PROPERTY_FILE_HASH,
  CadesSignatureRequest.JSON_PROPERTY_FILE_HASH_DIGEST_ALGORITHM,
  CadesSignatureRequest.JSON_PROPERTY_FILE_HASH_NAME,
  CadesSignatureRequest.JSON_PROPERTY_TSA_U_R_L,
  CadesSignatureRequest.JSON_PROPERTY_TSA_U_S_R,
  CadesSignatureRequest.JSON_PROPERTY_TSA_P_W_D,
  CadesSignatureRequest.JSON_PROPERTY_SIGN_LOCATION,
  CadesSignatureRequest.JSON_PROPERTY_SIGNER_ROLES,
  CadesSignatureRequest.JSON_PROPERTY_COMMITMENT_TYPES,
  CadesSignatureRequest.JSON_PROPERTY_COMPANY,
  CadesSignatureRequest.JSON_PROPERTY_USER_UUID,
  CadesSignatureRequest.JSON_PROPERTY_USER_ID,
  CadesSignatureRequest.JSON_PROPERTY_SIGN_CONTAINER,
  CadesSignatureRequest.JSON_PROPERTY_CERT_TICKET
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class CadesSignatureRequest {
  /**
   * Signature level
   */
  public enum SignLevelEnum {
    B(String.valueOf("B")),
    
    T(String.valueOf("T")),
    
    LT(String.valueOf("LT")),
    
    LTA(String.valueOf("LTA"));

    private String value;

    SignLevelEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SignLevelEnum fromValue(String value) {
      for (SignLevelEnum b : SignLevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SIGN_LEVEL = "signLevel";
  @javax.annotation.Nullable
  private SignLevelEnum signLevel = SignLevelEnum.B;

  /**
   * Signature package
   */
  public enum SignPackageEnum {
    DETACHED(String.valueOf("DETACHED")),
    
    ENVELOPING(String.valueOf("ENVELOPING"));

    private String value;

    SignPackageEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SignPackageEnum fromValue(String value) {
      for (SignPackageEnum b : SignPackageEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SIGN_PACKAGE = "signPackage";
  @javax.annotation.Nullable
  private SignPackageEnum signPackage = SignPackageEnum.DETACHED;

  /**
   * Algorithm used to obtain the digest of the document to sign
   */
  public enum DigestAlgorithmEnum {
    SHA1(String.valueOf("SHA1")),
    
    SHA256(String.valueOf("SHA256")),
    
    SHA384(String.valueOf("SHA384")),
    
    SHA512(String.valueOf("SHA512"));

    private String value;

    DigestAlgorithmEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DigestAlgorithmEnum fromValue(String value) {
      for (DigestAlgorithmEnum b : DigestAlgorithmEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DIGEST_ALGORITHM = "digestAlgorithm";
  @javax.annotation.Nullable
  private DigestAlgorithmEnum digestAlgorithm = DigestAlgorithmEnum.SHA256;

  public static final String JSON_PROPERTY_CERT_ID = "certId";
  @javax.annotation.Nullable
  private Integer certId;

  public static final String JSON_PROPERTY_CERT_PIN = "certPin";
  @javax.annotation.Nullable
  private String certPin;

  public static final String JSON_PROPERTY_POLICY_ID = "policyId";
  @javax.annotation.Nullable
  private String policyId;

  public static final String JSON_PROPERTY_POLICY_HASH = "policyHash";
  @javax.annotation.Nullable
  private String policyHash;

  /**
   * Digest algorithm with which the policyHash was made. Can only be used if the signature level is B
   */
  public enum PolicyDigestAlgorithmEnum {
    SHA1(String.valueOf("SHA1")),
    
    SHA256(String.valueOf("SHA256")),
    
    SHA384(String.valueOf("SHA384")),
    
    SHA512(String.valueOf("SHA512"));

    private String value;

    PolicyDigestAlgorithmEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PolicyDigestAlgorithmEnum fromValue(String value) {
      for (PolicyDigestAlgorithmEnum b : PolicyDigestAlgorithmEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_POLICY_DIGEST_ALGORITHM = "policyDigestAlgorithm";
  @javax.annotation.Nullable
  private PolicyDigestAlgorithmEnum policyDigestAlgorithm;

  public static final String JSON_PROPERTY_POLICY_QUALIFIER = "policyQualifier";
  @javax.annotation.Nullable
  private String policyQualifier;

  public static final String JSON_PROPERTY_FILE_HASH = "fileHash";
  @javax.annotation.Nullable
  private String fileHash;

  /**
   * Algorithm used to generate fileHash. This parameter must have the same value as the &#39;digestAlgorithm&#39; parameter
   */
  public enum FileHashDigestAlgorithmEnum {
    SHA1(String.valueOf("SHA1")),
    
    SHA256(String.valueOf("SHA256")),
    
    SHA384(String.valueOf("SHA384")),
    
    SHA512(String.valueOf("SHA512"));

    private String value;

    FileHashDigestAlgorithmEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FileHashDigestAlgorithmEnum fromValue(String value) {
      for (FileHashDigestAlgorithmEnum b : FileHashDigestAlgorithmEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FILE_HASH_DIGEST_ALGORITHM = "fileHashDigestAlgorithm";
  @javax.annotation.Nullable
  private FileHashDigestAlgorithmEnum fileHashDigestAlgorithm;

  public static final String JSON_PROPERTY_FILE_HASH_NAME = "fileHashName";
  @javax.annotation.Nullable
  private String fileHashName;

  public static final String JSON_PROPERTY_TSA_U_R_L = "tsaURL";
  @javax.annotation.Nullable
  private String tsaURL;

  public static final String JSON_PROPERTY_TSA_U_S_R = "tsaUSR";
  @javax.annotation.Nullable
  private String tsaUSR;

  public static final String JSON_PROPERTY_TSA_P_W_D = "tsaPWD";
  @javax.annotation.Nullable
  private String tsaPWD;

  public static final String JSON_PROPERTY_SIGN_LOCATION = "signLocation";
  @javax.annotation.Nullable
  private CadesSignLocation signLocation;

  public static final String JSON_PROPERTY_SIGNER_ROLES = "signerRoles";
  @javax.annotation.Nullable
  private List<String> signerRoles = new ArrayList<>();

  /**
   * Gets or Sets commitmentTypes
   */
  public enum CommitmentTypesEnum {
    PROOF_OF_ORIGIN(String.valueOf("ProofOfOrigin")),
    
    PROOF_OF_RECEIPT(String.valueOf("ProofOfReceipt")),
    
    PROOF_OF_DELIVERY(String.valueOf("ProofOfDelivery")),
    
    PROOF_OF_SENDER(String.valueOf("ProofOfSender")),
    
    PROOF_OF_APPROVAL(String.valueOf("ProofOfApproval")),
    
    PROOF_OF_CREATION(String.valueOf("ProofOfCreation"));

    private String value;

    CommitmentTypesEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CommitmentTypesEnum fromValue(String value) {
      for (CommitmentTypesEnum b : CommitmentTypesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_COMMITMENT_TYPES = "commitmentTypes";
  @javax.annotation.Nullable
  private List<CommitmentTypesEnum> commitmentTypes = new ArrayList<>();

  public static final String JSON_PROPERTY_COMPANY = "company";
  @javax.annotation.Nullable
  private String company;

  public static final String JSON_PROPERTY_USER_UUID = "userUuid";
  @javax.annotation.Nullable
  private String userUuid;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  @javax.annotation.Nullable
  private String userId;

  public static final String JSON_PROPERTY_SIGN_CONTAINER = "signContainer";
  @javax.annotation.Nullable
  private String signContainer;

  public static final String JSON_PROPERTY_CERT_TICKET = "certTicket";
  @javax.annotation.Nullable
  private String certTicket;

  public CadesSignatureRequest() {
  }

  public CadesSignatureRequest signLevel(@javax.annotation.Nullable SignLevelEnum signLevel) {
    
    this.signLevel = signLevel;
    return this;
  }

  /**
   * Signature level
   * @return signLevel
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGN_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SignLevelEnum getSignLevel() {
    return signLevel;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignLevel(@javax.annotation.Nullable SignLevelEnum signLevel) {
    this.signLevel = signLevel;
  }

  public CadesSignatureRequest signPackage(@javax.annotation.Nullable SignPackageEnum signPackage) {
    
    this.signPackage = signPackage;
    return this;
  }

  /**
   * Signature package
   * @return signPackage
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGN_PACKAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SignPackageEnum getSignPackage() {
    return signPackage;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_PACKAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignPackage(@javax.annotation.Nullable SignPackageEnum signPackage) {
    this.signPackage = signPackage;
  }

  public CadesSignatureRequest digestAlgorithm(@javax.annotation.Nullable DigestAlgorithmEnum digestAlgorithm) {
    
    this.digestAlgorithm = digestAlgorithm;
    return this;
  }

  /**
   * Algorithm used to obtain the digest of the document to sign
   * @return digestAlgorithm
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DigestAlgorithmEnum getDigestAlgorithm() {
    return digestAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDigestAlgorithm(@javax.annotation.Nullable DigestAlgorithmEnum digestAlgorithm) {
    this.digestAlgorithm = digestAlgorithm;
  }

  public CadesSignatureRequest certId(@javax.annotation.Nullable Integer certId) {
    
    this.certId = certId;
    return this;
  }

  /**
   * This parameter is linked with the signingId response parameter of the get user certificates operation
   * @return certId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCertId() {
    return certId;
  }


  @JsonProperty(JSON_PROPERTY_CERT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertId(@javax.annotation.Nullable Integer certId) {
    this.certId = certId;
  }

  public CadesSignatureRequest certPin(@javax.annotation.Nullable String certPin) {
    
    this.certPin = certPin;
    return this;
  }

  /**
   * PIN of the selected certificate, if needed
   * @return certPin
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERT_PIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCertPin() {
    return certPin;
  }


  @JsonProperty(JSON_PROPERTY_CERT_PIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertPin(@javax.annotation.Nullable String certPin) {
    this.certPin = certPin;
  }

  public CadesSignatureRequest policyId(@javax.annotation.Nullable String policyId) {
    
    this.policyId = policyId;
    return this;
  }

  /**
   * Identifier of the policy. The value is the OID. Can only be used if the signature level is B
   * @return policyId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POLICY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPolicyId() {
    return policyId;
  }


  @JsonProperty(JSON_PROPERTY_POLICY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPolicyId(@javax.annotation.Nullable String policyId) {
    this.policyId = policyId;
  }

  public CadesSignatureRequest policyHash(@javax.annotation.Nullable String policyHash) {
    
    this.policyHash = policyHash;
    return this;
  }

  /**
   * Hash of the policy to be used. Hexadecimal in Base64. Can only be used if the signature level is B
   * @return policyHash
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POLICY_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPolicyHash() {
    return policyHash;
  }


  @JsonProperty(JSON_PROPERTY_POLICY_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPolicyHash(@javax.annotation.Nullable String policyHash) {
    this.policyHash = policyHash;
  }

  public CadesSignatureRequest policyDigestAlgorithm(@javax.annotation.Nullable PolicyDigestAlgorithmEnum policyDigestAlgorithm) {
    
    this.policyDigestAlgorithm = policyDigestAlgorithm;
    return this;
  }

  /**
   * Digest algorithm with which the policyHash was made. Can only be used if the signature level is B
   * @return policyDigestAlgorithm
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POLICY_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PolicyDigestAlgorithmEnum getPolicyDigestAlgorithm() {
    return policyDigestAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_POLICY_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPolicyDigestAlgorithm(@javax.annotation.Nullable PolicyDigestAlgorithmEnum policyDigestAlgorithm) {
    this.policyDigestAlgorithm = policyDigestAlgorithm;
  }

  public CadesSignatureRequest policyQualifier(@javax.annotation.Nullable String policyQualifier) {
    
    this.policyQualifier = policyQualifier;
    return this;
  }

  /**
   * Defines a policy identifier qualifier. Can only be used if the signature level is B
   * @return policyQualifier
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POLICY_QUALIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPolicyQualifier() {
    return policyQualifier;
  }


  @JsonProperty(JSON_PROPERTY_POLICY_QUALIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPolicyQualifier(@javax.annotation.Nullable String policyQualifier) {
    this.policyQualifier = policyQualifier;
  }

  public CadesSignatureRequest fileHash(@javax.annotation.Nullable String fileHash) {
    
    this.fileHash = fileHash;
    return this;
  }

  /**
   * Defines a hash to be signed. Only used if Multipart File is not specified
   * @return fileHash
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILE_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFileHash() {
    return fileHash;
  }


  @JsonProperty(JSON_PROPERTY_FILE_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileHash(@javax.annotation.Nullable String fileHash) {
    this.fileHash = fileHash;
  }

  public CadesSignatureRequest fileHashDigestAlgorithm(@javax.annotation.Nullable FileHashDigestAlgorithmEnum fileHashDigestAlgorithm) {
    
    this.fileHashDigestAlgorithm = fileHashDigestAlgorithm;
    return this;
  }

  /**
   * Algorithm used to generate fileHash. This parameter must have the same value as the &#39;digestAlgorithm&#39; parameter
   * @return fileHashDigestAlgorithm
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILE_HASH_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FileHashDigestAlgorithmEnum getFileHashDigestAlgorithm() {
    return fileHashDigestAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_FILE_HASH_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileHashDigestAlgorithm(@javax.annotation.Nullable FileHashDigestAlgorithmEnum fileHashDigestAlgorithm) {
    this.fileHashDigestAlgorithm = fileHashDigestAlgorithm;
  }

  public CadesSignatureRequest fileHashName(@javax.annotation.Nullable String fileHashName) {
    
    this.fileHashName = fileHashName;
    return this;
  }

  /**
   * Name of specified hash in data.fileHash
   * @return fileHashName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILE_HASH_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFileHashName() {
    return fileHashName;
  }


  @JsonProperty(JSON_PROPERTY_FILE_HASH_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileHashName(@javax.annotation.Nullable String fileHashName) {
    this.fileHashName = fileHashName;
  }

  public CadesSignatureRequest tsaURL(@javax.annotation.Nullable String tsaURL) {
    
    this.tsaURL = tsaURL;
    return this;
  }

  /**
   * URL of a Timestamping authority to be used in T, LT or LTA signature levels
   * @return tsaURL
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TSA_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTsaURL() {
    return tsaURL;
  }


  @JsonProperty(JSON_PROPERTY_TSA_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTsaURL(@javax.annotation.Nullable String tsaURL) {
    this.tsaURL = tsaURL;
  }

  public CadesSignatureRequest tsaUSR(@javax.annotation.Nullable String tsaUSR) {
    
    this.tsaUSR = tsaUSR;
    return this;
  }

  /**
   * User of the credentials of the Timestamping authority, if authentication is required
   * @return tsaUSR
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TSA_U_S_R)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTsaUSR() {
    return tsaUSR;
  }


  @JsonProperty(JSON_PROPERTY_TSA_U_S_R)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTsaUSR(@javax.annotation.Nullable String tsaUSR) {
    this.tsaUSR = tsaUSR;
  }

  public CadesSignatureRequest tsaPWD(@javax.annotation.Nullable String tsaPWD) {
    
    this.tsaPWD = tsaPWD;
    return this;
  }

  /**
   * Password of the credentials of the Timestamping authority, if authentication is required
   * @return tsaPWD
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TSA_P_W_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTsaPWD() {
    return tsaPWD;
  }


  @JsonProperty(JSON_PROPERTY_TSA_P_W_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTsaPWD(@javax.annotation.Nullable String tsaPWD) {
    this.tsaPWD = tsaPWD;
  }

  public CadesSignatureRequest signLocation(@javax.annotation.Nullable CadesSignLocation signLocation) {
    
    this.signLocation = signLocation;
    return this;
  }

  /**
   * Get signLocation
   * @return signLocation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGN_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CadesSignLocation getSignLocation() {
    return signLocation;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignLocation(@javax.annotation.Nullable CadesSignLocation signLocation) {
    this.signLocation = signLocation;
  }

  public CadesSignatureRequest signerRoles(@javax.annotation.Nullable List<String> signerRoles) {
    
    this.signerRoles = signerRoles;
    return this;
  }

  public CadesSignatureRequest addSignerRolesItem(String signerRolesItem) {
    if (this.signerRoles == null) {
      this.signerRoles = new ArrayList<>();
    }
    this.signerRoles.add(signerRolesItem);
    return this;
  }

  /**
   * List of roles of signer
   * @return signerRoles
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNER_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSignerRoles() {
    return signerRoles;
  }


  @JsonProperty(JSON_PROPERTY_SIGNER_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignerRoles(@javax.annotation.Nullable List<String> signerRoles) {
    this.signerRoles = signerRoles;
  }

  public CadesSignatureRequest commitmentTypes(@javax.annotation.Nullable List<CommitmentTypesEnum> commitmentTypes) {
    
    this.commitmentTypes = commitmentTypes;
    return this;
  }

  public CadesSignatureRequest addCommitmentTypesItem(CommitmentTypesEnum commitmentTypesItem) {
    if (this.commitmentTypes == null) {
      this.commitmentTypes = new ArrayList<>();
    }
    this.commitmentTypes.add(commitmentTypesItem);
    return this;
  }

  /**
   * List of compromises of the signed document
   * @return commitmentTypes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMITMENT_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CommitmentTypesEnum> getCommitmentTypes() {
    return commitmentTypes;
  }


  @JsonProperty(JSON_PROPERTY_COMMITMENT_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommitmentTypes(@javax.annotation.Nullable List<CommitmentTypesEnum> commitmentTypes) {
    this.commitmentTypes = commitmentTypes;
  }

  public CadesSignatureRequest company(@javax.annotation.Nullable String company) {
    
    this.company = company;
    return this;
  }

  /**
   * Get company
   * @return company
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCompany() {
    return company;
  }


  @JsonProperty(JSON_PROPERTY_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompany(@javax.annotation.Nullable String company) {
    this.company = company;
  }

  public CadesSignatureRequest userUuid(@javax.annotation.Nullable String userUuid) {
    
    this.userUuid = userUuid;
    return this;
  }

  /**
   * Get userUuid
   * @return userUuid
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserUuid() {
    return userUuid;
  }


  @JsonProperty(JSON_PROPERTY_USER_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserUuid(@javax.annotation.Nullable String userUuid) {
    this.userUuid = userUuid;
  }

  public CadesSignatureRequest userId(@javax.annotation.Nullable String userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
  }

  public CadesSignatureRequest signContainer(@javax.annotation.Nullable String signContainer) {
    
    this.signContainer = signContainer;
    return this;
  }

  /**
   * Get signContainer
   * @return signContainer
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGN_CONTAINER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignContainer() {
    return signContainer;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_CONTAINER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignContainer(@javax.annotation.Nullable String signContainer) {
    this.signContainer = signContainer;
  }

  public CadesSignatureRequest certTicket(@javax.annotation.Nullable String certTicket) {
    
    this.certTicket = certTicket;
    return this;
  }

  /**
   * Get certTicket
   * @return certTicket
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERT_TICKET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCertTicket() {
    return certTicket;
  }


  @JsonProperty(JSON_PROPERTY_CERT_TICKET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertTicket(@javax.annotation.Nullable String certTicket) {
    this.certTicket = certTicket;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CadesSignatureRequest cadesSignatureRequest = (CadesSignatureRequest) o;
    return Objects.equals(this.signLevel, cadesSignatureRequest.signLevel) &&
        Objects.equals(this.signPackage, cadesSignatureRequest.signPackage) &&
        Objects.equals(this.digestAlgorithm, cadesSignatureRequest.digestAlgorithm) &&
        Objects.equals(this.certId, cadesSignatureRequest.certId) &&
        Objects.equals(this.certPin, cadesSignatureRequest.certPin) &&
        Objects.equals(this.policyId, cadesSignatureRequest.policyId) &&
        Objects.equals(this.policyHash, cadesSignatureRequest.policyHash) &&
        Objects.equals(this.policyDigestAlgorithm, cadesSignatureRequest.policyDigestAlgorithm) &&
        Objects.equals(this.policyQualifier, cadesSignatureRequest.policyQualifier) &&
        Objects.equals(this.fileHash, cadesSignatureRequest.fileHash) &&
        Objects.equals(this.fileHashDigestAlgorithm, cadesSignatureRequest.fileHashDigestAlgorithm) &&
        Objects.equals(this.fileHashName, cadesSignatureRequest.fileHashName) &&
        Objects.equals(this.tsaURL, cadesSignatureRequest.tsaURL) &&
        Objects.equals(this.tsaUSR, cadesSignatureRequest.tsaUSR) &&
        Objects.equals(this.tsaPWD, cadesSignatureRequest.tsaPWD) &&
        Objects.equals(this.signLocation, cadesSignatureRequest.signLocation) &&
        Objects.equals(this.signerRoles, cadesSignatureRequest.signerRoles) &&
        Objects.equals(this.commitmentTypes, cadesSignatureRequest.commitmentTypes) &&
        Objects.equals(this.company, cadesSignatureRequest.company) &&
        Objects.equals(this.userUuid, cadesSignatureRequest.userUuid) &&
        Objects.equals(this.userId, cadesSignatureRequest.userId) &&
        Objects.equals(this.signContainer, cadesSignatureRequest.signContainer) &&
        Objects.equals(this.certTicket, cadesSignatureRequest.certTicket);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signLevel, signPackage, digestAlgorithm, certId, certPin, policyId, policyHash, policyDigestAlgorithm, policyQualifier, fileHash, fileHashDigestAlgorithm, fileHashName, tsaURL, tsaUSR, tsaPWD, signLocation, signerRoles, commitmentTypes, company, userUuid, userId, signContainer, certTicket);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CadesSignatureRequest {\n");
    sb.append("    signLevel: ").append(toIndentedString(signLevel)).append("\n");
    sb.append("    signPackage: ").append(toIndentedString(signPackage)).append("\n");
    sb.append("    digestAlgorithm: ").append(toIndentedString(digestAlgorithm)).append("\n");
    sb.append("    certId: ").append(toIndentedString(certId)).append("\n");
    sb.append("    certPin: ").append(toIndentedString(certPin)).append("\n");
    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("    policyHash: ").append(toIndentedString(policyHash)).append("\n");
    sb.append("    policyDigestAlgorithm: ").append(toIndentedString(policyDigestAlgorithm)).append("\n");
    sb.append("    policyQualifier: ").append(toIndentedString(policyQualifier)).append("\n");
    sb.append("    fileHash: ").append(toIndentedString(fileHash)).append("\n");
    sb.append("    fileHashDigestAlgorithm: ").append(toIndentedString(fileHashDigestAlgorithm)).append("\n");
    sb.append("    fileHashName: ").append(toIndentedString(fileHashName)).append("\n");
    sb.append("    tsaURL: ").append(toIndentedString(tsaURL)).append("\n");
    sb.append("    tsaUSR: ").append(toIndentedString(tsaUSR)).append("\n");
    sb.append("    tsaPWD: ").append(toIndentedString(tsaPWD)).append("\n");
    sb.append("    signLocation: ").append(toIndentedString(signLocation)).append("\n");
    sb.append("    signerRoles: ").append(toIndentedString(signerRoles)).append("\n");
    sb.append("    commitmentTypes: ").append(toIndentedString(commitmentTypes)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    userUuid: ").append(toIndentedString(userUuid)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    signContainer: ").append(toIndentedString(signContainer)).append("\n");
    sb.append("    certTicket: ").append(toIndentedString(certTicket)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

