/*
 * Digital signature API
 * API for digital signatures in Nebula Suite
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ErrorResponseSignature400Codes
 */
@JsonPropertyOrder({
  ErrorResponseSignature400Codes.JSON_PROPERTY_ERROR,
  ErrorResponseSignature400Codes.JSON_PROPERTY_MESSAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ErrorResponseSignature400Codes {
  /**
   * Gets or Sets error
   */
  public enum ErrorEnum {
    SERVICE_ERROR(String.valueOf("SERVICE_ERROR")),
    
    INVALID_FILE(String.valueOf("INVALID_FILE")),
    
    INVALID_DATA(String.valueOf("INVALID_DATA")),
    
    INVALID_IMAGE(String.valueOf("INVALID_IMAGE")),
    
    INVALID_CERT(String.valueOf("INVALID_CERT")),
    
    INVALID_CERT_ID(String.valueOf("INVALID_CERT_ID")),
    
    INVALID_PIN_SIZE(String.valueOf("INVALID_PIN_SIZE")),
    
    INVALID_PIN_1(String.valueOf("INVALID_PIN_1")),
    
    INVALID_PIN_2(String.valueOf("INVALID_PIN_2")),
    
    PIN_BLOCKED(String.valueOf("PIN_BLOCKED")),
    
    PIN_REQUIRED(String.valueOf("PIN_REQUIRED")),
    
    CERTIFICATE_NOT_YET_VALID(String.valueOf("CERTIFICATE_NOT_YET_VALID")),
    
    CERTIFICATE_EXPIRED(String.valueOf("CERTIFICATE_EXPIRED")),
    
    ACL_BLOCK(String.valueOf("ACL_BLOCK")),
    
    TSA_NOT_ENABLED(String.valueOf("TSA_NOT_ENABLED"));

    private String value;

    ErrorEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ErrorEnum fromValue(String value) {
      for (ErrorEnum b : ErrorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ERROR = "error";
  @javax.annotation.Nullable
  private ErrorEnum error;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nullable
  private String message;

  public ErrorResponseSignature400Codes() {
  }

  public ErrorResponseSignature400Codes error(@javax.annotation.Nullable ErrorEnum error) {
    
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ErrorEnum getError() {
    return error;
  }


  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(@javax.annotation.Nullable ErrorEnum error) {
    this.error = error;
  }

  public ErrorResponseSignature400Codes message(@javax.annotation.Nullable String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorResponseSignature400Codes errorResponseSignature400Codes = (ErrorResponseSignature400Codes) o;
    return Objects.equals(this.error, errorResponseSignature400Codes.error) &&
        Objects.equals(this.message, errorResponseSignature400Codes.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorResponseSignature400Codes {\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

