/*
 * Digital signature API
 * API for digital signatures in Nebula Suite
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PadesSignatureResponse
 */
@JsonPropertyOrder({
  PadesSignatureResponse.JSON_PROPERTY_SIGNED_FILE,
  PadesSignatureResponse.JSON_PROPERTY_MESSAGE_EMBEDDED,
  PadesSignatureResponse.JSON_PROPERTY_CN_CERTIFICATE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class PadesSignatureResponse {
  public static final String JSON_PROPERTY_SIGNED_FILE = "signedFile";
  @javax.annotation.Nullable
  private String signedFile;

  public static final String JSON_PROPERTY_MESSAGE_EMBEDDED = "messageEmbedded";
  @javax.annotation.Nullable
  private String messageEmbedded;

  public static final String JSON_PROPERTY_CN_CERTIFICATE = "cnCertificate";
  @javax.annotation.Nullable
  private String cnCertificate;

  public PadesSignatureResponse() {
  }

  public PadesSignatureResponse signedFile(@javax.annotation.Nullable String signedFile) {
    
    this.signedFile = signedFile;
    return this;
  }

  /**
   * Get signedFile
   * @return signedFile
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignedFile() {
    return signedFile;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedFile(@javax.annotation.Nullable String signedFile) {
    this.signedFile = signedFile;
  }

  public PadesSignatureResponse messageEmbedded(@javax.annotation.Nullable String messageEmbedded) {
    
    this.messageEmbedded = messageEmbedded;
    return this;
  }

  /**
   * Get messageEmbedded
   * @return messageEmbedded
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE_EMBEDDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessageEmbedded() {
    return messageEmbedded;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE_EMBEDDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessageEmbedded(@javax.annotation.Nullable String messageEmbedded) {
    this.messageEmbedded = messageEmbedded;
  }

  public PadesSignatureResponse cnCertificate(@javax.annotation.Nullable String cnCertificate) {
    
    this.cnCertificate = cnCertificate;
    return this;
  }

  /**
   * Get cnCertificate
   * @return cnCertificate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CN_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCnCertificate() {
    return cnCertificate;
  }


  @JsonProperty(JSON_PROPERTY_CN_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCnCertificate(@javax.annotation.Nullable String cnCertificate) {
    this.cnCertificate = cnCertificate;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PadesSignatureResponse padesSignatureResponse = (PadesSignatureResponse) o;
    return Objects.equals(this.signedFile, padesSignatureResponse.signedFile) &&
        Objects.equals(this.messageEmbedded, padesSignatureResponse.messageEmbedded) &&
        Objects.equals(this.cnCertificate, padesSignatureResponse.cnCertificate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signedFile, messageEmbedded, cnCertificate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PadesSignatureResponse {\n");
    sb.append("    signedFile: ").append(toIndentedString(signedFile)).append("\n");
    sb.append("    messageEmbedded: ").append(toIndentedString(messageEmbedded)).append("\n");
    sb.append("    cnCertificate: ").append(toIndentedString(cnCertificate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

