/*
 * Digital signature API
 * API for digital signatures in Nebula Suite
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Required parameters in case that a visual signature is desired in the PDF file
 */
@JsonPropertyOrder({
  PadesVisualSignature.JSON_PROPERTY_X_AXIS,
  PadesVisualSignature.JSON_PROPERTY_Y_AXIS,
  PadesVisualSignature.JSON_PROPERTY_WIDTH,
  PadesVisualSignature.JSON_PROPERTY_HEIGHT,
  PadesVisualSignature.JSON_PROPERTY_PAGE,
  PadesVisualSignature.JSON_PROPERTY_POSITION_IN_PERCENTAGE,
  PadesVisualSignature.JSON_PROPERTY_MULTI_IMAGE_BUILD,
  PadesVisualSignature.JSON_PROPERTY_BACKGROUND_COLOR,
  PadesVisualSignature.JSON_PROPERTY_IMAGE_VERTICAL_ALIGNMENT,
  PadesVisualSignature.JSON_PROPERTY_FONT_NAME,
  PadesVisualSignature.JSON_PROPERTY_FONT_SIZE,
  PadesVisualSignature.JSON_PROPERTY_TEXT_COLOR,
  PadesVisualSignature.JSON_PROPERTY_TEXT,
  PadesVisualSignature.JSON_PROPERTY_TEXT_SIGNER_POSITION,
  PadesVisualSignature.JSON_PROPERTY_TEXT_HORIZONTAL_ALIGNMENT,
  PadesVisualSignature.JSON_PROPERTY_TEXT_IMAGE_VERTICAL_ALIGNMENT,
  PadesVisualSignature.JSON_PROPERTY_SIGN_LAST_PAGE,
  PadesVisualSignature.JSON_PROPERTY_SIGNATURE_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class PadesVisualSignature {
  public static final String JSON_PROPERTY_X_AXIS = "xAxis";
  @javax.annotation.Nullable
  private Float xAxis = 75f;

  public static final String JSON_PROPERTY_Y_AXIS = "yAxis";
  @javax.annotation.Nullable
  private Float yAxis = 85f;

  public static final String JSON_PROPERTY_WIDTH = "width";
  @javax.annotation.Nullable
  private Integer width = 170;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  @javax.annotation.Nullable
  private Integer height = 55;

  public static final String JSON_PROPERTY_PAGE = "page";
  @javax.annotation.Nullable
  private Integer page = 1;

  public static final String JSON_PROPERTY_POSITION_IN_PERCENTAGE = "positionInPercentage";
  @javax.annotation.Nullable
  private Boolean positionInPercentage = true;

  /**
   * If there is more than one image for the visual signature, this parameter will define how this images will be merged into one image
   */
  public enum MultiImageBuildEnum {
    HORIZONTAL(String.valueOf("HORIZONTAL")),
    
    VERTICAL(String.valueOf("VERTICAL"));

    private String value;

    MultiImageBuildEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MultiImageBuildEnum fromValue(String value) {
      for (MultiImageBuildEnum b : MultiImageBuildEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MULTI_IMAGE_BUILD = "multiImageBuild";
  @javax.annotation.Nullable
  private MultiImageBuildEnum multiImageBuild = MultiImageBuildEnum.HORIZONTAL;

  public static final String JSON_PROPERTY_BACKGROUND_COLOR = "backgroundColor";
  @javax.annotation.Nullable
  private List<Integer> backgroundColor = new ArrayList<>();

  /**
   * Vertical position of the visual signature in the page. In the case where the value is different than NONE and the parameter yAxis has a value different than the default one, the value defined by the parameter imageVerticalAlignment will prevail
   */
  public enum ImageVerticalAlignmentEnum {
    NONE(String.valueOf("NONE")),
    
    TOP(String.valueOf("TOP")),
    
    MIDDLE(String.valueOf("MIDDLE")),
    
    BOTTOM(String.valueOf("BOTTOM"));

    private String value;

    ImageVerticalAlignmentEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ImageVerticalAlignmentEnum fromValue(String value) {
      for (ImageVerticalAlignmentEnum b : ImageVerticalAlignmentEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_IMAGE_VERTICAL_ALIGNMENT = "imageVerticalAlignment";
  @javax.annotation.Nullable
  private ImageVerticalAlignmentEnum imageVerticalAlignment = ImageVerticalAlignmentEnum.NONE;

  /**
   * Name of the font that will be used for the text
   */
  public enum FontNameEnum {
    TIMES_ROMAN(String.valueOf("TIMES_ROMAN")),
    
    TIMES_BOLD(String.valueOf("TIMES_BOLD")),
    
    TIMES_ITALIC(String.valueOf("TIMES_ITALIC")),
    
    TIMES_BOLD_ITALIC(String.valueOf("TIMES_BOLD_ITALIC")),
    
    HELVETICA(String.valueOf("HELVETICA")),
    
    HELVETICA_BOLD(String.valueOf("HELVETICA_BOLD")),
    
    HELVETICA_OBLIQUE(String.valueOf("HELVETICA_OBLIQUE")),
    
    HELVETICA_BOLD_OBLIQUE(String.valueOf("HELVETICA_BOLD_OBLIQUE")),
    
    COURIER(String.valueOf("COURIER")),
    
    COURIER_BOLD(String.valueOf("COURIER_BOLD")),
    
    COURIER_OBLIQUE(String.valueOf("COURIER_OBLIQUE")),
    
    COURIER_BOLD_OBLIQUE(String.valueOf("COURIER_BOLD_OBLIQUE"));

    private String value;

    FontNameEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FontNameEnum fromValue(String value) {
      for (FontNameEnum b : FontNameEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FONT_NAME = "fontName";
  @javax.annotation.Nullable
  private FontNameEnum fontName = FontNameEnum.COURIER;

  public static final String JSON_PROPERTY_FONT_SIZE = "fontSize";
  @javax.annotation.Nullable
  private Integer fontSize = 12;

  public static final String JSON_PROPERTY_TEXT_COLOR = "textColor";
  @javax.annotation.Nullable
  private List<Integer> textColor = new ArrayList<>();

  public static final String JSON_PROPERTY_TEXT = "text";
  @javax.annotation.Nullable
  private String text = "Digitally signed by %CN% %DATE% %DATE_TIME%";

  /**
   * In case there is an image and text defined for the visual signature, this parameter will define the position between these two elements in the visual signature. The default value implies that the image will be at the left part of the visible signature while the text will be at the right part
   */
  public enum TextSignerPositionEnum {
    TOP(String.valueOf("TOP")),
    
    BOTTOM(String.valueOf("BOTTOM")),
    
    RIGHT(String.valueOf("RIGHT")),
    
    LEFT(String.valueOf("LEFT"));

    private String value;

    TextSignerPositionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TextSignerPositionEnum fromValue(String value) {
      for (TextSignerPositionEnum b : TextSignerPositionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TEXT_SIGNER_POSITION = "textSignerPosition";
  @javax.annotation.Nullable
  private TextSignerPositionEnum textSignerPosition = TextSignerPositionEnum.RIGHT;

  /**
   * Text alignment
   */
  public enum TextHorizontalAlignmentEnum {
    LEFT(String.valueOf("LEFT")),
    
    CENTER(String.valueOf("CENTER")),
    
    RIGHT(String.valueOf("RIGHT"));

    private String value;

    TextHorizontalAlignmentEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TextHorizontalAlignmentEnum fromValue(String value) {
      for (TextHorizontalAlignmentEnum b : TextHorizontalAlignmentEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TEXT_HORIZONTAL_ALIGNMENT = "textHorizontalAlignment";
  @javax.annotation.Nullable
  private TextHorizontalAlignmentEnum textHorizontalAlignment = TextHorizontalAlignmentEnum.LEFT;

  /**
   * In case there is more than one image with the parameter multiImageBuild with a value of HORIZONTAL and/or an image and text where the parameter textSignerPosition with values LEFT or RIGHT, this parameter defines the vertical alignment between those elements
   */
  public enum TextImageVerticalAlignmentEnum {
    TOP(String.valueOf("TOP")),
    
    MIDDLE(String.valueOf("MIDDLE")),
    
    BOTTOM(String.valueOf("BOTTOM"));

    private String value;

    TextImageVerticalAlignmentEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TextImageVerticalAlignmentEnum fromValue(String value) {
      for (TextImageVerticalAlignmentEnum b : TextImageVerticalAlignmentEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TEXT_IMAGE_VERTICAL_ALIGNMENT = "textImageVerticalAlignment";
  @javax.annotation.Nullable
  private TextImageVerticalAlignmentEnum textImageVerticalAlignment = TextImageVerticalAlignmentEnum.MIDDLE;

  public static final String JSON_PROPERTY_SIGN_LAST_PAGE = "signLastPage";
  @javax.annotation.Nullable
  private Boolean signLastPage = false;

  public static final String JSON_PROPERTY_SIGNATURE_FIELD = "signatureField";
  @javax.annotation.Nullable
  private String signatureField;

  public PadesVisualSignature() {
  }

  public PadesVisualSignature xAxis(@javax.annotation.Nullable Float xAxis) {
    
    this.xAxis = xAxis;
    return this;
  }

  /**
   * Horizontal position of the visible signature in pixels
   * minimum: 0
   * @return xAxis
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_X_AXIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getxAxis() {
    return xAxis;
  }


  @JsonProperty(JSON_PROPERTY_X_AXIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setxAxis(@javax.annotation.Nullable Float xAxis) {
    this.xAxis = xAxis;
  }

  public PadesVisualSignature yAxis(@javax.annotation.Nullable Float yAxis) {
    
    this.yAxis = yAxis;
    return this;
  }

  /**
   * Vertical position of the visible signature in pixels
   * minimum: 0
   * @return yAxis
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_Y_AXIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getyAxis() {
    return yAxis;
  }


  @JsonProperty(JSON_PROPERTY_Y_AXIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setyAxis(@javax.annotation.Nullable Float yAxis) {
    this.yAxis = yAxis;
  }

  public PadesVisualSignature width(@javax.annotation.Nullable Integer width) {
    
    this.width = width;
    return this;
  }

  /**
   * Width of the visible signature in pixels. By default, the value will be the width of the image, images and/or the text defined
   * @return width
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWidth() {
    return width;
  }


  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWidth(@javax.annotation.Nullable Integer width) {
    this.width = width;
  }

  public PadesVisualSignature height(@javax.annotation.Nullable Integer height) {
    
    this.height = height;
    return this;
  }

  /**
   * Height of the visible signature in pixels. By default, the value will be the height of the image, images and/or the text defined
   * @return height
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHeight() {
    return height;
  }


  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeight(@javax.annotation.Nullable Integer height) {
    this.height = height;
  }

  public PadesVisualSignature page(@javax.annotation.Nullable Integer page) {
    
    this.page = page;
    return this;
  }

  /**
   * Page where the visible signature will be inserted
   * minimum: 1
   * @return page
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPage() {
    return page;
  }


  @JsonProperty(JSON_PROPERTY_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPage(@javax.annotation.Nullable Integer page) {
    this.page = page;
  }

  public PadesVisualSignature positionInPercentage(@javax.annotation.Nullable Boolean positionInPercentage) {
    
    this.positionInPercentage = positionInPercentage;
    return this;
  }

  /**
   * When true, xAxis and yAxis will be interpreted as percentages
   * @return positionInPercentage
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSITION_IN_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPositionInPercentage() {
    return positionInPercentage;
  }


  @JsonProperty(JSON_PROPERTY_POSITION_IN_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPositionInPercentage(@javax.annotation.Nullable Boolean positionInPercentage) {
    this.positionInPercentage = positionInPercentage;
  }

  public PadesVisualSignature multiImageBuild(@javax.annotation.Nullable MultiImageBuildEnum multiImageBuild) {
    
    this.multiImageBuild = multiImageBuild;
    return this;
  }

  /**
   * If there is more than one image for the visual signature, this parameter will define how this images will be merged into one image
   * @return multiImageBuild
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MULTI_IMAGE_BUILD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MultiImageBuildEnum getMultiImageBuild() {
    return multiImageBuild;
  }


  @JsonProperty(JSON_PROPERTY_MULTI_IMAGE_BUILD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMultiImageBuild(@javax.annotation.Nullable MultiImageBuildEnum multiImageBuild) {
    this.multiImageBuild = multiImageBuild;
  }

  public PadesVisualSignature backgroundColor(@javax.annotation.Nullable List<Integer> backgroundColor) {
    
    this.backgroundColor = backgroundColor;
    return this;
  }

  public PadesVisualSignature addBackgroundColorItem(Integer backgroundColorItem) {
    if (this.backgroundColor == null) {
      this.backgroundColor = new ArrayList<>();
    }
    this.backgroundColor.add(backgroundColorItem);
    return this;
  }

  /**
   * The background color for the signature field in RGBA [0..255, 0..255, 0..255, 0..255]. By default, the color will be white with transparency
   * @return backgroundColor
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BACKGROUND_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getBackgroundColor() {
    return backgroundColor;
  }


  @JsonProperty(JSON_PROPERTY_BACKGROUND_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBackgroundColor(@javax.annotation.Nullable List<Integer> backgroundColor) {
    this.backgroundColor = backgroundColor;
  }

  public PadesVisualSignature imageVerticalAlignment(@javax.annotation.Nullable ImageVerticalAlignmentEnum imageVerticalAlignment) {
    
    this.imageVerticalAlignment = imageVerticalAlignment;
    return this;
  }

  /**
   * Vertical position of the visual signature in the page. In the case where the value is different than NONE and the parameter yAxis has a value different than the default one, the value defined by the parameter imageVerticalAlignment will prevail
   * @return imageVerticalAlignment
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IMAGE_VERTICAL_ALIGNMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ImageVerticalAlignmentEnum getImageVerticalAlignment() {
    return imageVerticalAlignment;
  }


  @JsonProperty(JSON_PROPERTY_IMAGE_VERTICAL_ALIGNMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImageVerticalAlignment(@javax.annotation.Nullable ImageVerticalAlignmentEnum imageVerticalAlignment) {
    this.imageVerticalAlignment = imageVerticalAlignment;
  }

  public PadesVisualSignature fontName(@javax.annotation.Nullable FontNameEnum fontName) {
    
    this.fontName = fontName;
    return this;
  }

  /**
   * Name of the font that will be used for the text
   * @return fontName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FONT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FontNameEnum getFontName() {
    return fontName;
  }


  @JsonProperty(JSON_PROPERTY_FONT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFontName(@javax.annotation.Nullable FontNameEnum fontName) {
    this.fontName = fontName;
  }

  public PadesVisualSignature fontSize(@javax.annotation.Nullable Integer fontSize) {
    
    this.fontSize = fontSize;
    return this;
  }

  /**
   * Letter size
   * minimum: 2
   * @return fontSize
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FONT_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFontSize() {
    return fontSize;
  }


  @JsonProperty(JSON_PROPERTY_FONT_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFontSize(@javax.annotation.Nullable Integer fontSize) {
    this.fontSize = fontSize;
  }

  public PadesVisualSignature textColor(@javax.annotation.Nullable List<Integer> textColor) {
    
    this.textColor = textColor;
    return this;
  }

  public PadesVisualSignature addTextColorItem(Integer textColorItem) {
    if (this.textColor == null) {
      this.textColor = new ArrayList<>();
    }
    this.textColor.add(textColorItem);
    return this;
  }

  /**
   * Text color in RGBA [0..255, 0..255, 0..255, 0..255]. The default text color is black without transparency
   * @return textColor
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXT_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getTextColor() {
    return textColor;
  }


  @JsonProperty(JSON_PROPERTY_TEXT_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextColor(@javax.annotation.Nullable List<Integer> textColor) {
    this.textColor = textColor;
  }

  public PadesVisualSignature text(@javax.annotation.Nullable String text) {
    
    this.text = text;
    return this;
  }

  /**
   * Text of the visual signature. It can contain the following macros for dynamic replacement: %CN% - Certificate Common Name, %DATE% - Signature date, %DATE_TIME% - Signature time
   * @return text
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getText() {
    return text;
  }


  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setText(@javax.annotation.Nullable String text) {
    this.text = text;
  }

  public PadesVisualSignature textSignerPosition(@javax.annotation.Nullable TextSignerPositionEnum textSignerPosition) {
    
    this.textSignerPosition = textSignerPosition;
    return this;
  }

  /**
   * In case there is an image and text defined for the visual signature, this parameter will define the position between these two elements in the visual signature. The default value implies that the image will be at the left part of the visible signature while the text will be at the right part
   * @return textSignerPosition
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXT_SIGNER_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TextSignerPositionEnum getTextSignerPosition() {
    return textSignerPosition;
  }


  @JsonProperty(JSON_PROPERTY_TEXT_SIGNER_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextSignerPosition(@javax.annotation.Nullable TextSignerPositionEnum textSignerPosition) {
    this.textSignerPosition = textSignerPosition;
  }

  public PadesVisualSignature textHorizontalAlignment(@javax.annotation.Nullable TextHorizontalAlignmentEnum textHorizontalAlignment) {
    
    this.textHorizontalAlignment = textHorizontalAlignment;
    return this;
  }

  /**
   * Text alignment
   * @return textHorizontalAlignment
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXT_HORIZONTAL_ALIGNMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TextHorizontalAlignmentEnum getTextHorizontalAlignment() {
    return textHorizontalAlignment;
  }


  @JsonProperty(JSON_PROPERTY_TEXT_HORIZONTAL_ALIGNMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextHorizontalAlignment(@javax.annotation.Nullable TextHorizontalAlignmentEnum textHorizontalAlignment) {
    this.textHorizontalAlignment = textHorizontalAlignment;
  }

  public PadesVisualSignature textImageVerticalAlignment(@javax.annotation.Nullable TextImageVerticalAlignmentEnum textImageVerticalAlignment) {
    
    this.textImageVerticalAlignment = textImageVerticalAlignment;
    return this;
  }

  /**
   * In case there is more than one image with the parameter multiImageBuild with a value of HORIZONTAL and/or an image and text where the parameter textSignerPosition with values LEFT or RIGHT, this parameter defines the vertical alignment between those elements
   * @return textImageVerticalAlignment
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXT_IMAGE_VERTICAL_ALIGNMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TextImageVerticalAlignmentEnum getTextImageVerticalAlignment() {
    return textImageVerticalAlignment;
  }


  @JsonProperty(JSON_PROPERTY_TEXT_IMAGE_VERTICAL_ALIGNMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextImageVerticalAlignment(@javax.annotation.Nullable TextImageVerticalAlignmentEnum textImageVerticalAlignment) {
    this.textImageVerticalAlignment = textImageVerticalAlignment;
  }

  public PadesVisualSignature signLastPage(@javax.annotation.Nullable Boolean signLastPage) {
    
    this.signLastPage = signLastPage;
    return this;
  }

  /**
   * Flag to perform the signature on the last page, ignoring the value defined in the page attribute
   * @return signLastPage
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGN_LAST_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSignLastPage() {
    return signLastPage;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_LAST_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignLastPage(@javax.annotation.Nullable Boolean signLastPage) {
    this.signLastPage = signLastPage;
  }

  public PadesVisualSignature signatureField(@javax.annotation.Nullable String signatureField) {
    
    this.signatureField = signatureField;
    return this;
  }

  /**
   * Indicates the name of the signature field in which the signature will be made. The field must previously exist in the PDF
   * @return signatureField
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNATURE_FIELD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignatureField() {
    return signatureField;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE_FIELD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignatureField(@javax.annotation.Nullable String signatureField) {
    this.signatureField = signatureField;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PadesVisualSignature padesVisualSignature = (PadesVisualSignature) o;
    return Objects.equals(this.xAxis, padesVisualSignature.xAxis) &&
        Objects.equals(this.yAxis, padesVisualSignature.yAxis) &&
        Objects.equals(this.width, padesVisualSignature.width) &&
        Objects.equals(this.height, padesVisualSignature.height) &&
        Objects.equals(this.page, padesVisualSignature.page) &&
        Objects.equals(this.positionInPercentage, padesVisualSignature.positionInPercentage) &&
        Objects.equals(this.multiImageBuild, padesVisualSignature.multiImageBuild) &&
        Objects.equals(this.backgroundColor, padesVisualSignature.backgroundColor) &&
        Objects.equals(this.imageVerticalAlignment, padesVisualSignature.imageVerticalAlignment) &&
        Objects.equals(this.fontName, padesVisualSignature.fontName) &&
        Objects.equals(this.fontSize, padesVisualSignature.fontSize) &&
        Objects.equals(this.textColor, padesVisualSignature.textColor) &&
        Objects.equals(this.text, padesVisualSignature.text) &&
        Objects.equals(this.textSignerPosition, padesVisualSignature.textSignerPosition) &&
        Objects.equals(this.textHorizontalAlignment, padesVisualSignature.textHorizontalAlignment) &&
        Objects.equals(this.textImageVerticalAlignment, padesVisualSignature.textImageVerticalAlignment) &&
        Objects.equals(this.signLastPage, padesVisualSignature.signLastPage) &&
        Objects.equals(this.signatureField, padesVisualSignature.signatureField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(xAxis, yAxis, width, height, page, positionInPercentage, multiImageBuild, backgroundColor, imageVerticalAlignment, fontName, fontSize, textColor, text, textSignerPosition, textHorizontalAlignment, textImageVerticalAlignment, signLastPage, signatureField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PadesVisualSignature {\n");
    sb.append("    xAxis: ").append(toIndentedString(xAxis)).append("\n");
    sb.append("    yAxis: ").append(toIndentedString(yAxis)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    positionInPercentage: ").append(toIndentedString(positionInPercentage)).append("\n");
    sb.append("    multiImageBuild: ").append(toIndentedString(multiImageBuild)).append("\n");
    sb.append("    backgroundColor: ").append(toIndentedString(backgroundColor)).append("\n");
    sb.append("    imageVerticalAlignment: ").append(toIndentedString(imageVerticalAlignment)).append("\n");
    sb.append("    fontName: ").append(toIndentedString(fontName)).append("\n");
    sb.append("    fontSize: ").append(toIndentedString(fontSize)).append("\n");
    sb.append("    textColor: ").append(toIndentedString(textColor)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    textSignerPosition: ").append(toIndentedString(textSignerPosition)).append("\n");
    sb.append("    textHorizontalAlignment: ").append(toIndentedString(textHorizontalAlignment)).append("\n");
    sb.append("    textImageVerticalAlignment: ").append(toIndentedString(textImageVerticalAlignment)).append("\n");
    sb.append("    signLastPage: ").append(toIndentedString(signLastPage)).append("\n");
    sb.append("    signatureField: ").append(toIndentedString(signatureField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

