/*
 * Digital signature API
 * API for digital signatures in Nebula Suite
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model.PadesVisualSignature;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PadesSignatureRequest
 */
@JsonPropertyOrder({
  PadesSignatureRequest.JSON_PROPERTY_SIGN_LEVEL,
  PadesSignatureRequest.JSON_PROPERTY_DIGEST_ALGORITHM,
  PadesSignatureRequest.JSON_PROPERTY_CERT_ID,
  PadesSignatureRequest.JSON_PROPERTY_CERT_PIN,
  PadesSignatureRequest.JSON_PROPERTY_LOCATION,
  PadesSignatureRequest.JSON_PROPERTY_SIGNER_ROLES,
  PadesSignatureRequest.JSON_PROPERTY_COMMITMENT_TYPES,
  PadesSignatureRequest.JSON_PROPERTY_TSA_U_R_L,
  PadesSignatureRequest.JSON_PROPERTY_TSA_U_S_R,
  PadesSignatureRequest.JSON_PROPERTY_TSA_P_W_D,
  PadesSignatureRequest.JSON_PROPERTY_SIGNATURE_SIZE,
  PadesSignatureRequest.JSON_PROPERTY_VISUAL_SIGNATURE,
  PadesSignatureRequest.JSON_PROPERTY_DATE_FORMAT,
  PadesSignatureRequest.JSON_PROPERTY_TIME_ZONE,
  PadesSignatureRequest.JSON_PROPERTY_CERTIFICATION_PERMISSION,
  PadesSignatureRequest.JSON_PROPERTY_APPLICATION,
  PadesSignatureRequest.JSON_PROPERTY_REASON,
  PadesSignatureRequest.JSON_PROPERTY_SIGNER_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class PadesSignatureRequest {
  /**
   * Signature level
   */
  public enum SignLevelEnum {
    B(String.valueOf("B")),
    
    T(String.valueOf("T")),
    
    LT(String.valueOf("LT")),
    
    LTA(String.valueOf("LTA"));

    private String value;

    SignLevelEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SignLevelEnum fromValue(String value) {
      for (SignLevelEnum b : SignLevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SIGN_LEVEL = "signLevel";
  @javax.annotation.Nullable
  private SignLevelEnum signLevel = SignLevelEnum.B;

  /**
   * Algorithm used to obtain the digest of the document to sign
   */
  public enum DigestAlgorithmEnum {
    SHA1(String.valueOf("SHA1")),
    
    SHA256(String.valueOf("SHA256")),
    
    SHA384(String.valueOf("SHA384")),
    
    SHA512(String.valueOf("SHA512"));

    private String value;

    DigestAlgorithmEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DigestAlgorithmEnum fromValue(String value) {
      for (DigestAlgorithmEnum b : DigestAlgorithmEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DIGEST_ALGORITHM = "digestAlgorithm";
  @javax.annotation.Nullable
  private DigestAlgorithmEnum digestAlgorithm = DigestAlgorithmEnum.SHA256;

  public static final String JSON_PROPERTY_CERT_ID = "certId";
  @javax.annotation.Nonnull
  private String certId;

  public static final String JSON_PROPERTY_CERT_PIN = "certPin";
  @javax.annotation.Nullable
  private String certPin;

  public static final String JSON_PROPERTY_LOCATION = "location";
  @javax.annotation.Nullable
  private String location;

  public static final String JSON_PROPERTY_SIGNER_ROLES = "signerRoles";
  @javax.annotation.Nullable
  private List<String> signerRoles = new ArrayList<>();

  /**
   * List of compromises of the signed document. This parameter shall be ignored if the parameter &#39;reason&#39; is defined
   */
  public enum CommitmentTypesEnum {
    PROOF_OF_ORIGIN(String.valueOf("ProofOfOrigin")),
    
    PROOF_OF_RECEIPT(String.valueOf("ProofOfReceipt")),
    
    PROOF_OF_DELIVERY(String.valueOf("ProofOfDelivery")),
    
    PROOF_OF_SENDER(String.valueOf("ProofOfSender")),
    
    PROOF_OF_APPROVAL(String.valueOf("ProofOfApproval")),
    
    PROOF_OF_CREATION(String.valueOf("ProofOfCreation"));

    private String value;

    CommitmentTypesEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CommitmentTypesEnum fromValue(String value) {
      for (CommitmentTypesEnum b : CommitmentTypesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_COMMITMENT_TYPES = "commitmentTypes";
  @javax.annotation.Nullable
  private List<CommitmentTypesEnum> commitmentTypes = new ArrayList<>();

  public static final String JSON_PROPERTY_TSA_U_R_L = "tsaURL";
  @javax.annotation.Nullable
  private String tsaURL;

  public static final String JSON_PROPERTY_TSA_U_S_R = "tsaUSR";
  @javax.annotation.Nullable
  private String tsaUSR;

  public static final String JSON_PROPERTY_TSA_P_W_D = "tsaPWD";
  @javax.annotation.Nullable
  private String tsaPWD;

  public static final String JSON_PROPERTY_SIGNATURE_SIZE = "signatureSize";
  @javax.annotation.Nullable
  private Integer signatureSize;

  public static final String JSON_PROPERTY_VISUAL_SIGNATURE = "visualSignature";
  @javax.annotation.Nullable
  private PadesVisualSignature visualSignature;

  public static final String JSON_PROPERTY_DATE_FORMAT = "dateFormat";
  @javax.annotation.Nullable
  private String dateFormat = "dd/MM/yyyy";

  public static final String JSON_PROPERTY_TIME_ZONE = "timeZone";
  @javax.annotation.Nullable
  private String timeZone = "UTC";

  /**
   * File permissions after signature
   */
  public enum CertificationPermissionEnum {
    NO_CHANGE_PERMITTED(String.valueOf("NO_CHANGE_PERMITTED")),
    
    MINIMAL_CHANGES_PERMITTED(String.valueOf("MINIMAL_CHANGES_PERMITTED")),
    
    CHANGES_PERMITTED(String.valueOf("CHANGES_PERMITTED"));

    private String value;

    CertificationPermissionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CertificationPermissionEnum fromValue(String value) {
      for (CertificationPermissionEnum b : CertificationPermissionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CERTIFICATION_PERMISSION = "certificationPermission";
  @javax.annotation.Nullable
  private CertificationPermissionEnum certificationPermission;

  public static final String JSON_PROPERTY_APPLICATION = "application";
  @javax.annotation.Nullable
  private String application;

  public static final String JSON_PROPERTY_REASON = "reason";
  @javax.annotation.Nullable
  private String reason;

  public static final String JSON_PROPERTY_SIGNER_NAME = "signerName";
  @javax.annotation.Nullable
  private String signerName;

  public PadesSignatureRequest() {
  }

  public PadesSignatureRequest signLevel(@javax.annotation.Nullable SignLevelEnum signLevel) {
    
    this.signLevel = signLevel;
    return this;
  }

  /**
   * Signature level
   * @return signLevel
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGN_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SignLevelEnum getSignLevel() {
    return signLevel;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignLevel(@javax.annotation.Nullable SignLevelEnum signLevel) {
    this.signLevel = signLevel;
  }

  public PadesSignatureRequest digestAlgorithm(@javax.annotation.Nullable DigestAlgorithmEnum digestAlgorithm) {
    
    this.digestAlgorithm = digestAlgorithm;
    return this;
  }

  /**
   * Algorithm used to obtain the digest of the document to sign
   * @return digestAlgorithm
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DigestAlgorithmEnum getDigestAlgorithm() {
    return digestAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDigestAlgorithm(@javax.annotation.Nullable DigestAlgorithmEnum digestAlgorithm) {
    this.digestAlgorithm = digestAlgorithm;
  }

  public PadesSignatureRequest certId(@javax.annotation.Nonnull String certId) {
    
    this.certId = certId;
    return this;
  }

  /**
   * This parameter is linked with the signingId response parameter of the get user certificates operation
   * @return certId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CERT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCertId() {
    return certId;
  }


  @JsonProperty(JSON_PROPERTY_CERT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCertId(@javax.annotation.Nonnull String certId) {
    this.certId = certId;
  }

  public PadesSignatureRequest certPin(@javax.annotation.Nullable String certPin) {
    
    this.certPin = certPin;
    return this;
  }

  /**
   * PIN of the selected certificate
   * @return certPin
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERT_PIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCertPin() {
    return certPin;
  }


  @JsonProperty(JSON_PROPERTY_CERT_PIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertPin(@javax.annotation.Nullable String certPin) {
    this.certPin = certPin;
  }

  public PadesSignatureRequest location(@javax.annotation.Nullable String location) {
    
    this.location = location;
    return this;
  }

  /**
   * The CPU host name or physical location of the signing
   * @return location
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocation() {
    return location;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(@javax.annotation.Nullable String location) {
    this.location = location;
  }

  public PadesSignatureRequest signerRoles(@javax.annotation.Nullable List<String> signerRoles) {
    
    this.signerRoles = signerRoles;
    return this;
  }

  public PadesSignatureRequest addSignerRolesItem(String signerRolesItem) {
    if (this.signerRoles == null) {
      this.signerRoles = new ArrayList<>();
    }
    this.signerRoles.add(signerRolesItem);
    return this;
  }

  /**
   * List of roles of signer
   * @return signerRoles
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNER_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSignerRoles() {
    return signerRoles;
  }


  @JsonProperty(JSON_PROPERTY_SIGNER_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignerRoles(@javax.annotation.Nullable List<String> signerRoles) {
    this.signerRoles = signerRoles;
  }

  public PadesSignatureRequest commitmentTypes(@javax.annotation.Nullable List<CommitmentTypesEnum> commitmentTypes) {
    
    this.commitmentTypes = commitmentTypes;
    return this;
  }

  public PadesSignatureRequest addCommitmentTypesItem(CommitmentTypesEnum commitmentTypesItem) {
    if (this.commitmentTypes == null) {
      this.commitmentTypes = new ArrayList<>();
    }
    this.commitmentTypes.add(commitmentTypesItem);
    return this;
  }

  /**
   * List of compromises of the signed document. This parameter shall be ignored if the parameter &#39;reason&#39; is defined
   * @return commitmentTypes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMITMENT_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CommitmentTypesEnum> getCommitmentTypes() {
    return commitmentTypes;
  }


  @JsonProperty(JSON_PROPERTY_COMMITMENT_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommitmentTypes(@javax.annotation.Nullable List<CommitmentTypesEnum> commitmentTypes) {
    this.commitmentTypes = commitmentTypes;
  }

  public PadesSignatureRequest tsaURL(@javax.annotation.Nullable String tsaURL) {
    
    this.tsaURL = tsaURL;
    return this;
  }

  /**
   * URL of a Timestamping authority to be used in T, LT or LTA signature levels
   * @return tsaURL
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TSA_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTsaURL() {
    return tsaURL;
  }


  @JsonProperty(JSON_PROPERTY_TSA_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTsaURL(@javax.annotation.Nullable String tsaURL) {
    this.tsaURL = tsaURL;
  }

  public PadesSignatureRequest tsaUSR(@javax.annotation.Nullable String tsaUSR) {
    
    this.tsaUSR = tsaUSR;
    return this;
  }

  /**
   * User of the credentials of the Timestamping authority, if authentication is required
   * @return tsaUSR
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TSA_U_S_R)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTsaUSR() {
    return tsaUSR;
  }


  @JsonProperty(JSON_PROPERTY_TSA_U_S_R)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTsaUSR(@javax.annotation.Nullable String tsaUSR) {
    this.tsaUSR = tsaUSR;
  }

  public PadesSignatureRequest tsaPWD(@javax.annotation.Nullable String tsaPWD) {
    
    this.tsaPWD = tsaPWD;
    return this;
  }

  /**
   * Password of the credentials of the Timestamping authority, if authentication is required
   * @return tsaPWD
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TSA_P_W_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTsaPWD() {
    return tsaPWD;
  }


  @JsonProperty(JSON_PROPERTY_TSA_P_W_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTsaPWD(@javax.annotation.Nullable String tsaPWD) {
    this.tsaPWD = tsaPWD;
  }

  public PadesSignatureRequest signatureSize(@javax.annotation.Nullable Integer signatureSize) {
    
    this.signatureSize = signatureSize;
    return this;
  }

  /**
   * Signature size
   * @return signatureSize
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNATURE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSignatureSize() {
    return signatureSize;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignatureSize(@javax.annotation.Nullable Integer signatureSize) {
    this.signatureSize = signatureSize;
  }

  public PadesSignatureRequest visualSignature(@javax.annotation.Nullable PadesVisualSignature visualSignature) {
    
    this.visualSignature = visualSignature;
    return this;
  }

  /**
   * Get visualSignature
   * @return visualSignature
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VISUAL_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PadesVisualSignature getVisualSignature() {
    return visualSignature;
  }


  @JsonProperty(JSON_PROPERTY_VISUAL_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVisualSignature(@javax.annotation.Nullable PadesVisualSignature visualSignature) {
    this.visualSignature = visualSignature;
  }

  public PadesSignatureRequest dateFormat(@javax.annotation.Nullable String dateFormat) {
    
    this.dateFormat = dateFormat;
    return this;
  }

  /**
   * A date format pattern, based on Java&#39;s SimpleDateFormat specification, used for the %DATE% tag in the visual signature.
   * @return dateFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDateFormat() {
    return dateFormat;
  }


  @JsonProperty(JSON_PROPERTY_DATE_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateFormat(@javax.annotation.Nullable String dateFormat) {
    this.dateFormat = dateFormat;
  }

  public PadesSignatureRequest timeZone(@javax.annotation.Nullable String timeZone) {
    
    this.timeZone = timeZone;
    return this;
  }

  /**
   * The value must be a string corresponding to a valid IANA Time Zone Database name.
   * @return timeZone
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME_ZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimeZone() {
    return timeZone;
  }


  @JsonProperty(JSON_PROPERTY_TIME_ZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeZone(@javax.annotation.Nullable String timeZone) {
    this.timeZone = timeZone;
  }

  public PadesSignatureRequest certificationPermission(@javax.annotation.Nullable CertificationPermissionEnum certificationPermission) {
    
    this.certificationPermission = certificationPermission;
    return this;
  }

  /**
   * File permissions after signature
   * @return certificationPermission
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERTIFICATION_PERMISSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CertificationPermissionEnum getCertificationPermission() {
    return certificationPermission;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATION_PERMISSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificationPermission(@javax.annotation.Nullable CertificationPermissionEnum certificationPermission) {
    this.certificationPermission = certificationPermission;
  }

  public PadesSignatureRequest application(@javax.annotation.Nullable String application) {
    
    this.application = application;
    return this;
  }

  /**
   * Application token that grants some permissions
   * @return application
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APPLICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getApplication() {
    return application;
  }


  @JsonProperty(JSON_PROPERTY_APPLICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApplication(@javax.annotation.Nullable String application) {
    this.application = application;
  }

  public PadesSignatureRequest reason(@javax.annotation.Nullable String reason) {
    
    this.reason = reason;
    return this;
  }

  /**
   * Reason for signature
   * @return reason
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReason() {
    return reason;
  }


  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReason(@javax.annotation.Nullable String reason) {
    this.reason = reason;
  }

  public PadesSignatureRequest signerName(@javax.annotation.Nullable String signerName) {
    
    this.signerName = signerName;
    return this;
  }

  /**
   * Signer name
   * @return signerName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignerName() {
    return signerName;
  }


  @JsonProperty(JSON_PROPERTY_SIGNER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignerName(@javax.annotation.Nullable String signerName) {
    this.signerName = signerName;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PadesSignatureRequest padesSignatureRequest = (PadesSignatureRequest) o;
    return Objects.equals(this.signLevel, padesSignatureRequest.signLevel) &&
        Objects.equals(this.digestAlgorithm, padesSignatureRequest.digestAlgorithm) &&
        Objects.equals(this.certId, padesSignatureRequest.certId) &&
        Objects.equals(this.certPin, padesSignatureRequest.certPin) &&
        Objects.equals(this.location, padesSignatureRequest.location) &&
        Objects.equals(this.signerRoles, padesSignatureRequest.signerRoles) &&
        Objects.equals(this.commitmentTypes, padesSignatureRequest.commitmentTypes) &&
        Objects.equals(this.tsaURL, padesSignatureRequest.tsaURL) &&
        Objects.equals(this.tsaUSR, padesSignatureRequest.tsaUSR) &&
        Objects.equals(this.tsaPWD, padesSignatureRequest.tsaPWD) &&
        Objects.equals(this.signatureSize, padesSignatureRequest.signatureSize) &&
        Objects.equals(this.visualSignature, padesSignatureRequest.visualSignature) &&
        Objects.equals(this.dateFormat, padesSignatureRequest.dateFormat) &&
        Objects.equals(this.timeZone, padesSignatureRequest.timeZone) &&
        Objects.equals(this.certificationPermission, padesSignatureRequest.certificationPermission) &&
        Objects.equals(this.application, padesSignatureRequest.application) &&
        Objects.equals(this.reason, padesSignatureRequest.reason) &&
        Objects.equals(this.signerName, padesSignatureRequest.signerName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signLevel, digestAlgorithm, certId, certPin, location, signerRoles, commitmentTypes, tsaURL, tsaUSR, tsaPWD, signatureSize, visualSignature, dateFormat, timeZone, certificationPermission, application, reason, signerName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PadesSignatureRequest {\n");
    sb.append("    signLevel: ").append(toIndentedString(signLevel)).append("\n");
    sb.append("    digestAlgorithm: ").append(toIndentedString(digestAlgorithm)).append("\n");
    sb.append("    certId: ").append(toIndentedString(certId)).append("\n");
    sb.append("    certPin: ").append(toIndentedString(certPin)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    signerRoles: ").append(toIndentedString(signerRoles)).append("\n");
    sb.append("    commitmentTypes: ").append(toIndentedString(commitmentTypes)).append("\n");
    sb.append("    tsaURL: ").append(toIndentedString(tsaURL)).append("\n");
    sb.append("    tsaUSR: ").append(toIndentedString(tsaUSR)).append("\n");
    sb.append("    tsaPWD: ").append(toIndentedString(tsaPWD)).append("\n");
    sb.append("    signatureSize: ").append(toIndentedString(signatureSize)).append("\n");
    sb.append("    visualSignature: ").append(toIndentedString(visualSignature)).append("\n");
    sb.append("    dateFormat: ").append(toIndentedString(dateFormat)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    certificationPermission: ").append(toIndentedString(certificationPermission)).append("\n");
    sb.append("    application: ").append(toIndentedString(application)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    signerName: ").append(toIndentedString(signerName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

