/*
 * Digital signature API
 * API for digital signatures in Nebula Suite
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * XadesSignLocation
 */
@JsonPropertyOrder({
  XadesSignLocation.JSON_PROPERTY_COUNTRY,
  XadesSignLocation.JSON_PROPERTY_LOCALITY,
  XadesSignLocation.JSON_PROPERTY_POSTAL_ADDRESS,
  XadesSignLocation.JSON_PROPERTY_POSTAL_CODE,
  XadesSignLocation.JSON_PROPERTY_STATE_OR_PROVINCE,
  XadesSignLocation.JSON_PROPERTY_STREET
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class XadesSignLocation {
  public static final String JSON_PROPERTY_COUNTRY = "country";
  @javax.annotation.Nullable
  private String country;

  public static final String JSON_PROPERTY_LOCALITY = "locality";
  @javax.annotation.Nullable
  private String locality;

  public static final String JSON_PROPERTY_POSTAL_ADDRESS = "postalAddress";
  @javax.annotation.Nullable
  private List<String> postalAddress = new ArrayList<>();

  public static final String JSON_PROPERTY_POSTAL_CODE = "postalCode";
  @javax.annotation.Nullable
  private String postalCode;

  public static final String JSON_PROPERTY_STATE_OR_PROVINCE = "stateOrProvince";
  @javax.annotation.Nullable
  private String stateOrProvince;

  public static final String JSON_PROPERTY_STREET = "street";
  @javax.annotation.Nullable
  private String street;

  public XadesSignLocation() {
  }

  public XadesSignLocation country(@javax.annotation.Nullable String country) {
    
    this.country = country;
    return this;
  }

  /**
   * Get country
   * @return country
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }

  public XadesSignLocation locality(@javax.annotation.Nullable String locality) {
    
    this.locality = locality;
    return this;
  }

  /**
   * Get locality
   * @return locality
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocality() {
    return locality;
  }


  @JsonProperty(JSON_PROPERTY_LOCALITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocality(@javax.annotation.Nullable String locality) {
    this.locality = locality;
  }

  public XadesSignLocation postalAddress(@javax.annotation.Nullable List<String> postalAddress) {
    
    this.postalAddress = postalAddress;
    return this;
  }

  public XadesSignLocation addPostalAddressItem(String postalAddressItem) {
    if (this.postalAddress == null) {
      this.postalAddress = new ArrayList<>();
    }
    this.postalAddress.add(postalAddressItem);
    return this;
  }

  /**
   * Get postalAddress
   * @return postalAddress
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSTAL_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getPostalAddress() {
    return postalAddress;
  }


  @JsonProperty(JSON_PROPERTY_POSTAL_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPostalAddress(@javax.annotation.Nullable List<String> postalAddress) {
    this.postalAddress = postalAddress;
  }

  public XadesSignLocation postalCode(@javax.annotation.Nullable String postalCode) {
    
    this.postalCode = postalCode;
    return this;
  }

  /**
   * Get postalCode
   * @return postalCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPostalCode() {
    return postalCode;
  }


  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPostalCode(@javax.annotation.Nullable String postalCode) {
    this.postalCode = postalCode;
  }

  public XadesSignLocation stateOrProvince(@javax.annotation.Nullable String stateOrProvince) {
    
    this.stateOrProvince = stateOrProvince;
    return this;
  }

  /**
   * Get stateOrProvince
   * @return stateOrProvince
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE_OR_PROVINCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStateOrProvince() {
    return stateOrProvince;
  }


  @JsonProperty(JSON_PROPERTY_STATE_OR_PROVINCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStateOrProvince(@javax.annotation.Nullable String stateOrProvince) {
    this.stateOrProvince = stateOrProvince;
  }

  public XadesSignLocation street(@javax.annotation.Nullable String street) {
    
    this.street = street;
    return this;
  }

  /**
   * Get street
   * @return street
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STREET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStreet() {
    return street;
  }


  @JsonProperty(JSON_PROPERTY_STREET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStreet(@javax.annotation.Nullable String street) {
    this.street = street;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XadesSignLocation xadesSignLocation = (XadesSignLocation) o;
    return Objects.equals(this.country, xadesSignLocation.country) &&
        Objects.equals(this.locality, xadesSignLocation.locality) &&
        Objects.equals(this.postalAddress, xadesSignLocation.postalAddress) &&
        Objects.equals(this.postalCode, xadesSignLocation.postalCode) &&
        Objects.equals(this.stateOrProvince, xadesSignLocation.stateOrProvince) &&
        Objects.equals(this.street, xadesSignLocation.street);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, locality, postalAddress, postalCode, stateOrProvince, street);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class XadesSignLocation {\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    locality: ").append(toIndentedString(locality)).append("\n");
    sb.append("    postalAddress: ").append(toIndentedString(postalAddress)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    stateOrProvince: ").append(toIndentedString(stateOrProvince)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

