/*
 * Digital signature API
 * API for digital signatures in Nebula Suite
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.fundaciobit.vintegris.nebula.api.client.digitalsignature.v1.model.XadesSignLocation;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * XadesSignatureRequest
 */
@JsonPropertyOrder({
  XadesSignatureRequest.JSON_PROPERTY_CERT_ID,
  XadesSignatureRequest.JSON_PROPERTY_CERT_PIN,
  XadesSignatureRequest.JSON_PROPERTY_CERT_TICKET,
  XadesSignatureRequest.JSON_PROPERTY_COMMITMENT_TYPES,
  XadesSignatureRequest.JSON_PROPERTY_COMPANY,
  XadesSignatureRequest.JSON_PROPERTY_DIGEST_ALGORITHM,
  XadesSignatureRequest.JSON_PROPERTY_FILE_HASH,
  XadesSignatureRequest.JSON_PROPERTY_FILE_HASH_DIGEST_ALGORITHM,
  XadesSignatureRequest.JSON_PROPERTY_FILE_HASH_NAME,
  XadesSignatureRequest.JSON_PROPERTY_POLICY_DIGEST_ALGORITHM,
  XadesSignatureRequest.JSON_PROPERTY_POLICY_HASH,
  XadesSignatureRequest.JSON_PROPERTY_POLICY_ID,
  XadesSignatureRequest.JSON_PROPERTY_POLICY_QUALIFIER,
  XadesSignatureRequest.JSON_PROPERTY_SIGN_CONTAINER,
  XadesSignatureRequest.JSON_PROPERTY_SIGN_LEVEL,
  XadesSignatureRequest.JSON_PROPERTY_SIGN_LOCATION,
  XadesSignatureRequest.JSON_PROPERTY_SIGN_PACKAGE,
  XadesSignatureRequest.JSON_PROPERTY_SIGNER_ROLES,
  XadesSignatureRequest.JSON_PROPERTY_TSA_U_R_L,
  XadesSignatureRequest.JSON_PROPERTY_TSA_U_S_R,
  XadesSignatureRequest.JSON_PROPERTY_TSA_P_W_D,
  XadesSignatureRequest.JSON_PROPERTY_USER_ID,
  XadesSignatureRequest.JSON_PROPERTY_USER_UUID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class XadesSignatureRequest {
  public static final String JSON_PROPERTY_CERT_ID = "certId";
  @javax.annotation.Nullable
  private String certId;

  public static final String JSON_PROPERTY_CERT_PIN = "certPin";
  @javax.annotation.Nullable
  private String certPin;

  public static final String JSON_PROPERTY_CERT_TICKET = "certTicket";
  @javax.annotation.Nullable
  private String certTicket;

  public static final String JSON_PROPERTY_COMMITMENT_TYPES = "commitmentTypes";
  @javax.annotation.Nullable
  private List<String> commitmentTypes = new ArrayList<>();

  public static final String JSON_PROPERTY_COMPANY = "company";
  @javax.annotation.Nullable
  private String company;

  /**
   * Algorithm used to obtain the digest of the document to sign
   */
  public enum DigestAlgorithmEnum {
    SHA1(String.valueOf("SHA1")),
    
    SHA256(String.valueOf("SHA256")),
    
    SHA384(String.valueOf("SHA384")),
    
    SHA512(String.valueOf("SHA512"));

    private String value;

    DigestAlgorithmEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DigestAlgorithmEnum fromValue(String value) {
      for (DigestAlgorithmEnum b : DigestAlgorithmEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DIGEST_ALGORITHM = "digestAlgorithm";
  @javax.annotation.Nullable
  private DigestAlgorithmEnum digestAlgorithm = DigestAlgorithmEnum.SHA256;

  public static final String JSON_PROPERTY_FILE_HASH = "fileHash";
  @javax.annotation.Nullable
  private String fileHash;

  public static final String JSON_PROPERTY_FILE_HASH_DIGEST_ALGORITHM = "fileHashDigestAlgorithm";
  @javax.annotation.Nullable
  private String fileHashDigestAlgorithm;

  public static final String JSON_PROPERTY_FILE_HASH_NAME = "fileHashName";
  @javax.annotation.Nullable
  private String fileHashName;

  public static final String JSON_PROPERTY_POLICY_DIGEST_ALGORITHM = "policyDigestAlgorithm";
  @javax.annotation.Nullable
  private String policyDigestAlgorithm;

  public static final String JSON_PROPERTY_POLICY_HASH = "policyHash";
  @javax.annotation.Nullable
  private String policyHash;

  public static final String JSON_PROPERTY_POLICY_ID = "policyId";
  @javax.annotation.Nullable
  private String policyId;

  public static final String JSON_PROPERTY_POLICY_QUALIFIER = "policyQualifier";
  @javax.annotation.Nullable
  private String policyQualifier;

  public static final String JSON_PROPERTY_SIGN_CONTAINER = "signContainer";
  @javax.annotation.Nullable
  private String signContainer;

  /**
   * Signature level
   */
  public enum SignLevelEnum {
    B(String.valueOf("B")),
    
    T(String.valueOf("T")),
    
    LT(String.valueOf("LT")),
    
    LTA(String.valueOf("LTA"));

    private String value;

    SignLevelEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SignLevelEnum fromValue(String value) {
      for (SignLevelEnum b : SignLevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SIGN_LEVEL = "signLevel";
  @javax.annotation.Nullable
  private SignLevelEnum signLevel = SignLevelEnum.B;

  public static final String JSON_PROPERTY_SIGN_LOCATION = "signLocation";
  @javax.annotation.Nullable
  private XadesSignLocation signLocation;

  /**
   * Signature Mode
   */
  public enum SignPackageEnum {
    DETACHED(String.valueOf("DETACHED")),
    
    ENVELOPED(String.valueOf("ENVELOPED")),
    
    ENVELOPING(String.valueOf("ENVELOPING"));

    private String value;

    SignPackageEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SignPackageEnum fromValue(String value) {
      for (SignPackageEnum b : SignPackageEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SIGN_PACKAGE = "signPackage";
  @javax.annotation.Nullable
  private SignPackageEnum signPackage;

  public static final String JSON_PROPERTY_SIGNER_ROLES = "signerRoles";
  @javax.annotation.Nullable
  private List<String> signerRoles = new ArrayList<>();

  public static final String JSON_PROPERTY_TSA_U_R_L = "tsaURL";
  @javax.annotation.Nullable
  private String tsaURL;

  public static final String JSON_PROPERTY_TSA_U_S_R = "tsaUSR";
  @javax.annotation.Nullable
  private String tsaUSR;

  public static final String JSON_PROPERTY_TSA_P_W_D = "tsaPWD";
  @javax.annotation.Nullable
  private String tsaPWD;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  @javax.annotation.Nullable
  private String userId;

  public static final String JSON_PROPERTY_USER_UUID = "userUuid";
  @javax.annotation.Nullable
  private String userUuid;

  public XadesSignatureRequest() {
  }

  public XadesSignatureRequest certId(@javax.annotation.Nullable String certId) {
    
    this.certId = certId;
    return this;
  }

  /**
   * This parameter is linked with the signingId response parameter of the get user certificates operation
   * @return certId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCertId() {
    return certId;
  }


  @JsonProperty(JSON_PROPERTY_CERT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertId(@javax.annotation.Nullable String certId) {
    this.certId = certId;
  }

  public XadesSignatureRequest certPin(@javax.annotation.Nullable String certPin) {
    
    this.certPin = certPin;
    return this;
  }

  /**
   * PIN of the selected certificate
   * @return certPin
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERT_PIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCertPin() {
    return certPin;
  }


  @JsonProperty(JSON_PROPERTY_CERT_PIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertPin(@javax.annotation.Nullable String certPin) {
    this.certPin = certPin;
  }

  public XadesSignatureRequest certTicket(@javax.annotation.Nullable String certTicket) {
    
    this.certTicket = certTicket;
    return this;
  }

  /**
   * Get certTicket
   * @return certTicket
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERT_TICKET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCertTicket() {
    return certTicket;
  }


  @JsonProperty(JSON_PROPERTY_CERT_TICKET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertTicket(@javax.annotation.Nullable String certTicket) {
    this.certTicket = certTicket;
  }

  public XadesSignatureRequest commitmentTypes(@javax.annotation.Nullable List<String> commitmentTypes) {
    
    this.commitmentTypes = commitmentTypes;
    return this;
  }

  public XadesSignatureRequest addCommitmentTypesItem(String commitmentTypesItem) {
    if (this.commitmentTypes == null) {
      this.commitmentTypes = new ArrayList<>();
    }
    this.commitmentTypes.add(commitmentTypesItem);
    return this;
  }

  /**
   * Get commitmentTypes
   * @return commitmentTypes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMITMENT_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getCommitmentTypes() {
    return commitmentTypes;
  }


  @JsonProperty(JSON_PROPERTY_COMMITMENT_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommitmentTypes(@javax.annotation.Nullable List<String> commitmentTypes) {
    this.commitmentTypes = commitmentTypes;
  }

  public XadesSignatureRequest company(@javax.annotation.Nullable String company) {
    
    this.company = company;
    return this;
  }

  /**
   * Get company
   * @return company
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCompany() {
    return company;
  }


  @JsonProperty(JSON_PROPERTY_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompany(@javax.annotation.Nullable String company) {
    this.company = company;
  }

  public XadesSignatureRequest digestAlgorithm(@javax.annotation.Nullable DigestAlgorithmEnum digestAlgorithm) {
    
    this.digestAlgorithm = digestAlgorithm;
    return this;
  }

  /**
   * Algorithm used to obtain the digest of the document to sign
   * @return digestAlgorithm
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DigestAlgorithmEnum getDigestAlgorithm() {
    return digestAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDigestAlgorithm(@javax.annotation.Nullable DigestAlgorithmEnum digestAlgorithm) {
    this.digestAlgorithm = digestAlgorithm;
  }

  public XadesSignatureRequest fileHash(@javax.annotation.Nullable String fileHash) {
    
    this.fileHash = fileHash;
    return this;
  }

  /**
   * Get fileHash
   * @return fileHash
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILE_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFileHash() {
    return fileHash;
  }


  @JsonProperty(JSON_PROPERTY_FILE_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileHash(@javax.annotation.Nullable String fileHash) {
    this.fileHash = fileHash;
  }

  public XadesSignatureRequest fileHashDigestAlgorithm(@javax.annotation.Nullable String fileHashDigestAlgorithm) {
    
    this.fileHashDigestAlgorithm = fileHashDigestAlgorithm;
    return this;
  }

  /**
   * Get fileHashDigestAlgorithm
   * @return fileHashDigestAlgorithm
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILE_HASH_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFileHashDigestAlgorithm() {
    return fileHashDigestAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_FILE_HASH_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileHashDigestAlgorithm(@javax.annotation.Nullable String fileHashDigestAlgorithm) {
    this.fileHashDigestAlgorithm = fileHashDigestAlgorithm;
  }

  public XadesSignatureRequest fileHashName(@javax.annotation.Nullable String fileHashName) {
    
    this.fileHashName = fileHashName;
    return this;
  }

  /**
   * Get fileHashName
   * @return fileHashName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILE_HASH_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFileHashName() {
    return fileHashName;
  }


  @JsonProperty(JSON_PROPERTY_FILE_HASH_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileHashName(@javax.annotation.Nullable String fileHashName) {
    this.fileHashName = fileHashName;
  }

  public XadesSignatureRequest policyDigestAlgorithm(@javax.annotation.Nullable String policyDigestAlgorithm) {
    
    this.policyDigestAlgorithm = policyDigestAlgorithm;
    return this;
  }

  /**
   * Get policyDigestAlgorithm
   * @return policyDigestAlgorithm
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POLICY_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPolicyDigestAlgorithm() {
    return policyDigestAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_POLICY_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPolicyDigestAlgorithm(@javax.annotation.Nullable String policyDigestAlgorithm) {
    this.policyDigestAlgorithm = policyDigestAlgorithm;
  }

  public XadesSignatureRequest policyHash(@javax.annotation.Nullable String policyHash) {
    
    this.policyHash = policyHash;
    return this;
  }

  /**
   * Get policyHash
   * @return policyHash
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POLICY_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPolicyHash() {
    return policyHash;
  }


  @JsonProperty(JSON_PROPERTY_POLICY_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPolicyHash(@javax.annotation.Nullable String policyHash) {
    this.policyHash = policyHash;
  }

  public XadesSignatureRequest policyId(@javax.annotation.Nullable String policyId) {
    
    this.policyId = policyId;
    return this;
  }

  /**
   * Get policyId
   * @return policyId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POLICY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPolicyId() {
    return policyId;
  }


  @JsonProperty(JSON_PROPERTY_POLICY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPolicyId(@javax.annotation.Nullable String policyId) {
    this.policyId = policyId;
  }

  public XadesSignatureRequest policyQualifier(@javax.annotation.Nullable String policyQualifier) {
    
    this.policyQualifier = policyQualifier;
    return this;
  }

  /**
   * Get policyQualifier
   * @return policyQualifier
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POLICY_QUALIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPolicyQualifier() {
    return policyQualifier;
  }


  @JsonProperty(JSON_PROPERTY_POLICY_QUALIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPolicyQualifier(@javax.annotation.Nullable String policyQualifier) {
    this.policyQualifier = policyQualifier;
  }

  public XadesSignatureRequest signContainer(@javax.annotation.Nullable String signContainer) {
    
    this.signContainer = signContainer;
    return this;
  }

  /**
   * Get signContainer
   * @return signContainer
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGN_CONTAINER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignContainer() {
    return signContainer;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_CONTAINER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignContainer(@javax.annotation.Nullable String signContainer) {
    this.signContainer = signContainer;
  }

  public XadesSignatureRequest signLevel(@javax.annotation.Nullable SignLevelEnum signLevel) {
    
    this.signLevel = signLevel;
    return this;
  }

  /**
   * Signature level
   * @return signLevel
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGN_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SignLevelEnum getSignLevel() {
    return signLevel;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignLevel(@javax.annotation.Nullable SignLevelEnum signLevel) {
    this.signLevel = signLevel;
  }

  public XadesSignatureRequest signLocation(@javax.annotation.Nullable XadesSignLocation signLocation) {
    
    this.signLocation = signLocation;
    return this;
  }

  /**
   * Get signLocation
   * @return signLocation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGN_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public XadesSignLocation getSignLocation() {
    return signLocation;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignLocation(@javax.annotation.Nullable XadesSignLocation signLocation) {
    this.signLocation = signLocation;
  }

  public XadesSignatureRequest signPackage(@javax.annotation.Nullable SignPackageEnum signPackage) {
    
    this.signPackage = signPackage;
    return this;
  }

  /**
   * Signature Mode
   * @return signPackage
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGN_PACKAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SignPackageEnum getSignPackage() {
    return signPackage;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_PACKAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignPackage(@javax.annotation.Nullable SignPackageEnum signPackage) {
    this.signPackage = signPackage;
  }

  public XadesSignatureRequest signerRoles(@javax.annotation.Nullable List<String> signerRoles) {
    
    this.signerRoles = signerRoles;
    return this;
  }

  public XadesSignatureRequest addSignerRolesItem(String signerRolesItem) {
    if (this.signerRoles == null) {
      this.signerRoles = new ArrayList<>();
    }
    this.signerRoles.add(signerRolesItem);
    return this;
  }

  /**
   * Get signerRoles
   * @return signerRoles
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNER_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSignerRoles() {
    return signerRoles;
  }


  @JsonProperty(JSON_PROPERTY_SIGNER_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignerRoles(@javax.annotation.Nullable List<String> signerRoles) {
    this.signerRoles = signerRoles;
  }

  public XadesSignatureRequest tsaURL(@javax.annotation.Nullable String tsaURL) {
    
    this.tsaURL = tsaURL;
    return this;
  }

  /**
   * URL of a Timestamping authority to be used in T, LT or LTA signature levels
   * @return tsaURL
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TSA_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTsaURL() {
    return tsaURL;
  }


  @JsonProperty(JSON_PROPERTY_TSA_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTsaURL(@javax.annotation.Nullable String tsaURL) {
    this.tsaURL = tsaURL;
  }

  public XadesSignatureRequest tsaUSR(@javax.annotation.Nullable String tsaUSR) {
    
    this.tsaUSR = tsaUSR;
    return this;
  }

  /**
   * User of the credentials of the Timestamping authority, if authentication is required
   * @return tsaUSR
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TSA_U_S_R)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTsaUSR() {
    return tsaUSR;
  }


  @JsonProperty(JSON_PROPERTY_TSA_U_S_R)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTsaUSR(@javax.annotation.Nullable String tsaUSR) {
    this.tsaUSR = tsaUSR;
  }

  public XadesSignatureRequest tsaPWD(@javax.annotation.Nullable String tsaPWD) {
    
    this.tsaPWD = tsaPWD;
    return this;
  }

  /**
   * Password of the credentials of the Timestamping authority, if authentication is required
   * @return tsaPWD
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TSA_P_W_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTsaPWD() {
    return tsaPWD;
  }


  @JsonProperty(JSON_PROPERTY_TSA_P_W_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTsaPWD(@javax.annotation.Nullable String tsaPWD) {
    this.tsaPWD = tsaPWD;
  }

  public XadesSignatureRequest userId(@javax.annotation.Nullable String userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
  }

  public XadesSignatureRequest userUuid(@javax.annotation.Nullable String userUuid) {
    
    this.userUuid = userUuid;
    return this;
  }

  /**
   * Get userUuid
   * @return userUuid
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserUuid() {
    return userUuid;
  }


  @JsonProperty(JSON_PROPERTY_USER_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserUuid(@javax.annotation.Nullable String userUuid) {
    this.userUuid = userUuid;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XadesSignatureRequest xadesSignatureRequest = (XadesSignatureRequest) o;
    return Objects.equals(this.certId, xadesSignatureRequest.certId) &&
        Objects.equals(this.certPin, xadesSignatureRequest.certPin) &&
        Objects.equals(this.certTicket, xadesSignatureRequest.certTicket) &&
        Objects.equals(this.commitmentTypes, xadesSignatureRequest.commitmentTypes) &&
        Objects.equals(this.company, xadesSignatureRequest.company) &&
        Objects.equals(this.digestAlgorithm, xadesSignatureRequest.digestAlgorithm) &&
        Objects.equals(this.fileHash, xadesSignatureRequest.fileHash) &&
        Objects.equals(this.fileHashDigestAlgorithm, xadesSignatureRequest.fileHashDigestAlgorithm) &&
        Objects.equals(this.fileHashName, xadesSignatureRequest.fileHashName) &&
        Objects.equals(this.policyDigestAlgorithm, xadesSignatureRequest.policyDigestAlgorithm) &&
        Objects.equals(this.policyHash, xadesSignatureRequest.policyHash) &&
        Objects.equals(this.policyId, xadesSignatureRequest.policyId) &&
        Objects.equals(this.policyQualifier, xadesSignatureRequest.policyQualifier) &&
        Objects.equals(this.signContainer, xadesSignatureRequest.signContainer) &&
        Objects.equals(this.signLevel, xadesSignatureRequest.signLevel) &&
        Objects.equals(this.signLocation, xadesSignatureRequest.signLocation) &&
        Objects.equals(this.signPackage, xadesSignatureRequest.signPackage) &&
        Objects.equals(this.signerRoles, xadesSignatureRequest.signerRoles) &&
        Objects.equals(this.tsaURL, xadesSignatureRequest.tsaURL) &&
        Objects.equals(this.tsaUSR, xadesSignatureRequest.tsaUSR) &&
        Objects.equals(this.tsaPWD, xadesSignatureRequest.tsaPWD) &&
        Objects.equals(this.userId, xadesSignatureRequest.userId) &&
        Objects.equals(this.userUuid, xadesSignatureRequest.userUuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certId, certPin, certTicket, commitmentTypes, company, digestAlgorithm, fileHash, fileHashDigestAlgorithm, fileHashName, policyDigestAlgorithm, policyHash, policyId, policyQualifier, signContainer, signLevel, signLocation, signPackage, signerRoles, tsaURL, tsaUSR, tsaPWD, userId, userUuid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class XadesSignatureRequest {\n");
    sb.append("    certId: ").append(toIndentedString(certId)).append("\n");
    sb.append("    certPin: ").append(toIndentedString(certPin)).append("\n");
    sb.append("    certTicket: ").append(toIndentedString(certTicket)).append("\n");
    sb.append("    commitmentTypes: ").append(toIndentedString(commitmentTypes)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    digestAlgorithm: ").append(toIndentedString(digestAlgorithm)).append("\n");
    sb.append("    fileHash: ").append(toIndentedString(fileHash)).append("\n");
    sb.append("    fileHashDigestAlgorithm: ").append(toIndentedString(fileHashDigestAlgorithm)).append("\n");
    sb.append("    fileHashName: ").append(toIndentedString(fileHashName)).append("\n");
    sb.append("    policyDigestAlgorithm: ").append(toIndentedString(policyDigestAlgorithm)).append("\n");
    sb.append("    policyHash: ").append(toIndentedString(policyHash)).append("\n");
    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("    policyQualifier: ").append(toIndentedString(policyQualifier)).append("\n");
    sb.append("    signContainer: ").append(toIndentedString(signContainer)).append("\n");
    sb.append("    signLevel: ").append(toIndentedString(signLevel)).append("\n");
    sb.append("    signLocation: ").append(toIndentedString(signLocation)).append("\n");
    sb.append("    signPackage: ").append(toIndentedString(signPackage)).append("\n");
    sb.append("    signerRoles: ").append(toIndentedString(signerRoles)).append("\n");
    sb.append("    tsaURL: ").append(toIndentedString(tsaURL)).append("\n");
    sb.append("    tsaUSR: ").append(toIndentedString(tsaUSR)).append("\n");
    sb.append("    tsaPWD: ").append(toIndentedString(tsaPWD)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    userUuid: ").append(toIndentedString(userUuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

