
pluginname=Plugin de Firma Web de Firma Cloud Fortress de ViaFirma


esperar=Esperant a que l'usuari s'autentiqui...
cancel=Cancel·lar
tornar=Tornar

reintentar=Reintentar
pipellabloquejada=Si veu aquest missatge el que ha passat és que el seu navegador ha bloquejat la finestra que s´ha obert.<br/> Revisi missatges d´error a la part superior del seu navegador i accepti mostrar noves finestres.<br/> Després pitji el boto Reintentar.  
