<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>pluginsib-signatureweb</artifactId>
        <groupId>org.fundaciobit.pluginsib.signatureweb</groupId>
        <version>4.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>pluginsib-signatureweb-fortress</artifactId>
    <name>FundacioBit - PluginsIB - SignatureWeb - ViaFirma-Fortress</name>
    <packaging>jar</packaging>

    <properties>
        <fortress-sdk.version>4.6.2</fortress-sdk.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.fundaciobit.pluginsib.signatureweb</groupId>
            <artifactId>pluginsib-signatureweb-api</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.signatureweb</groupId>
            <artifactId>pluginsib-signatureweb-miniappletutils</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
        </dependency>

        <!-- Les dependències de okhttp3 que té viafirma no funcionen amb
        TLSv1.2 #554 -->
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
        </dependency>

        <dependency>
            <groupId>com.viafirma.fortress</groupId>
            <artifactId>viafirma-fortress-sdk-java</artifactId>
            <version>${fortress-sdk.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.squareup.okhttp3</groupId>
                    <artifactId>logging-interceptor</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>logging-interceptor</artifactId>
            <version>3.12.12</version>
        </dependency>

    </dependencies>
<!--
    <repositories>
        <repository>
            <id>Viavansi</id>
            <url>https://repositorio.viavansi.com/repo</url>
        </repository>
    </repositories>
-->
</project>