package org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.api;

import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.services.ApiException;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.services.ApiClient;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.services.Configuration;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.services.Pair;

import javax.ws.rs.core.GenericType;

import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model.NebulaResponse;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model.NebulaResponseAuthorizeResponseViewModel;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model.NebulaResponseLoginResponseViewModel;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class AuthenticationApi {
  private ApiClient apiClient;

  public AuthenticationApi() {
    this(Configuration.getDefaultApiClient());
  }

  public AuthenticationApi(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  public ApiClient getApiClient() {
    return apiClient;
  }

  public void setApiClient(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  /**
   * First factor login
   * It is used to obtain a simple nebulaSUITE token from the specified user
   * @param application Token generated by the authorize endpoint (required)
   * @param username User UID in base64 (required)
   * @return a {@code NebulaResponseLoginResponseViewModel}
   * @throws ApiException if fails to make API call
   */
  public NebulaResponseLoginResponseViewModel appLoginFirst(String application, String username) throws ApiException {
    Object localVarPostBody = null;
    
    // verify the required parameter 'application' is set
    if (application == null) {
      throw new ApiException(400, "Missing the required parameter 'application' when calling appLoginFirst");
    }
    
    // verify the required parameter 'username' is set
    if (username == null) {
      throw new ApiException(400, "Missing the required parameter 'username' when calling appLoginFirst");
    }
    
    // create path and map variables
    String localVarPath = "/trusted/app/login/first".replaceAll("\\{format\\}","json");

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    localVarQueryParams.addAll(apiClient.parameterToPairs("", "username", username));

    if (application != null)
      localVarHeaderParams.put("application", apiClient.parameterToString(application));

    
    
    final String[] localVarAccepts = {
      "*/*"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "nebulasuite" };

    GenericType<NebulaResponseLoginResponseViewModel> localVarReturnType = new GenericType<NebulaResponseLoginResponseViewModel>() {};
    return apiClient.invokeAPI(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAccept, localVarContentType, localVarAuthNames, localVarReturnType);
      }
  /**
   * Second factor login
   * It is used to obtain a robust nebulaSUITE token from the specified user
   * @param application Token generated by the authorize endpoint (required)
   * @param authorization Simple nebulaSUITE token (required)
   * @return a {@code NebulaResponseLoginResponseViewModel}
   * @throws ApiException if fails to make API call
   */
  public NebulaResponseLoginResponseViewModel appLoginSecond(String application, String authorization) throws ApiException {
    Object localVarPostBody = null;
    
    // verify the required parameter 'application' is set
    if (application == null) {
      throw new ApiException(400, "Missing the required parameter 'application' when calling appLoginSecond");
    }
    
    // verify the required parameter 'authorization' is set
    if (authorization == null) {
      throw new ApiException(400, "Missing the required parameter 'authorization' when calling appLoginSecond");
    }
    
    // create path and map variables
    String localVarPath = "/trusted/app/login/second".replaceAll("\\{format\\}","json");

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();


    if (application != null)
      localVarHeaderParams.put("application", apiClient.parameterToString(application));
if (authorization != null)
      localVarHeaderParams.put("Authorization", apiClient.parameterToString(authorization));

    
    
    final String[] localVarAccepts = {
      "*/*"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "nebulasuite" };

    GenericType<NebulaResponseLoginResponseViewModel> localVarReturnType = new GenericType<NebulaResponseLoginResponseViewModel>() {};
    return apiClient.invokeAPI(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAccept, localVarContentType, localVarAuthNames, localVarReturnType);
      }
  /**
   * Authorize an trusted app
   * It is used to obtain the token necessary for the trusted app to consume the permissions it has
   * @param authorization Token generated by the trusted app (optional)
   * @return a {@code NebulaResponseAuthorizeResponseViewModel}
   * @throws ApiException if fails to make API call
   */
  public NebulaResponseAuthorizeResponseViewModel authorize(String authorization) throws ApiException {
    Object localVarPostBody = null;
    
    // create path and map variables
    String localVarPath = "/trusted/app/authorize".replaceAll("\\{format\\}","json");

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();


    if (authorization != null)
      localVarHeaderParams.put("Authorization", apiClient.parameterToString(authorization));

    
    
    final String[] localVarAccepts = {
      "*/*"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "nebulasuite" };

    GenericType<NebulaResponseAuthorizeResponseViewModel> localVarReturnType = new GenericType<NebulaResponseAuthorizeResponseViewModel>() {};
    return apiClient.invokeAPI(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAccept, localVarContentType, localVarAuthNames, localVarReturnType);
      }
  /**
   * Validate permissions of a user in the trusted app
   * Used to check if the user has the requested permissions from the trusted app
   * @param application Token generated by the authorize endpoint (required)
   * @param authorization nebulaSUITE token (required)
   * @param permission Trusted app permission (optional)
   * @return a {@code NebulaResponse}
   * @throws ApiException if fails to make API call
   */
  public NebulaResponse validatePermission(String application, String authorization, String permission) throws ApiException {
    Object localVarPostBody = null;
    
    // verify the required parameter 'application' is set
    if (application == null) {
      throw new ApiException(400, "Missing the required parameter 'application' when calling validatePermission");
    }
    
    // verify the required parameter 'authorization' is set
    if (authorization == null) {
      throw new ApiException(400, "Missing the required parameter 'authorization' when calling validatePermission");
    }
    
    // create path and map variables
    String localVarPath = "/trusted/app/validate".replaceAll("\\{format\\}","json");

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    localVarQueryParams.addAll(apiClient.parameterToPairs("", "permission", permission));

    if (application != null)
      localVarHeaderParams.put("application", apiClient.parameterToString(application));
if (authorization != null)
      localVarHeaderParams.put("Authorization", apiClient.parameterToString(authorization));

    
    
    final String[] localVarAccepts = {
      "*/*"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "nebulasuite" };

    GenericType<NebulaResponse> localVarReturnType = new GenericType<NebulaResponse>() {};
    return apiClient.invokeAPI(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAccept, localVarContentType, localVarAuthNames, localVarReturnType);
      }
}
