/*
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.authentication.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AuthViewModel
 */
@JsonPropertyOrder({
  AuthViewModel.JSON_PROPERTY_USERNAME,
  AuthViewModel.JSON_PROPERTY_PASSWORD,
  AuthViewModel.JSON_PROPERTY_TUID,
  AuthViewModel.JSON_PROPERTY_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class AuthViewModel {
  public static final String JSON_PROPERTY_USERNAME = "username";
  @javax.annotation.Nonnull
  private String username;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  @javax.annotation.Nonnull
  private String password;

  public static final String JSON_PROPERTY_TUID = "tuid";
  @javax.annotation.Nullable
  private String tuid;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nullable
  private String url;

  public AuthViewModel() {
  }

  public AuthViewModel username(@javax.annotation.Nonnull String username) {
    
    this.username = username;
    return this;
  }

  /**
   * The user identifier
   * @return username
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUsername(@javax.annotation.Nonnull String username) {
    this.username = username;
  }

  public AuthViewModel password(@javax.annotation.Nonnull String password) {
    
    this.password = password;
    return this;
  }

  /**
   * The user password
   * @return password
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPassword(@javax.annotation.Nonnull String password) {
    this.password = password;
  }

  public AuthViewModel tuid(@javax.annotation.Nullable String tuid) {
    
    this.tuid = tuid;
    return this;
  }

  /**
   * The client identifier (not necessary if url is set)
   * @return tuid
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTuid() {
    return tuid;
  }


  @JsonProperty(JSON_PROPERTY_TUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTuid(@javax.annotation.Nullable String tuid) {
    this.tuid = tuid;
  }

  public AuthViewModel url(@javax.annotation.Nullable String url) {
    
    this.url = url;
    return this;
  }

  /**
   * The url (not necessary if client identifier is set)
   * @return url
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = url;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthViewModel authViewModel = (AuthViewModel) o;
    return Objects.equals(this.username, authViewModel.username) &&
        Objects.equals(this.password, authViewModel.password) &&
        Objects.equals(this.tuid, authViewModel.tuid) &&
        Objects.equals(this.url, authViewModel.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(username, password, tuid, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthViewModel {\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    tuid: ").append(toIndentedString(tuid)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

