/*
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.authentication.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SessionAndChallengeViewModel
 */
@JsonPropertyOrder({
  SessionAndChallengeViewModel.JSON_PROPERTY_SESSION,
  SessionAndChallengeViewModel.JSON_PROPERTY_CHALLENGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class SessionAndChallengeViewModel {
  public static final String JSON_PROPERTY_SESSION = "session";
  @javax.annotation.Nonnull
  private String session;

  public static final String JSON_PROPERTY_CHALLENGE = "challenge";
  @javax.annotation.Nonnull
  private String challenge;

  public SessionAndChallengeViewModel() {
  }

  public SessionAndChallengeViewModel session(@javax.annotation.Nonnull String session) {
    
    this.session = session;
    return this;
  }

  /**
   * The authentication session
   * @return session
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SESSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSession() {
    return session;
  }


  @JsonProperty(JSON_PROPERTY_SESSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSession(@javax.annotation.Nonnull String session) {
    this.session = session;
  }

  public SessionAndChallengeViewModel challenge(@javax.annotation.Nonnull String challenge) {
    
    this.challenge = challenge;
    return this;
  }

  /**
   * The solved challenge
   * @return challenge
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CHALLENGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getChallenge() {
    return challenge;
  }


  @JsonProperty(JSON_PROPERTY_CHALLENGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChallenge(@javax.annotation.Nonnull String challenge) {
    this.challenge = challenge;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionAndChallengeViewModel sessionAndChallengeViewModel = (SessionAndChallengeViewModel) o;
    return Objects.equals(this.session, sessionAndChallengeViewModel.session) &&
        Objects.equals(this.challenge, sessionAndChallengeViewModel.challenge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(session, challenge);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionAndChallengeViewModel {\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("    challenge: ").append(toIndentedString(challenge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

