/*
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.authentication.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TokenWithLevelViewModel
 */
@JsonPropertyOrder({
  TokenWithLevelViewModel.JSON_PROPERTY_TOKEN,
  TokenWithLevelViewModel.JSON_PROPERTY_LVL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class TokenWithLevelViewModel {
  public static final String JSON_PROPERTY_TOKEN = "token";
  @javax.annotation.Nonnull
  private String token;

  public static final String JSON_PROPERTY_LVL = "lvl";
  @javax.annotation.Nonnull
  private String lvl;

  public TokenWithLevelViewModel() {
  }

  public TokenWithLevelViewModel token(@javax.annotation.Nonnull String token) {
    
    this.token = token;
    return this;
  }

  /**
   * JWT Token
   * @return token
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToken() {
    return token;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToken(@javax.annotation.Nonnull String token) {
    this.token = token;
  }

  public TokenWithLevelViewModel lvl(@javax.annotation.Nonnull String lvl) {
    
    this.lvl = lvl;
    return this;
  }

  /**
   * level
   * @return lvl
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LVL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLvl() {
    return lvl;
  }


  @JsonProperty(JSON_PROPERTY_LVL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLvl(@javax.annotation.Nonnull String lvl) {
    this.lvl = lvl;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokenWithLevelViewModel tokenWithLevelViewModel = (TokenWithLevelViewModel) o;
    return Objects.equals(this.token, tokenWithLevelViewModel.token) &&
        Objects.equals(this.lvl, tokenWithLevelViewModel.lvl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, lvl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokenWithLevelViewModel {\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    lvl: ").append(toIndentedString(lvl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

