/*
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.authentication.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TokenWithChallengeVierModel
 */
@JsonPropertyOrder({
  TokenWithChallengeVierModel.JSON_PROPERTY_TOKEN,
  TokenWithChallengeVierModel.JSON_PROPERTY_LVL,
  TokenWithChallengeVierModel.JSON_PROPERTY_CHALLENGE,
  TokenWithChallengeVierModel.JSON_PROPERTY_SESSION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class TokenWithChallengeVierModel {
  public static final String JSON_PROPERTY_TOKEN = "token";
  @javax.annotation.Nullable
  private String token;

  public static final String JSON_PROPERTY_LVL = "lvl";
  @javax.annotation.Nullable
  private String lvl;

  public static final String JSON_PROPERTY_CHALLENGE = "challenge";
  @javax.annotation.Nullable
  private String challenge;

  public static final String JSON_PROPERTY_SESSION = "session";
  @javax.annotation.Nullable
  private String session;

  public TokenWithChallengeVierModel() {
  }

  public TokenWithChallengeVierModel token(@javax.annotation.Nullable String token) {
    
    this.token = token;
    return this;
  }

  /**
   * Authentication token (Authorization header must contain this value on next operations)
   * @return token
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToken() {
    return token;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToken(@javax.annotation.Nullable String token) {
    this.token = token;
  }

  public TokenWithChallengeVierModel lvl(@javax.annotation.Nullable String lvl) {
    
    this.lvl = lvl;
    return this;
  }

  /**
   * The authentication level. One of [simple, authentication, robust]
   * @return lvl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LVL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLvl() {
    return lvl;
  }


  @JsonProperty(JSON_PROPERTY_LVL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLvl(@javax.annotation.Nullable String lvl) {
    this.lvl = lvl;
  }

  public TokenWithChallengeVierModel challenge(@javax.annotation.Nullable String challenge) {
    
    this.challenge = challenge;
    return this;
  }

  /**
   * The authentication challenge
   * @return challenge
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHALLENGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getChallenge() {
    return challenge;
  }


  @JsonProperty(JSON_PROPERTY_CHALLENGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChallenge(@javax.annotation.Nullable String challenge) {
    this.challenge = challenge;
  }

  public TokenWithChallengeVierModel session(@javax.annotation.Nullable String session) {
    
    this.session = session;
    return this;
  }

  /**
   * The authentication session
   * @return session
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SESSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSession() {
    return session;
  }


  @JsonProperty(JSON_PROPERTY_SESSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSession(@javax.annotation.Nullable String session) {
    this.session = session;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokenWithChallengeVierModel tokenWithChallengeVierModel = (TokenWithChallengeVierModel) o;
    return Objects.equals(this.token, tokenWithChallengeVierModel.token) &&
        Objects.equals(this.lvl, tokenWithChallengeVierModel.lvl) &&
        Objects.equals(this.challenge, tokenWithChallengeVierModel.challenge) &&
        Objects.equals(this.session, tokenWithChallengeVierModel.session);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, lvl, challenge, session);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokenWithChallengeVierModel {\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    lvl: ").append(toIndentedString(lvl)).append("\n");
    sb.append("    challenge: ").append(toIndentedString(challenge)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

