/*
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.authentication.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TokenWithAuthenticatorsViewModel
 */
@JsonPropertyOrder({
  TokenWithAuthenticatorsViewModel.JSON_PROPERTY_TOKEN,
  TokenWithAuthenticatorsViewModel.JSON_PROPERTY_AUTHENTICATORS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class TokenWithAuthenticatorsViewModel {
  public static final String JSON_PROPERTY_TOKEN = "token";
  @javax.annotation.Nullable
  private String token;

  public static final String JSON_PROPERTY_AUTHENTICATORS = "authenticators";
  @javax.annotation.Nullable
  private List<String> authenticators = new ArrayList<>();

  public TokenWithAuthenticatorsViewModel() {
  }

  public TokenWithAuthenticatorsViewModel token(@javax.annotation.Nullable String token) {
    
    this.token = token;
    return this;
  }

  /**
   * Authentication token (Authorization header must contain this value on next operations)
   * @return token
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToken() {
    return token;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToken(@javax.annotation.Nullable String token) {
    this.token = token;
  }

  public TokenWithAuthenticatorsViewModel authenticators(@javax.annotation.Nullable List<String> authenticators) {
    
    this.authenticators = authenticators;
    return this;
  }

  public TokenWithAuthenticatorsViewModel addAuthenticatorsItem(String authenticatorsItem) {
    if (this.authenticators == null) {
      this.authenticators = new ArrayList<>();
    }
    this.authenticators.add(authenticatorsItem);
    return this;
  }

  /**
   * List containing the available authenticators
   * @return authenticators
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTHENTICATORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getAuthenticators() {
    return authenticators;
  }


  @JsonProperty(JSON_PROPERTY_AUTHENTICATORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthenticators(@javax.annotation.Nullable List<String> authenticators) {
    this.authenticators = authenticators;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokenWithAuthenticatorsViewModel tokenWithAuthenticatorsViewModel = (TokenWithAuthenticatorsViewModel) o;
    return Objects.equals(this.token, tokenWithAuthenticatorsViewModel.token) &&
        Objects.equals(this.authenticators, tokenWithAuthenticatorsViewModel.authenticators);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, authenticators);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokenWithAuthenticatorsViewModel {\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    authenticators: ").append(toIndentedString(authenticators)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

