nebula=Plugin de Nebula (Vintegris)

pluginname=Plugin de Firma Web de Nebula (Vintegris)

cancel=Cancel·lar
certificatfirmar=Certificat amb què signar
selectcertificat.titol=Seleccioneu el certificat per firmar
tipusfirma.desconegut=Tipus de signatura amb ID {0} no està suportat pel plugin `{1}`
tornar=Tornar
valid=Vàlid fins {0}
warn.notecertificats=No té certificats en el repositori del servidor o els que té no passen el filtre requerit. Consulti amb el seu administrador de Vintegris.

firmar=Signar
error.firmantdocument=Error en signar el document
error.nodefinitpasswordpin=No ha definit la contrasenya o el PIN
error.pinerroni=El PIN introduït no és correcte
nopassafiltre=NO<br>PASSA<br>FILTRE
pin=PIN
pin.error=El PIN introduït no és correcte
pinassociatacertificat=PIN associat al certificat
pin.requiredalert=No pot deixar el camp PIN buit



authenticatormethod.ONE_TIME_PASSWORD_OTP=Se us requerirà que obri l´aplicació d´autenticació al seu mòbil.
authenticatormethod.MOBILE_SMS=Se us enviarà un codi d´un sol ús al seu mòbil mitjançant un SMS.
authenticatormethod.DIRECT_ACCESS=No requereix cap tipus de contraseña

selectauthenticatormethod.titol=Seleccioneu el mètode d´autenticació
selectauthenticatormethod.submit=Continuar

mobilesmspassword.titol=Escriure codi SMS rebut
mobilesmspassword.label=Introduïu la clau de nebulaSUITE enviada al vostre mòbil mitjançant un SMS 
mobilesmspassword.submit=Continua
mobilesmspassword.error=El codi SMS introduït no és correcte

onetimepasswordotp.titol=Verificació de seguretat
onetimepasswordotp.label=Per accedir-hi, introduïu el codi de 6 dígits que es mostra a la vostra aplicació d'autenticació
onetimepasswordotp.submit=Continua
onetimepasswordotp.error=El codi OTP introduït no és correcte

error.filter.obligatori=Abans de cridar al mètode signDocuments() ha de cridar al mètode filter().
error.autenticadors.nuls=El llistat de sistemes d´Autenticació val nul la qual cosa significa que no s´ha cridat al mètode filter() abans de cridar al mètode signDocuments(). Tornau-ho a intentar i si el problema persisteix contacti amb suport.
error.sessio.cache.noexisteix=No s´ha trobat la sessió de cache de Nebula per al SignaturesSetID {0} la qual cosa significa que no s´ha cridat al mètode filter() abans de cridar al mètode signDocuments(). Tornau-ho a intentar i si el problema persisteix contacti amb suport.
error.autenticador.nosuportat=El mètode d´autenticació seleccionat {0} no està suportat pel plugin de firma web de Nebula.
error.filtre.autenticador.desconegut=S´ha obtingut un mètode d´autenticació desconegut al filtre de configuració: {0}
error.global.preparant.firma=Error global preparant per signar: {0}
error.certificats.buits=La llista de certificats de l´usuari està buida. No s´ha executat el mètode filter() o s´ha fet neteja de la informació de cache. Tornau-ho a intentar i si el problema persisteix contacti amb suport.
error.politiques.buides=No s´ha pogut recuperar les polítiques associades als certificats de l´usuari. Tornau-ho a intentar i si el problema persisteix contacti amb suport.
error.politica.certificat.noexisteix=No s´ha pogut recuperar la política associada al ID de certificat {0}. Tornau-ho a intentar i si el problema persisteix contacti amb suport.
error.tipus.firma.nosuportat=Tipus de firma {0} no suportat pel {1}
error.api.firma=Error d´API realitzant la firma: {0} (Code: {1}, Body: {2})
error.realitzant.firma=Error realitzant la firma: {0}
error.global.realitzant.firmes=Error global realitzant les firmes: {0}
error.xades.firma=Error realitzant la firma XAdES: Code {0}, Msg: {1}
error.xades.excepcio=Excepció realitzant la firma XAdES: Code {0}, Msg: {1}
error.certificat.no.seleccionat=No s´ha elegit el Certificat amb el que vol signar. Tornau-ho a intentar i si el problema persisteix contacti amb suport.
error.otp.clau.bloc=S´ha equivocat massa vegades amb la clau introduïda ({0}). Pitgi el botó de Cancel·lar i torni a intentar-ho en 5 minuts.
error.otp.clau.incorrecta=La clau introduïda no és correcta. Torni a intentar-ho.
error.otp.authsecond=Error fent la cridada a authSecond en OTP: {0}
error.otp.authsecond.inesperat=Error inesperat en la cridada a authSecond en OTP: {0}
error.sms.bloc=El sistema d´autenticació SMS per l´usuari {0} està bloquejat. Pitgi el botó de Cancel·lar i torni a intentar-ho més tard (5 minuts)
error.sms.clau.bloc=S´ha equivocat massa vegades amb la clau introduïda ({0}). Pitgi el botó de Cancel·lar i torni a intentar-ho en 5 minuts.
error.sms.clau.incorrecta=La clau introduïda ({0}) no és correcta. Torni a intentar-ho.
error.sms.authsecond=Error fent la cridada a authSecond en SMS: {0}
error.certificat.no.trobat=No s´ha trobat el certificat amb ID {0} dins de la llista de certificats de l´usuari {1}
error.authmethods.null=Error obtenint els mètodes d´autenticació de l´usuari {0}. authMethods és null
error.authmethods.codi=Error obtenint els mètodes d´autenticació de l´usuari {0}. Codi Final no és l´esperat. authMethods.getCode() = {1}, authMethods.getMessage() = {2}
error.authmethods.content.null=Error obtenint els mètodes d´autenticació de l´usuari {0}. authMethods.getContent() és null
error.authmethods.authenticadors.buits=Error obtenint els mètodes d´autenticació de l´usuari {0}. El llistat d´autenticadors és buit o null