nebula=Plugin de Nebula (Vintegris)

pluginname=Plugin de Firma Web de Nebula (Vintegris)

cancel=Cancel·lar
certificatfirmar=Certificat amb què signar
selectcertificat.titol=Seleccioneu el certificat per firmar
tipusfirma.desconegut=Tipus de signatura amb ID {0} no està suportat pel plugin `{1}`
tornar=Tornar
valid=Vàlid fins {0}
warn.notecertificats=No té certificats en el repositori del servidor o els que té no passen el filtre requerit. Consulti amb el seu administrador de Vintegris.

firmar=Signar
error.firmantdocument=Error en signar el document
error.nodefinitpasswordpin=No ha definit la contrasenya o el PIN
error.pinerroni=El PIN introduït no és correcte
nopassafiltre=NO<br>PASSA<br>FILTRE
pin=PIN
pin.error=El PIN introduït no és correcte
pinassociatacertificat=PIN associat al certificat
pin.requiredalert=No pot deixar el camp PIN buit
