nebula=Plugin de Nebula (Vintegris)
pluginname=Plugin de Firma Web de Nebula (Vintegris)


cancel=Cancel·lar
certificatfirmar=Certificat amb el que firmar
error.firmantdocument=Error firmant document
firmadocument=Firmar Document
firmardocument.plural=Firmar Documents 
selectcertificat.titol=Seleccioni Certificat amb el que Firmar
tipusfirma.desconegut=Tipus de Firma amb ID {0}  no està suportat pel plugin `{1}`
tornar=Tornar
valid=Vàlid des de {0} fins {1}
warn.notecertificats=No té certificats en el repositori del servidor. Consulti amb l'administrador de sistemes.


certificatfirmar=Certificat amb el que firmar
firmadocument=Firmar Document
firmardocument.plural=Firmar Documents 
error.firmantdocument=Error firmant document
error.nodefinitpasswordpin=No ha definit el password o el pin
error.pinerroni=El PIN introduit no es correcte
nopassafiltre=NO<br>PASSA<br>FILTRE
pin=PIN
pinassociatacertificat=PIN associat al certificat
selectcertificat.titol=Seleccioni Certificat amb el que Firmar
tornar=Tornar
valid=Vàlid des de {0} fins {1}
warn.notecertificats=No té certificats en el repositori del servidor o els que té no passen el filtre requerit. Consulti amb el seu administrador de Vintegris. 
tipusfirma.desconegut=Tipus de Firma amb ID {0}  no està suportat pel plugin `{1}`
nopinrequired=No es requereix PIN per a aquest certificat