/*
 * Trusted Applications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.api;

import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.services.ApiException;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model.NebulaResponse;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model.NebulaResponseAuthorizeResponseViewModel;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model.NebulaResponseLoginResponseViewModel;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticationApi
 */
class AuthenticationApiTest {

    private final AuthenticationApi api = new AuthenticationApi();

    /**
     * First factor login
     *
     * It is used to obtain a simple nebulaSUITE token from the specified user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void appLoginFirstTest() throws ApiException {
        //
        //String application = null;
        //
        //String username = null;
        //
        //NebulaResponseLoginResponseViewModel response = api.appLoginFirst(application, username);

        // TODO: test validations
    }
    /**
     * Second factor login
     *
     * It is used to obtain a robust nebulaSUITE token from the specified user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void appLoginSecondTest() throws ApiException {
        //
        //String application = null;
        //
        //String authorization = null;
        //
        //NebulaResponseLoginResponseViewModel response = api.appLoginSecond(application, authorization);

        // TODO: test validations
    }
    /**
     * Authorize an trusted app
     *
     * It is used to obtain the token necessary for the trusted app to consume the permissions it has
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void authorizeTest() throws ApiException {
        //
        //String authorization = null;
        //
        //NebulaResponseAuthorizeResponseViewModel response = api.authorize(authorization);

        // TODO: test validations
    }
    /**
     * Validate permissions of a user in the trusted app
     *
     * Used to check if the user has the requested permissions from the trusted app
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void validatePermissionTest() throws ApiException {
        //
        //String application = null;
        //
        //String authorization = null;
        //
        //String permission = null;
        //
        //NebulaResponse response = api.validatePermission(application, authorization, permission);

        // TODO: test validations
    }
}
