/*
 * Trusted Applications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.api;

import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.services.ApiException;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model.CreateTrustedAppViewModel;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model.NebulaResponse;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model.NebulaResponseDetailedTrustedAppViewModel;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model.NebulaResponseListTrustedAppViewModel;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ManageTrustedAppApi
 */
class ManageTrustedAppApiTest {

    private final ManageTrustedAppApi api = new ManageTrustedAppApi();

    /**
     * Create a new trusted app
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void createTrustedAppTest() throws ApiException {
        //
        //CreateTrustedAppViewModel createTrustedAppViewModel = null;
        //
        //NebulaResponseDetailedTrustedAppViewModel response = api.createTrustedApp(createTrustedAppViewModel);

        // TODO: test validations
    }
    /**
     * Delete a trusted app
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void deleteTrustedAppTest() throws ApiException {
        //
        //String id = null;
        //
        //NebulaResponse response = api.deleteTrustedApp(id);

        // TODO: test validations
    }
    /**
     * Get a specific trusted app
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getTrustedAppTest() throws ApiException {
        //
        //String id = null;
        //
        //NebulaResponseDetailedTrustedAppViewModel response = api.getTrustedApp(id);

        // TODO: test validations
    }
    /**
     * Get list of trusted apps created in the system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getTrustedAppsTest() throws ApiException {
        //
        //Integer page = null;
        //
        //Integer size = null;
        //
        //NebulaResponseListTrustedAppViewModel response = api.getTrustedApps(page, size);

        // TODO: test validations
    }
    /**
     * Update a trusted app
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void updateTrustedAppTest() throws ApiException {
        //
        //String id = null;
        //
        //CreateTrustedAppViewModel createTrustedAppViewModel = null;
        //
        //NebulaResponseDetailedTrustedAppViewModel response = api.updateTrustedApp(id, createTrustedAppViewModel);

        // TODO: test validations
    }
}
