/*
 * Trusted Applications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.api;

import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.services.ApiException;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model.AccessGroupsViewModel;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model.NebulaResponse;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model.NebulaResponseListGroupViewModel;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ManageGroupsApi
 */
class ManageGroupsApiTest {

    private final ManageGroupsApi api = new ManageGroupsApi();

    /**
     * Modify the groups assigned to a trusted app
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void changeGroupsTest() throws ApiException {
        //
        //String id = null;
        //
        //AccessGroupsViewModel accessGroupsViewModel = null;
        //
        //NebulaResponse response = api.changeGroups(id, accessGroupsViewModel);

        // TODO: test validations
    }
    /**
     * Get list of all groups configured in a trusted app
     *
     * List only the groups of a trusted app
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getAllGroupsTest() throws ApiException {
        //
        //String id = null;
        //
        //NebulaResponseListGroupViewModel response = api.getAllGroups(id);

        // TODO: test validations
    }
}
