/*
 * Trusted Applications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.api;

import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.services.ApiException;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model.NebulaResponse;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model.NebulaResponseRegenerateTrustedAppViewModel;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model.PermissionsBody;
import org.fundaciobit.vintegris.nebula.api.client.trustedapplications.v1.model.TrustedAppSecParamsViewModel;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ManageTrustedAppPermissionsApi
 */
class ManageTrustedAppPermissionsApiTest {

    private final ManageTrustedAppPermissionsApi api = new ManageTrustedAppPermissionsApi();

    /**
     * Modify the permissions assigned to a trusted app
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void changePermissionsTest() throws ApiException {
        //
        //String id = null;
        //
        //PermissionsBody permissionsBody = null;
        //
        //NebulaResponse response = api.changePermissions(id, permissionsBody);

        // TODO: test validations
    }
    /**
     * Generate signature key for trusted app authorization
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void regenerateAccessKeyTest() throws ApiException {
        //
        //String id = null;
        //
        //NebulaResponseRegenerateTrustedAppViewModel response = api.regenerateAccessKey(id);

        // TODO: test validations
    }
    /**
     * Modify the security parameters assigned to a trusted app
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void setSecurityParametersTest() throws ApiException {
        //
        //String id = null;
        //
        //TrustedAppSecParamsViewModel trustedAppSecParamsViewModel = null;
        //
        //NebulaResponse response = api.setSecurityParameters(id, trustedAppSecParamsViewModel);

        // TODO: test validations
    }
}
