<?xml version="1.0" encoding="UTF-8"?>
<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>pluginsib-signatureweb</artifactId>
        <groupId>org.fundaciobit.pluginsib.signatureweb</groupId>
        <version>4.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>pluginsib-signatureweb-signaturewebtester</artifactId>
    <packaging>war</packaging>
    <name>FundacioBit - PluginsIB - SignatureWeb - Tester</name>

    <properties>
        <maven-site-plugin.skip>true</maven-site-plugin.skip>
    </properties>

    <dependencies>

        <!-- Servlet API -->
        <dependency>
            <groupId>org.jboss.spec.javax.servlet</groupId>
            <artifactId>jboss-servlet-api_4.0_spec</artifactId>
            <scope>provided</scope>
        </dependency>


        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>jstl</artifactId>
            <version>1.2</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.signatureweb</groupId>
            <artifactId>pluginsib-signatureweb-fire</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.signatureweb</groupId>
            <artifactId>pluginsib-signatureweb-fortress</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.signatureweb</groupId>
            <artifactId>pluginsib-signatureweb-afirma_triphase_server</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.signatureweb</groupId>
            <artifactId>pluginsib-signatureweb-miniappletinserversia</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.signatureweb</groupId>
            <artifactId>pluginsib-signatureweb-fnmtcloud</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.signatureweb</groupId>
            <artifactId>pluginsib-signatureweb-firmanocriptografica</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.timestamp</groupId>
            <artifactId>pluginsib-timestamp-afirmarfc-cliente_tsa_rfc</artifactId>
            <version>2.1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>htmlunit-driver</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>fluent-hc</artifactId>
            <version>4.5.13</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.warrenstrange</groupId>
            <artifactId>googleauth</artifactId>
            <version>1.4.0</version>
            <scope>test</scope>
        </dependency>

    </dependencies>







    <profiles>
    
        <!-- Profile jboss72: actiu per defecte -->
        <profile>
            <id>jboss72_def</id>
            <activation>
                <property>
                    <name>!jboss</name>
                </property>
            </activation>
            <dependencies>
                <!-- Dependències específiques per a JBoss 7.2 -->
                <dependency>
                    <groupId>javax.activation</groupId>
                    <artifactId>activation</artifactId>
                    <type>jar</type>
                </dependency>

                <dependency>
                    <groupId>javax.inject</groupId>
                    <artifactId>javax.inject</artifactId>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>javax.enterprise</groupId>
                    <artifactId>cdi-api</artifactId>
                </dependency>
            </dependencies>
        </profile>
    
    
        <!-- Profile jboss72: actiu per propietat -->
        <profile>
            <id>jboss72_explicit</id>
            <activation>
                <property>
                    <name>jboss</name>
                    <value>7.2</value>
                </property>
            </activation>
            <dependencies>
                <!-- Dependències específiques per a JBoss 7.2 -->
                <dependency>
                    <groupId>javax.activation</groupId>
                    <artifactId>activation</artifactId>
                </dependency>

                <dependency>
                    <groupId>javax.inject</groupId>
                    <artifactId>javax.inject</artifactId>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>javax.enterprise</groupId>
                    <artifactId>cdi-api</artifactId>
                </dependency>

            </dependencies>
        </profile>

        <!-- Profile jboss74: se activa manualmente -->
        <profile>
            <id>jboss74_explicit</id>
            <activation>
                <property>
                    <name>jboss</name>
                    <value>7.4</value>
                </property>
            </activation>
            <dependencies>
                <!-- Dependències específiques per a JBoss 7.4 -->
                <dependency>
                    <groupId>jakarta.activation</groupId>
                    <artifactId>jakarta.activation-api</artifactId>
                    <version>1.2.2.redhat-00001</version>
                </dependency>

                <dependency>
                    <groupId>jakarta.inject</groupId>
                    <artifactId>jakarta.inject-api</artifactId>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>jakarta.enterprise</groupId>
                    <artifactId>jakarta.enterprise.cdi-api</artifactId>
                    <scope>provided</scope>
                </dependency>
            </dependencies>
        </profile>
    </profiles>


    <build>
        <finalName>signaturewebtester</finalName>

        <plugins>
            <plugin>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>

    </build>

</project>