/*
 * Nebula Certificates API
 * API for issuing, activating, and managing digital certificates in Nebula Suite.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.api;

import org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.services.ApiException;
import org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model.ChangeCertificatePinRequest;
import org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model.DelegateCertificateUserRequest;
import org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model.DeleteCertificateRequest;
import org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model.ImportCertificateRequest;
import java.time.LocalDate;
import org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model.RequestCertificateReportRequest;
import org.fundaciobit.vintegris.nebula.api.client.digitalcertificate.v1.model.RequestKeystoreCertificateRequest;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DigitalCertificateApi
 */
class DigitalCertificateApiTest {

    private final DigitalCertificateApi api = new DigitalCertificateApi();

    /**
     * Activate Certificate
     *
     * Activates an issued certificate once the issue status is ENROLL.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void activateCertificateTest() throws ApiException {
        //
        //String requestId = null;
        //
        //api.activateCertificate(requestId);

        // TODO: test validations
    }
    /**
     * Find Certificates to Sign
     *
     * Gets the user&#39;s certificate list that can be used to perform signature operations.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void availableForSigningTest() throws ApiException {
        //
        //Integer offset = null;
        //
        //Integer limit = null;
        //
        //api.availableForSigning(offset, limit);

        // TODO: test validations
    }
    /**
     * Change Certificate PIN
     *
     * Changes the PIN associated with a digital certificate.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void changeCertificatePinTest() throws ApiException {
        //
        //ChangeCertificatePinRequest changeCertificatePinRequest = null;
        //
        //api.changeCertificatePin(changeCertificatePinRequest);

        // TODO: test validations
    }
    /**
     * Delegate User Certificate
     *
     * Delegates a certificate to another user in the system.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void delegateCertificateUserTest() throws ApiException {
        //
        //DelegateCertificateUserRequest delegateCertificateUserRequest = null;
        //
        //api.delegateCertificateUser(delegateCertificateUserRequest);

        // TODO: test validations
    }
    /**
     * Delete Certificate
     *
     * Delete a certificate from the system.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void deleteCertificateTest() throws ApiException {
        //
        //DeleteCertificateRequest deleteCertificateRequest = null;
        //
        //api.deleteCertificate(deleteCertificateRequest);

        // TODO: test validations
    }
    /**
     * Get Certificate
     *
     * Returns the certificate data for the certificate identified by the given id.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getCertificateByIdTest() throws ApiException {
        //
        //String certificateId = null;
        //
        //api.getCertificateById(certificateId);

        // TODO: test validations
    }
    /**
     * Get Policy
     *
     * Returns the policy linked to the given user and certificate id.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getCertificatePolicyTest() throws ApiException {
        //
        //String certificateId = null;
        //
        //api.getCertificatePolicy(certificateId);

        // TODO: test validations
    }
    /**
     * Get User Certificates
     *
     * Gets the user&#39;s certificate list and returns its search result that fulfills the given input search criteria. The caller must have role admin, owner or signer.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getMyCertificatesTest() throws ApiException {
        //
        //Integer offset = null;
        //
        //Integer limit = null;
        //
        //String enableFilter = null;
        //
        //String expireFilter = null;
        //
        //String certType = null;
        //
        //Boolean isOrphan = null;
        //
        //LocalDate dateValidStart = null;
        //
        //api.getMyCertificates(offset, limit, enableFilter, expireFilter, certType, isOrphan, dateValidStart);

        // TODO: test validations
    }
    /**
     * Import Certificate
     *
     * Import a certificate into the system (PFX / PKCS#12 in base64).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void importCertificateTest() throws ApiException {
        //
        //ImportCertificateRequest importCertificateRequest = null;
        //
        //api.importCertificate(importCertificateRequest);

        // TODO: test validations
    }
    /**
     * Issue Certificate
     *
     * Issues a requested certificate. This operation is asynchronous — to execute Activate Certificate, wait until the request issue status is ENROLL.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void issueCertificateTest() throws ApiException {
        //
        //String requestId = null;
        //
        //api.issueCertificate(requestId);

        // TODO: test validations
    }
    /**
     * Request Certificate Report
     *
     * Requests a report (sent by email) with certificates information.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void requestCertificateReportTest() throws ApiException {
        //
        //RequestCertificateReportRequest requestCertificateReportRequest = null;
        //
        //api.requestCertificateReport(requestCertificateReportRequest);

        // TODO: test validations
    }
    /**
     * Request Keystore Certificate
     *
     * Requests a new certificate to be issued and stored in the keystore.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void requestKeystoreCertificateTest() throws ApiException {
        //
        //RequestKeystoreCertificateRequest requestKeystoreCertificateRequest = null;
        //
        //api.requestKeystoreCertificate(requestKeystoreCertificateRequest);

        // TODO: test validations
    }
}
